//This code has been automatically generated by DudeLabs, LLC RCConverter
using System;
using System.Drawing;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;
namespace CS_testSecurity5
{
	/// <summary>
	/// Summary description for FrmSamrtpoesampleDialog.
	/// </summary>

	partial class FrmSamrtpoesampleDialog : System.Windows.Forms.Form
		{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.Container components = null;
        private System.Windows.Forms.Label lblStatic1;
        private System.Windows.Forms.ComboBox cboComboCardNumber;
        private System.Windows.Forms.Label lblStatic2;
        private System.Windows.Forms.TextBox txtEditId;
        private System.Windows.Forms.TextBox txtEditDcgetbuf0;
        private System.Windows.Forms.Label lblStatic3;
        private System.Windows.Forms.Label lblStatic4;
        private System.Windows.Forms.TextBox txtEditError;
        private System.Windows.Forms.Label lblStatic5;
        private System.Windows.Forms.TextBox txtEditId14;
        private System.Windows.Forms.Label lblStatic6;
        private System.Windows.Forms.TextBox txtEditId15;
        private System.Windows.Forms.Label lblStatic7;
        private System.Windows.Forms.TextBox txtEditId16;
        private System.Windows.Forms.Button btnButtonSet4;
        private System.Windows.Forms.GroupBox grpStatic8;
        private System.Windows.Forms.Label lblStatic9;
        private System.Windows.Forms.TextBox txtEditId18;
        private System.Windows.Forms.TextBox txtEditId19;
        private System.Windows.Forms.Label lblStatic10;
        private System.Windows.Forms.Label lblStatic11;
        private System.Windows.Forms.TextBox txtEditId20;
        private System.Windows.Forms.Button btnButtonSet29;
        private System.Windows.Forms.Button btnButtonSet30;
        private System.Windows.Forms.Button btnButtonSet31;
        private System.Windows.Forms.Button btnButtonSet32;
        private System.Windows.Forms.TextBox txtEditDcgetbuf5;
        private System.Windows.Forms.TextBox txtEditDcgetbuf6;
        private System.Windows.Forms.Button btnButtonSet33;
        //public System.Windows.Forms.TextBox[] txtEditDcsetbuf = new System.Windows.Forms.TextBox[32];




		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		protected override void Dispose( bool disposing )
		{
			if( disposing )
			{
				if (components != null) 
				{
					components.Dispose();
				}
			}
			base.Dispose( disposing );
		}

					#region DudeLabs LLC RCConverter generated code
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
            this.lblStatic1 = new System.Windows.Forms.Label();
            this.cboComboCardNumber = new System.Windows.Forms.ComboBox();
            this.lblStatic2 = new System.Windows.Forms.Label();
            this.txtEditId = new System.Windows.Forms.TextBox();
            this.txtEditDcgetbuf0 = new System.Windows.Forms.TextBox();
            this.lblStatic3 = new System.Windows.Forms.Label();
            this.lblStatic4 = new System.Windows.Forms.Label();
            this.txtEditError = new System.Windows.Forms.TextBox();
            this.lblStatic5 = new System.Windows.Forms.Label();
            this.txtEditId14 = new System.Windows.Forms.TextBox();
            this.lblStatic6 = new System.Windows.Forms.Label();
            this.txtEditId15 = new System.Windows.Forms.TextBox();
            this.lblStatic7 = new System.Windows.Forms.Label();
            this.txtEditId16 = new System.Windows.Forms.TextBox();
            this.btnButtonSet4 = new System.Windows.Forms.Button();
            this.grpStatic8 = new System.Windows.Forms.GroupBox();
            this.lblStatic10 = new System.Windows.Forms.Label();
            this.lblStatic11 = new System.Windows.Forms.Label();
            this.lblStatic9 = new System.Windows.Forms.Label();
            this.txtEditId18 = new System.Windows.Forms.TextBox();
            this.txtEditId19 = new System.Windows.Forms.TextBox();
            this.txtEditId20 = new System.Windows.Forms.TextBox();
            this.btnButtonSet29 = new System.Windows.Forms.Button();
            this.btnButtonSet30 = new System.Windows.Forms.Button();
            this.btnButtonSet31 = new System.Windows.Forms.Button();
            this.btnButtonSet32 = new System.Windows.Forms.Button();
            this.txtEditDcgetbuf5 = new System.Windows.Forms.TextBox();
            this.txtEditDcgetbuf6 = new System.Windows.Forms.TextBox();
            this.btnButtonSet33 = new System.Windows.Forms.Button();
            this.panel2 = new System.Windows.Forms.Panel();
            this.rdoRadio1On1 = new System.Windows.Forms.RadioButton();
            this.rdoRadio1Off1 = new System.Windows.Forms.RadioButton();
            this.lblStatic13 = new System.Windows.Forms.Label();
            this.panel3 = new System.Windows.Forms.Panel();
            this.rdoRadio1Off2 = new System.Windows.Forms.RadioButton();
            this.rdoRadio1On2 = new System.Windows.Forms.RadioButton();
            this.lblStatic14 = new System.Windows.Forms.Label();
            this.panel4 = new System.Windows.Forms.Panel();
            this.rdoRadio1Off4 = new System.Windows.Forms.RadioButton();
            this.rdoRadio1On4 = new System.Windows.Forms.RadioButton();
            this.lblStatic16 = new System.Windows.Forms.Label();
            this.panel5 = new System.Windows.Forms.Panel();
            this.rdoRadio1Off3 = new System.Windows.Forms.RadioButton();
            this.rdoRadio1On3 = new System.Windows.Forms.RadioButton();
            this.lblStatic15 = new System.Windows.Forms.Label();
            this.panel6 = new System.Windows.Forms.Panel();
            this.rdoRadio1Off8 = new System.Windows.Forms.RadioButton();
            this.rdoRadio1On8 = new System.Windows.Forms.RadioButton();
            this.lblStatic20 = new System.Windows.Forms.Label();
            this.panel7 = new System.Windows.Forms.Panel();
            this.rdoRadio1Off6 = new System.Windows.Forms.RadioButton();
            this.rdoRadio1On6 = new System.Windows.Forms.RadioButton();
            this.lblStatic18 = new System.Windows.Forms.Label();
            this.panel8 = new System.Windows.Forms.Panel();
            this.rdoRadio1Off7 = new System.Windows.Forms.RadioButton();
            this.rdoRadio1On7 = new System.Windows.Forms.RadioButton();
            this.lblStatic19 = new System.Windows.Forms.Label();
            this.panel9 = new System.Windows.Forms.Panel();
            this.rdoRadio1Off5 = new System.Windows.Forms.RadioButton();
            this.rdoRadio1On5 = new System.Windows.Forms.RadioButton();
            this.lblStatic17 = new System.Windows.Forms.Label();
            this.panel1 = new System.Windows.Forms.Panel();
            this.rdoRadio1Off16 = new System.Windows.Forms.RadioButton();
            this.rdoRadio1On16 = new System.Windows.Forms.RadioButton();
            this.lblStatic28 = new System.Windows.Forms.Label();
            this.panel10 = new System.Windows.Forms.Panel();
            this.rdoRadio1Off12 = new System.Windows.Forms.RadioButton();
            this.rdoRadio1On12 = new System.Windows.Forms.RadioButton();
            this.lblStatic24 = new System.Windows.Forms.Label();
            this.panel11 = new System.Windows.Forms.Panel();
            this.rdoRadio1Off14 = new System.Windows.Forms.RadioButton();
            this.rdoRadio1On14 = new System.Windows.Forms.RadioButton();
            this.lblStatic26 = new System.Windows.Forms.Label();
            this.panel12 = new System.Windows.Forms.Panel();
            this.rdoRadio1Off10 = new System.Windows.Forms.RadioButton();
            this.rdoRadio1On10 = new System.Windows.Forms.RadioButton();
            this.lblStatic22 = new System.Windows.Forms.Label();
            this.panel13 = new System.Windows.Forms.Panel();
            this.rdoRadio1Off15 = new System.Windows.Forms.RadioButton();
            this.rdoRadio1On15 = new System.Windows.Forms.RadioButton();
            this.lblStatic27 = new System.Windows.Forms.Label();
            this.panel14 = new System.Windows.Forms.Panel();
            this.rdoRadio1Off11 = new System.Windows.Forms.RadioButton();
            this.rdoRadio1On11 = new System.Windows.Forms.RadioButton();
            this.lblStatic23 = new System.Windows.Forms.Label();
            this.panel15 = new System.Windows.Forms.Panel();
            this.rdoRadio1Off13 = new System.Windows.Forms.RadioButton();
            this.rdoRadio1On13 = new System.Windows.Forms.RadioButton();
            this.lblStatic25 = new System.Windows.Forms.Label();
            this.panel16 = new System.Windows.Forms.Panel();
            this.rdoRadio1Off9 = new System.Windows.Forms.RadioButton();
            this.rdoRadio1On9 = new System.Windows.Forms.RadioButton();
            this.label1 = new System.Windows.Forms.Label();
            this.grpStatic10 = new System.Windows.Forms.GroupBox();
            this.btnButtonSet18 = new System.Windows.Forms.Button();
            this.label2 = new System.Windows.Forms.Label();
            this.btnButtonSet21 = new System.Windows.Forms.Button();
            this.label3 = new System.Windows.Forms.Label();
            this.txtEditDcsetbuf0 = new System.Windows.Forms.TextBox();
            this.txtEditDcsetbuf1 = new System.Windows.Forms.TextBox();
            this.txtEditDcsetbuf10 = new System.Windows.Forms.TextBox();
            this.txtEditDcsetbuf11 = new System.Windows.Forms.TextBox();
            this.txtEditDcsetbuf12 = new System.Windows.Forms.TextBox();
            this.txtEditDcsetbuf13 = new System.Windows.Forms.TextBox();
            this.txtEditDcsetbuf14 = new System.Windows.Forms.TextBox();
            this.txtEditDcsetbuf15 = new System.Windows.Forms.TextBox();
            this.txtEditDcsetbuf16 = new System.Windows.Forms.TextBox();
            this.txtEditDcsetbuf17 = new System.Windows.Forms.TextBox();
            this.txtEditDcsetbuf18 = new System.Windows.Forms.TextBox();
            this.txtEditDcsetbuf19 = new System.Windows.Forms.TextBox();
            this.txtEditDcsetbuf2 = new System.Windows.Forms.TextBox();
            this.txtEditDcsetbuf20 = new System.Windows.Forms.TextBox();
            this.txtEditDcsetbuf21 = new System.Windows.Forms.TextBox();
            this.txtEditDcsetbuf22 = new System.Windows.Forms.TextBox();
            this.txtEditDcsetbuf23 = new System.Windows.Forms.TextBox();
            this.txtEditDcsetbuf24 = new System.Windows.Forms.TextBox();
            this.txtEditDcsetbuf25 = new System.Windows.Forms.TextBox();
            this.txtEditDcsetbuf26 = new System.Windows.Forms.TextBox();
            this.txtEditDcsetbuf27 = new System.Windows.Forms.TextBox();
            this.txtEditDcsetbuf28 = new System.Windows.Forms.TextBox();
            this.txtEditDcsetbuf29 = new System.Windows.Forms.TextBox();
            this.txtEditDcsetbuf3 = new System.Windows.Forms.TextBox();
            this.txtEditDcsetbuf30 = new System.Windows.Forms.TextBox();
            this.txtEditDcsetbuf31 = new System.Windows.Forms.TextBox();
            this.txtEditDcsetbuf4 = new System.Windows.Forms.TextBox();
            this.txtEditDcsetbuf5 = new System.Windows.Forms.TextBox();
            this.txtEditDcsetbuf6 = new System.Windows.Forms.TextBox();
            this.txtEditDcsetbuf7 = new System.Windows.Forms.TextBox();
            this.txtEditDcsetbuf8 = new System.Windows.Forms.TextBox();
            this.txtEditDcsetbuf9 = new System.Windows.Forms.TextBox();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.grpStatic8.SuspendLayout();
            this.panel2.SuspendLayout();
            this.panel3.SuspendLayout();
            this.panel4.SuspendLayout();
            this.panel5.SuspendLayout();
            this.panel6.SuspendLayout();
            this.panel7.SuspendLayout();
            this.panel8.SuspendLayout();
            this.panel9.SuspendLayout();
            this.panel1.SuspendLayout();
            this.panel10.SuspendLayout();
            this.panel11.SuspendLayout();
            this.panel12.SuspendLayout();
            this.panel13.SuspendLayout();
            this.panel14.SuspendLayout();
            this.panel15.SuspendLayout();
            this.panel16.SuspendLayout();
            this.grpStatic10.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.SuspendLayout();
            // 
            // lblStatic1
            // 
            this.lblStatic1.AutoSize = true;
            this.lblStatic1.Location = new System.Drawing.Point(42, 21);
            this.lblStatic1.Name = "lblStatic1";
            this.lblStatic1.Size = new System.Drawing.Size(70, 13);
            this.lblStatic1.TabIndex = 1;
            this.lblStatic1.Text = "Card number:";
            // 
            // cboComboCardNumber
            // 
            this.cboComboCardNumber.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboComboCardNumber.Location = new System.Drawing.Point(120, 18);
            this.cboComboCardNumber.Name = "cboComboCardNumber";
            this.cboComboCardNumber.Size = new System.Drawing.Size(78, 21);
            this.cboComboCardNumber.TabIndex = 2;
            this.cboComboCardNumber.SelectedIndexChanged += new System.EventHandler(this.cboComboCardNumber_SelectedIndexChanged);
            // 
            // lblStatic2
            // 
            this.lblStatic2.AutoSize = true;
            this.lblStatic2.Location = new System.Drawing.Point(66, 50);
            this.lblStatic2.Name = "lblStatic2";
            this.lblStatic2.Size = new System.Drawing.Size(46, 13);
            this.lblStatic2.TabIndex = 3;
            this.lblStatic2.Text = "Card ID:";
            // 
            // txtEditId
            // 
            this.txtEditId.Enabled = false;
            this.txtEditId.Location = new System.Drawing.Point(120, 45);
            this.txtEditId.Name = "txtEditId";
            this.txtEditId.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditId.Size = new System.Drawing.Size(78, 20);
            this.txtEditId.TabIndex = 4;
            // 
            // txtEditDcgetbuf0
            // 
            this.txtEditDcgetbuf0.Location = new System.Drawing.Point(102, 189);
            this.txtEditDcgetbuf0.Name = "txtEditDcgetbuf0";
            this.txtEditDcgetbuf0.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditDcgetbuf0.Size = new System.Drawing.Size(315, 20);
            this.txtEditDcgetbuf0.TabIndex = 5;
            // 
            // lblStatic3
            // 
            this.lblStatic3.AutoSize = true;
            this.lblStatic3.Location = new System.Drawing.Point(18, 189);
            this.lblStatic3.Name = "lblStatic3";
            this.lblStatic3.Size = new System.Drawing.Size(60, 13);
            this.lblStatic3.TabIndex = 6;
            this.lblStatic3.Text = "getbuf(hex)";
            // 
            // lblStatic4
            // 
            this.lblStatic4.AutoSize = true;
            this.lblStatic4.Location = new System.Drawing.Point(216, 18);
            this.lblStatic4.Name = "lblStatic4";
            this.lblStatic4.Size = new System.Drawing.Size(49, 13);
            this.lblStatic4.TabIndex = 7;
            this.lblStatic4.Text = "ERROR:";
            // 
            // txtEditError
            // 
            this.txtEditError.Enabled = false;
            this.txtEditError.Location = new System.Drawing.Point(270, 13);
            this.txtEditError.Name = "txtEditError";
            this.txtEditError.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditError.Size = new System.Drawing.Size(78, 20);
            this.txtEditError.TabIndex = 8;
            // 
            // lblStatic5
            // 
            this.lblStatic5.AutoSize = true;
            this.lblStatic5.Location = new System.Drawing.Point(212, 49);
            this.lblStatic5.Name = "lblStatic5";
            this.lblStatic5.Size = new System.Drawing.Size(59, 13);
            this.lblStatic5.TabIndex = 9;
            this.lblStatic5.Text = "EEVersion:";
            // 
            // txtEditId14
            // 
            this.txtEditId14.Enabled = false;
            this.txtEditId14.Location = new System.Drawing.Point(270, 45);
            this.txtEditId14.Name = "txtEditId14";
            this.txtEditId14.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditId14.Size = new System.Drawing.Size(78, 20);
            this.txtEditId14.TabIndex = 10;
            // 
            // lblStatic6
            // 
            this.lblStatic6.AutoSize = true;
            this.lblStatic6.Location = new System.Drawing.Point(365, 48);
            this.lblStatic6.Name = "lblStatic6";
            this.lblStatic6.Size = new System.Drawing.Size(67, 13);
            this.lblStatic6.TabIndex = 11;
            this.lblStatic6.Text = "EEStandard:";
            // 
            // txtEditId15
            // 
            this.txtEditId15.Enabled = false;
            this.txtEditId15.Location = new System.Drawing.Point(432, 45);
            this.txtEditId15.Name = "txtEditId15";
            this.txtEditId15.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditId15.Size = new System.Drawing.Size(78, 20);
            this.txtEditId15.TabIndex = 12;
            // 
            // lblStatic7
            // 
            this.lblStatic7.AutoSize = true;
            this.lblStatic7.Location = new System.Drawing.Point(528, 48);
            this.lblStatic7.Name = "lblStatic7";
            this.lblStatic7.Size = new System.Drawing.Size(43, 13);
            this.lblStatic7.TabIndex = 13;
            this.lblStatic7.Text = "EEPort:";
            // 
            // txtEditId16
            // 
            this.txtEditId16.Enabled = false;
            this.txtEditId16.Location = new System.Drawing.Point(582, 43);
            this.txtEditId16.Name = "txtEditId16";
            this.txtEditId16.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditId16.Size = new System.Drawing.Size(78, 20);
            this.txtEditId16.TabIndex = 14;
            // 
            // btnButtonSet4
            // 
            this.btnButtonSet4.Location = new System.Drawing.Point(357, 13);
            this.btnButtonSet4.Name = "btnButtonSet4";
            this.btnButtonSet4.Size = new System.Drawing.Size(75, 24);
            this.btnButtonSet4.TabIndex = 15;
            this.btnButtonSet4.Text = "Clear ERROR";
            this.btnButtonSet4.Click += new System.EventHandler(this.btnButtonSet4_Click);
            // 
            // grpStatic8
            // 
            this.grpStatic8.Controls.Add(this.btnButtonSet4);
            this.grpStatic8.Controls.Add(this.cboComboCardNumber);
            this.grpStatic8.Controls.Add(this.lblStatic1);
            this.grpStatic8.Controls.Add(this.lblStatic10);
            this.grpStatic8.Controls.Add(this.lblStatic11);
            this.grpStatic8.Controls.Add(this.lblStatic2);
            this.grpStatic8.Controls.Add(this.lblStatic4);
            this.grpStatic8.Controls.Add(this.lblStatic5);
            this.grpStatic8.Controls.Add(this.lblStatic6);
            this.grpStatic8.Controls.Add(this.lblStatic7);
            this.grpStatic8.Controls.Add(this.lblStatic9);
            this.grpStatic8.Controls.Add(this.txtEditError);
            this.grpStatic8.Controls.Add(this.txtEditId);
            this.grpStatic8.Controls.Add(this.txtEditId14);
            this.grpStatic8.Controls.Add(this.txtEditId15);
            this.grpStatic8.Controls.Add(this.txtEditId16);
            this.grpStatic8.Controls.Add(this.txtEditId18);
            this.grpStatic8.Controls.Add(this.txtEditId19);
            this.grpStatic8.Controls.Add(this.txtEditId20);
            this.grpStatic8.Location = new System.Drawing.Point(22, 11);
            this.grpStatic8.Name = "grpStatic8";
            this.grpStatic8.Size = new System.Drawing.Size(1017, 76);
            this.grpStatic8.TabIndex = 16;
            this.grpStatic8.TabStop = false;
            this.grpStatic8.Text = "Static";
            // 
            // lblStatic10
            // 
            this.lblStatic10.AutoSize = true;
            this.lblStatic10.Location = new System.Drawing.Point(842, 16);
            this.lblStatic10.Name = "lblStatic10";
            this.lblStatic10.Size = new System.Drawing.Size(79, 13);
            this.lblStatic10.TabIndex = 20;
            this.lblStatic10.Text = "CPLDVersion2:";
            // 
            // lblStatic11
            // 
            this.lblStatic11.AutoSize = true;
            this.lblStatic11.Location = new System.Drawing.Point(678, 43);
            this.lblStatic11.Name = "lblStatic11";
            this.lblStatic11.Size = new System.Drawing.Size(69, 13);
            this.lblStatic11.TabIndex = 21;
            this.lblStatic11.Text = "MCUVersion:";
            // 
            // lblStatic9
            // 
            this.lblStatic9.AutoSize = true;
            this.lblStatic9.Location = new System.Drawing.Point(670, 17);
            this.lblStatic9.Name = "lblStatic9";
            this.lblStatic9.Size = new System.Drawing.Size(79, 13);
            this.lblStatic9.TabIndex = 17;
            this.lblStatic9.Text = "CPLDVersion1:";
            // 
            // txtEditId18
            // 
            this.txtEditId18.Enabled = false;
            this.txtEditId18.Location = new System.Drawing.Point(750, 13);
            this.txtEditId18.Name = "txtEditId18";
            this.txtEditId18.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditId18.Size = new System.Drawing.Size(78, 20);
            this.txtEditId18.TabIndex = 18;
            // 
            // txtEditId19
            // 
            this.txtEditId19.Enabled = false;
            this.txtEditId19.Location = new System.Drawing.Point(922, 13);
            this.txtEditId19.Name = "txtEditId19";
            this.txtEditId19.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditId19.Size = new System.Drawing.Size(78, 20);
            this.txtEditId19.TabIndex = 19;
            // 
            // txtEditId20
            // 
            this.txtEditId20.Enabled = false;
            this.txtEditId20.Location = new System.Drawing.Point(750, 39);
            this.txtEditId20.Name = "txtEditId20";
            this.txtEditId20.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditId20.Size = new System.Drawing.Size(78, 20);
            this.txtEditId20.TabIndex = 22;
            // 
            // btnButtonSet29
            // 
            this.btnButtonSet29.Location = new System.Drawing.Point(11, 17);
            this.btnButtonSet29.Name = "btnButtonSet29";
            this.btnButtonSet29.Size = new System.Drawing.Size(147, 24);
            this.btnButtonSet29.TabIndex = 25;
            this.btnButtonSet29.Text = "EncryptReadSegment";
            this.btnButtonSet29.Click += new System.EventHandler(this.btnButtonSet29_Click);
            // 
            // btnButtonSet30
            // 
            this.btnButtonSet30.Location = new System.Drawing.Point(11, 183);
            this.btnButtonSet30.Name = "btnButtonSet30";
            this.btnButtonSet30.Size = new System.Drawing.Size(160, 24);
            this.btnButtonSet30.TabIndex = 26;
            this.btnButtonSet30.Text = "EncryptAuthWritePageEnc";
            this.btnButtonSet30.Click += new System.EventHandler(this.btnButtonSet30_Click);
            // 
            // btnButtonSet31
            // 
            this.btnButtonSet31.Location = new System.Drawing.Point(12, 19);
            this.btnButtonSet31.Name = "btnButtonSet31";
            this.btnButtonSet31.Size = new System.Drawing.Size(146, 24);
            this.btnButtonSet31.TabIndex = 29;
            this.btnButtonSet31.Text = "EncryptComputeEnc";
            this.btnButtonSet31.Click += new System.EventHandler(this.btnButtonSet31_Click);
            // 
            // btnButtonSet32
            // 
            this.btnButtonSet32.Location = new System.Drawing.Point(426, 33);
            this.btnButtonSet32.Name = "btnButtonSet32";
            this.btnButtonSet32.Size = new System.Drawing.Size(122, 24);
            this.btnButtonSet32.TabIndex = 30;
            this.btnButtonSet32.Text = "SecretStatus";
            this.btnButtonSet32.Click += new System.EventHandler(this.btnButtonSet32_Click);
            // 
            // txtEditDcgetbuf5
            // 
            this.txtEditDcgetbuf5.Location = new System.Drawing.Point(12, 56);
            this.txtEditDcgetbuf5.Multiline = true;
            this.txtEditDcgetbuf5.Name = "txtEditDcgetbuf5";
            this.txtEditDcgetbuf5.Size = new System.Drawing.Size(394, 121);
            this.txtEditDcgetbuf5.TabIndex = 31;
            // 
            // txtEditDcgetbuf6
            // 
            this.txtEditDcgetbuf6.Location = new System.Drawing.Point(12, 56);
            this.txtEditDcgetbuf6.Multiline = true;
            this.txtEditDcgetbuf6.Name = "txtEditDcgetbuf6";
            this.txtEditDcgetbuf6.Size = new System.Drawing.Size(394, 81);
            this.txtEditDcgetbuf6.TabIndex = 32;
            // 
            // btnButtonSet33
            // 
            this.btnButtonSet33.Location = new System.Drawing.Point(180, 17);
            this.btnButtonSet33.Name = "btnButtonSet33";
            this.btnButtonSet33.Size = new System.Drawing.Size(147, 24);
            this.btnButtonSet33.TabIndex = 81;
            this.btnButtonSet33.Text = "Check ON/OFF";
            this.btnButtonSet33.Click += new System.EventHandler(this.btnButtonSet33_Click);
            // 
            // panel2
            // 
            this.panel2.Controls.Add(this.rdoRadio1On1);
            this.panel2.Controls.Add(this.rdoRadio1Off1);
            this.panel2.Controls.Add(this.lblStatic13);
            this.panel2.Location = new System.Drawing.Point(6, 19);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(193, 17);
            this.panel2.TabIndex = 84;
            // 
            // rdoRadio1On1
            // 
            this.rdoRadio1On1.Location = new System.Drawing.Point(84, 0);
            this.rdoRadio1On1.Name = "rdoRadio1On1";
            this.rdoRadio1On1.Size = new System.Drawing.Size(45, 17);
            this.rdoRadio1On1.TabIndex = 87;
            this.rdoRadio1On1.Text = "ON";
            // 
            // rdoRadio1Off1
            // 
            this.rdoRadio1Off1.Location = new System.Drawing.Point(128, 0);
            this.rdoRadio1Off1.Name = "rdoRadio1Off1";
            this.rdoRadio1Off1.Size = new System.Drawing.Size(50, 17);
            this.rdoRadio1Off1.TabIndex = 88;
            this.rdoRadio1Off1.Text = "OFF";
            // 
            // lblStatic13
            // 
            this.lblStatic13.AutoSize = true;
            this.lblStatic13.Location = new System.Drawing.Point(14, 1);
            this.lblStatic13.Name = "lblStatic13";
            this.lblStatic13.Size = new System.Drawing.Size(54, 13);
            this.lblStatic13.TabIndex = 89;
            this.lblStatic13.Text = "Function1";
            // 
            // panel3
            // 
            this.panel3.Controls.Add(this.rdoRadio1Off2);
            this.panel3.Controls.Add(this.rdoRadio1On2);
            this.panel3.Controls.Add(this.lblStatic14);
            this.panel3.Location = new System.Drawing.Point(6, 37);
            this.panel3.Name = "panel3";
            this.panel3.Size = new System.Drawing.Size(193, 17);
            this.panel3.TabIndex = 85;
            // 
            // rdoRadio1Off2
            // 
            this.rdoRadio1Off2.Location = new System.Drawing.Point(128, 0);
            this.rdoRadio1Off2.Name = "rdoRadio1Off2";
            this.rdoRadio1Off2.Size = new System.Drawing.Size(50, 17);
            this.rdoRadio1Off2.TabIndex = 43;
            this.rdoRadio1Off2.Text = "OFF";
            // 
            // rdoRadio1On2
            // 
            this.rdoRadio1On2.Location = new System.Drawing.Point(84, 0);
            this.rdoRadio1On2.Name = "rdoRadio1On2";
            this.rdoRadio1On2.Size = new System.Drawing.Size(45, 17);
            this.rdoRadio1On2.TabIndex = 42;
            this.rdoRadio1On2.Text = "ON";
            // 
            // lblStatic14
            // 
            this.lblStatic14.AutoSize = true;
            this.lblStatic14.Location = new System.Drawing.Point(14, 3);
            this.lblStatic14.Name = "lblStatic14";
            this.lblStatic14.Size = new System.Drawing.Size(54, 13);
            this.lblStatic14.TabIndex = 44;
            this.lblStatic14.Text = "Function2";
            // 
            // panel4
            // 
            this.panel4.Controls.Add(this.rdoRadio1Off4);
            this.panel4.Controls.Add(this.rdoRadio1On4);
            this.panel4.Controls.Add(this.lblStatic16);
            this.panel4.Location = new System.Drawing.Point(6, 74);
            this.panel4.Name = "panel4";
            this.panel4.Size = new System.Drawing.Size(193, 17);
            this.panel4.TabIndex = 87;
            // 
            // rdoRadio1Off4
            // 
            this.rdoRadio1Off4.Location = new System.Drawing.Point(128, 0);
            this.rdoRadio1Off4.Name = "rdoRadio1Off4";
            this.rdoRadio1Off4.Size = new System.Drawing.Size(50, 17);
            this.rdoRadio1Off4.TabIndex = 46;
            this.rdoRadio1Off4.Text = "OFF";
            // 
            // rdoRadio1On4
            // 
            this.rdoRadio1On4.Location = new System.Drawing.Point(84, 0);
            this.rdoRadio1On4.Name = "rdoRadio1On4";
            this.rdoRadio1On4.Size = new System.Drawing.Size(45, 17);
            this.rdoRadio1On4.TabIndex = 45;
            this.rdoRadio1On4.Text = "ON";
            // 
            // lblStatic16
            // 
            this.lblStatic16.AutoSize = true;
            this.lblStatic16.Location = new System.Drawing.Point(14, 1);
            this.lblStatic16.Name = "lblStatic16";
            this.lblStatic16.Size = new System.Drawing.Size(54, 13);
            this.lblStatic16.TabIndex = 47;
            this.lblStatic16.Text = "Function4";
            // 
            // panel5
            // 
            this.panel5.Controls.Add(this.rdoRadio1Off3);
            this.panel5.Controls.Add(this.rdoRadio1On3);
            this.panel5.Controls.Add(this.lblStatic15);
            this.panel5.Location = new System.Drawing.Point(6, 56);
            this.panel5.Name = "panel5";
            this.panel5.Size = new System.Drawing.Size(193, 17);
            this.panel5.TabIndex = 86;
            // 
            // rdoRadio1Off3
            // 
            this.rdoRadio1Off3.Location = new System.Drawing.Point(128, 0);
            this.rdoRadio1Off3.Name = "rdoRadio1Off3";
            this.rdoRadio1Off3.Size = new System.Drawing.Size(50, 17);
            this.rdoRadio1Off3.TabIndex = 43;
            this.rdoRadio1Off3.Text = "OFF";
            // 
            // rdoRadio1On3
            // 
            this.rdoRadio1On3.Location = new System.Drawing.Point(84, 0);
            this.rdoRadio1On3.Name = "rdoRadio1On3";
            this.rdoRadio1On3.Size = new System.Drawing.Size(45, 17);
            this.rdoRadio1On3.TabIndex = 42;
            this.rdoRadio1On3.Text = "ON";
            // 
            // lblStatic15
            // 
            this.lblStatic15.AutoSize = true;
            this.lblStatic15.Location = new System.Drawing.Point(14, 1);
            this.lblStatic15.Name = "lblStatic15";
            this.lblStatic15.Size = new System.Drawing.Size(54, 13);
            this.lblStatic15.TabIndex = 44;
            this.lblStatic15.Text = "Function3";
            // 
            // panel6
            // 
            this.panel6.Controls.Add(this.rdoRadio1Off8);
            this.panel6.Controls.Add(this.rdoRadio1On8);
            this.panel6.Controls.Add(this.lblStatic20);
            this.panel6.Location = new System.Drawing.Point(6, 148);
            this.panel6.Name = "panel6";
            this.panel6.Size = new System.Drawing.Size(193, 17);
            this.panel6.TabIndex = 91;
            // 
            // rdoRadio1Off8
            // 
            this.rdoRadio1Off8.Location = new System.Drawing.Point(128, 0);
            this.rdoRadio1Off8.Name = "rdoRadio1Off8";
            this.rdoRadio1Off8.Size = new System.Drawing.Size(50, 17);
            this.rdoRadio1Off8.TabIndex = 58;
            this.rdoRadio1Off8.Text = "OFF";
            // 
            // rdoRadio1On8
            // 
            this.rdoRadio1On8.Location = new System.Drawing.Point(84, 0);
            this.rdoRadio1On8.Name = "rdoRadio1On8";
            this.rdoRadio1On8.Size = new System.Drawing.Size(45, 17);
            this.rdoRadio1On8.TabIndex = 57;
            this.rdoRadio1On8.Text = "ON";
            // 
            // lblStatic20
            // 
            this.lblStatic20.AutoSize = true;
            this.lblStatic20.Location = new System.Drawing.Point(14, 1);
            this.lblStatic20.Name = "lblStatic20";
            this.lblStatic20.Size = new System.Drawing.Size(54, 13);
            this.lblStatic20.TabIndex = 59;
            this.lblStatic20.Text = "Function8";
            // 
            // panel7
            // 
            this.panel7.Controls.Add(this.rdoRadio1Off6);
            this.panel7.Controls.Add(this.rdoRadio1On6);
            this.panel7.Controls.Add(this.lblStatic18);
            this.panel7.Location = new System.Drawing.Point(6, 111);
            this.panel7.Name = "panel7";
            this.panel7.Size = new System.Drawing.Size(193, 17);
            this.panel7.TabIndex = 89;
            // 
            // rdoRadio1Off6
            // 
            this.rdoRadio1Off6.Location = new System.Drawing.Point(128, 0);
            this.rdoRadio1Off6.Name = "rdoRadio1Off6";
            this.rdoRadio1Off6.Size = new System.Drawing.Size(50, 17);
            this.rdoRadio1Off6.TabIndex = 52;
            this.rdoRadio1Off6.Text = "OFF";
            // 
            // rdoRadio1On6
            // 
            this.rdoRadio1On6.Location = new System.Drawing.Point(84, 0);
            this.rdoRadio1On6.Name = "rdoRadio1On6";
            this.rdoRadio1On6.Size = new System.Drawing.Size(45, 17);
            this.rdoRadio1On6.TabIndex = 51;
            this.rdoRadio1On6.Text = "ON";
            // 
            // lblStatic18
            // 
            this.lblStatic18.AutoSize = true;
            this.lblStatic18.Location = new System.Drawing.Point(14, 1);
            this.lblStatic18.Name = "lblStatic18";
            this.lblStatic18.Size = new System.Drawing.Size(54, 13);
            this.lblStatic18.TabIndex = 53;
            this.lblStatic18.Text = "Function6";
            // 
            // panel8
            // 
            this.panel8.Controls.Add(this.rdoRadio1Off7);
            this.panel8.Controls.Add(this.rdoRadio1On7);
            this.panel8.Controls.Add(this.lblStatic19);
            this.panel8.Location = new System.Drawing.Point(6, 130);
            this.panel8.Name = "panel8";
            this.panel8.Size = new System.Drawing.Size(193, 17);
            this.panel8.TabIndex = 90;
            // 
            // rdoRadio1Off7
            // 
            this.rdoRadio1Off7.Location = new System.Drawing.Point(128, 0);
            this.rdoRadio1Off7.Name = "rdoRadio1Off7";
            this.rdoRadio1Off7.Size = new System.Drawing.Size(50, 17);
            this.rdoRadio1Off7.TabIndex = 55;
            this.rdoRadio1Off7.Text = "OFF";
            // 
            // rdoRadio1On7
            // 
            this.rdoRadio1On7.Location = new System.Drawing.Point(84, 0);
            this.rdoRadio1On7.Name = "rdoRadio1On7";
            this.rdoRadio1On7.Size = new System.Drawing.Size(45, 17);
            this.rdoRadio1On7.TabIndex = 54;
            this.rdoRadio1On7.Text = "ON";
            // 
            // lblStatic19
            // 
            this.lblStatic19.AutoSize = true;
            this.lblStatic19.Location = new System.Drawing.Point(14, 3);
            this.lblStatic19.Name = "lblStatic19";
            this.lblStatic19.Size = new System.Drawing.Size(54, 13);
            this.lblStatic19.TabIndex = 56;
            this.lblStatic19.Text = "Function7";
            // 
            // panel9
            // 
            this.panel9.Controls.Add(this.rdoRadio1Off5);
            this.panel9.Controls.Add(this.rdoRadio1On5);
            this.panel9.Controls.Add(this.lblStatic17);
            this.panel9.Location = new System.Drawing.Point(6, 93);
            this.panel9.Name = "panel9";
            this.panel9.Size = new System.Drawing.Size(193, 17);
            this.panel9.TabIndex = 88;
            // 
            // rdoRadio1Off5
            // 
            this.rdoRadio1Off5.Location = new System.Drawing.Point(128, 0);
            this.rdoRadio1Off5.Name = "rdoRadio1Off5";
            this.rdoRadio1Off5.Size = new System.Drawing.Size(50, 17);
            this.rdoRadio1Off5.TabIndex = 49;
            this.rdoRadio1Off5.Text = "OFF";
            // 
            // rdoRadio1On5
            // 
            this.rdoRadio1On5.Location = new System.Drawing.Point(84, 0);
            this.rdoRadio1On5.Name = "rdoRadio1On5";
            this.rdoRadio1On5.Size = new System.Drawing.Size(45, 17);
            this.rdoRadio1On5.TabIndex = 48;
            this.rdoRadio1On5.Text = "ON";
            // 
            // lblStatic17
            // 
            this.lblStatic17.AutoSize = true;
            this.lblStatic17.Location = new System.Drawing.Point(14, 1);
            this.lblStatic17.Name = "lblStatic17";
            this.lblStatic17.Size = new System.Drawing.Size(54, 13);
            this.lblStatic17.TabIndex = 50;
            this.lblStatic17.Text = "Function5";
            // 
            // panel1
            // 
            this.panel1.Controls.Add(this.rdoRadio1Off16);
            this.panel1.Controls.Add(this.rdoRadio1On16);
            this.panel1.Controls.Add(this.lblStatic28);
            this.panel1.Location = new System.Drawing.Point(205, 148);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(193, 17);
            this.panel1.TabIndex = 99;
            // 
            // rdoRadio1Off16
            // 
            this.rdoRadio1Off16.Location = new System.Drawing.Point(128, 0);
            this.rdoRadio1Off16.Name = "rdoRadio1Off16";
            this.rdoRadio1Off16.Size = new System.Drawing.Size(50, 17);
            this.rdoRadio1Off16.TabIndex = 82;
            this.rdoRadio1Off16.Text = "OFF";
            // 
            // rdoRadio1On16
            // 
            this.rdoRadio1On16.Location = new System.Drawing.Point(82, 0);
            this.rdoRadio1On16.Name = "rdoRadio1On16";
            this.rdoRadio1On16.Size = new System.Drawing.Size(45, 17);
            this.rdoRadio1On16.TabIndex = 81;
            this.rdoRadio1On16.Text = "ON";
            // 
            // lblStatic28
            // 
            this.lblStatic28.AutoSize = true;
            this.lblStatic28.Location = new System.Drawing.Point(14, 1);
            this.lblStatic28.Name = "lblStatic28";
            this.lblStatic28.Size = new System.Drawing.Size(60, 13);
            this.lblStatic28.TabIndex = 83;
            this.lblStatic28.Text = "Function16";
            // 
            // panel10
            // 
            this.panel10.Controls.Add(this.rdoRadio1Off12);
            this.panel10.Controls.Add(this.rdoRadio1On12);
            this.panel10.Controls.Add(this.lblStatic24);
            this.panel10.Location = new System.Drawing.Point(205, 74);
            this.panel10.Name = "panel10";
            this.panel10.Size = new System.Drawing.Size(193, 17);
            this.panel10.TabIndex = 95;
            // 
            // rdoRadio1Off12
            // 
            this.rdoRadio1Off12.Location = new System.Drawing.Point(128, 0);
            this.rdoRadio1Off12.Name = "rdoRadio1Off12";
            this.rdoRadio1Off12.Size = new System.Drawing.Size(50, 17);
            this.rdoRadio1Off12.TabIndex = 70;
            this.rdoRadio1Off12.Text = "OFF";
            // 
            // rdoRadio1On12
            // 
            this.rdoRadio1On12.Location = new System.Drawing.Point(82, 0);
            this.rdoRadio1On12.Name = "rdoRadio1On12";
            this.rdoRadio1On12.Size = new System.Drawing.Size(45, 17);
            this.rdoRadio1On12.TabIndex = 69;
            this.rdoRadio1On12.Text = "ON";
            // 
            // lblStatic24
            // 
            this.lblStatic24.AutoSize = true;
            this.lblStatic24.Location = new System.Drawing.Point(14, 1);
            this.lblStatic24.Name = "lblStatic24";
            this.lblStatic24.Size = new System.Drawing.Size(60, 13);
            this.lblStatic24.TabIndex = 71;
            this.lblStatic24.Text = "Function12";
            // 
            // panel11
            // 
            this.panel11.Controls.Add(this.rdoRadio1Off14);
            this.panel11.Controls.Add(this.rdoRadio1On14);
            this.panel11.Controls.Add(this.lblStatic26);
            this.panel11.Location = new System.Drawing.Point(205, 111);
            this.panel11.Name = "panel11";
            this.panel11.Size = new System.Drawing.Size(193, 17);
            this.panel11.TabIndex = 97;
            // 
            // rdoRadio1Off14
            // 
            this.rdoRadio1Off14.Location = new System.Drawing.Point(128, 0);
            this.rdoRadio1Off14.Name = "rdoRadio1Off14";
            this.rdoRadio1Off14.Size = new System.Drawing.Size(50, 17);
            this.rdoRadio1Off14.TabIndex = 76;
            this.rdoRadio1Off14.Text = "OFF";
            // 
            // rdoRadio1On14
            // 
            this.rdoRadio1On14.Location = new System.Drawing.Point(82, 0);
            this.rdoRadio1On14.Name = "rdoRadio1On14";
            this.rdoRadio1On14.Size = new System.Drawing.Size(45, 17);
            this.rdoRadio1On14.TabIndex = 75;
            this.rdoRadio1On14.Text = "ON";
            // 
            // lblStatic26
            // 
            this.lblStatic26.AutoSize = true;
            this.lblStatic26.Location = new System.Drawing.Point(14, 0);
            this.lblStatic26.Name = "lblStatic26";
            this.lblStatic26.Size = new System.Drawing.Size(60, 13);
            this.lblStatic26.TabIndex = 77;
            this.lblStatic26.Text = "Function14";
            // 
            // panel12
            // 
            this.panel12.Controls.Add(this.rdoRadio1Off10);
            this.panel12.Controls.Add(this.rdoRadio1On10);
            this.panel12.Controls.Add(this.lblStatic22);
            this.panel12.Location = new System.Drawing.Point(205, 37);
            this.panel12.Name = "panel12";
            this.panel12.Size = new System.Drawing.Size(193, 17);
            this.panel12.TabIndex = 93;
            // 
            // rdoRadio1Off10
            // 
            this.rdoRadio1Off10.Location = new System.Drawing.Point(128, 0);
            this.rdoRadio1Off10.Name = "rdoRadio1Off10";
            this.rdoRadio1Off10.Size = new System.Drawing.Size(50, 17);
            this.rdoRadio1Off10.TabIndex = 64;
            this.rdoRadio1Off10.Text = "OFF";
            // 
            // rdoRadio1On10
            // 
            this.rdoRadio1On10.Location = new System.Drawing.Point(82, 0);
            this.rdoRadio1On10.Name = "rdoRadio1On10";
            this.rdoRadio1On10.Size = new System.Drawing.Size(45, 17);
            this.rdoRadio1On10.TabIndex = 63;
            this.rdoRadio1On10.Text = "ON";
            // 
            // lblStatic22
            // 
            this.lblStatic22.AutoSize = true;
            this.lblStatic22.Location = new System.Drawing.Point(14, 3);
            this.lblStatic22.Name = "lblStatic22";
            this.lblStatic22.Size = new System.Drawing.Size(60, 13);
            this.lblStatic22.TabIndex = 65;
            this.lblStatic22.Text = "Function10";
            // 
            // panel13
            // 
            this.panel13.Controls.Add(this.rdoRadio1Off15);
            this.panel13.Controls.Add(this.rdoRadio1On15);
            this.panel13.Controls.Add(this.lblStatic27);
            this.panel13.Location = new System.Drawing.Point(205, 130);
            this.panel13.Name = "panel13";
            this.panel13.Size = new System.Drawing.Size(193, 17);
            this.panel13.TabIndex = 98;
            // 
            // rdoRadio1Off15
            // 
            this.rdoRadio1Off15.Location = new System.Drawing.Point(128, 0);
            this.rdoRadio1Off15.Name = "rdoRadio1Off15";
            this.rdoRadio1Off15.Size = new System.Drawing.Size(50, 17);
            this.rdoRadio1Off15.TabIndex = 79;
            this.rdoRadio1Off15.Text = "OFF";
            // 
            // rdoRadio1On15
            // 
            this.rdoRadio1On15.Location = new System.Drawing.Point(82, 0);
            this.rdoRadio1On15.Name = "rdoRadio1On15";
            this.rdoRadio1On15.Size = new System.Drawing.Size(45, 17);
            this.rdoRadio1On15.TabIndex = 78;
            this.rdoRadio1On15.Text = "ON";
            // 
            // lblStatic27
            // 
            this.lblStatic27.AutoSize = true;
            this.lblStatic27.Location = new System.Drawing.Point(14, 3);
            this.lblStatic27.Name = "lblStatic27";
            this.lblStatic27.Size = new System.Drawing.Size(60, 13);
            this.lblStatic27.TabIndex = 80;
            this.lblStatic27.Text = "Function15";
            // 
            // panel14
            // 
            this.panel14.Controls.Add(this.rdoRadio1Off11);
            this.panel14.Controls.Add(this.rdoRadio1On11);
            this.panel14.Controls.Add(this.lblStatic23);
            this.panel14.Location = new System.Drawing.Point(205, 56);
            this.panel14.Name = "panel14";
            this.panel14.Size = new System.Drawing.Size(193, 17);
            this.panel14.TabIndex = 94;
            // 
            // rdoRadio1Off11
            // 
            this.rdoRadio1Off11.Location = new System.Drawing.Point(128, 0);
            this.rdoRadio1Off11.Name = "rdoRadio1Off11";
            this.rdoRadio1Off11.Size = new System.Drawing.Size(50, 17);
            this.rdoRadio1Off11.TabIndex = 67;
            this.rdoRadio1Off11.Text = "OFF";
            // 
            // rdoRadio1On11
            // 
            this.rdoRadio1On11.Location = new System.Drawing.Point(82, 0);
            this.rdoRadio1On11.Name = "rdoRadio1On11";
            this.rdoRadio1On11.Size = new System.Drawing.Size(45, 17);
            this.rdoRadio1On11.TabIndex = 66;
            this.rdoRadio1On11.Text = "ON";
            // 
            // lblStatic23
            // 
            this.lblStatic23.AutoSize = true;
            this.lblStatic23.Location = new System.Drawing.Point(14, 1);
            this.lblStatic23.Name = "lblStatic23";
            this.lblStatic23.Size = new System.Drawing.Size(60, 13);
            this.lblStatic23.TabIndex = 68;
            this.lblStatic23.Text = "Function11";
            // 
            // panel15
            // 
            this.panel15.Controls.Add(this.rdoRadio1Off13);
            this.panel15.Controls.Add(this.rdoRadio1On13);
            this.panel15.Controls.Add(this.lblStatic25);
            this.panel15.Location = new System.Drawing.Point(205, 93);
            this.panel15.Name = "panel15";
            this.panel15.Size = new System.Drawing.Size(193, 17);
            this.panel15.TabIndex = 96;
            // 
            // rdoRadio1Off13
            // 
            this.rdoRadio1Off13.Location = new System.Drawing.Point(128, 0);
            this.rdoRadio1Off13.Name = "rdoRadio1Off13";
            this.rdoRadio1Off13.Size = new System.Drawing.Size(50, 17);
            this.rdoRadio1Off13.TabIndex = 73;
            this.rdoRadio1Off13.Text = "OFF";
            // 
            // rdoRadio1On13
            // 
            this.rdoRadio1On13.Location = new System.Drawing.Point(82, 0);
            this.rdoRadio1On13.Name = "rdoRadio1On13";
            this.rdoRadio1On13.Size = new System.Drawing.Size(45, 17);
            this.rdoRadio1On13.TabIndex = 72;
            this.rdoRadio1On13.Text = "ON";
            // 
            // lblStatic25
            // 
            this.lblStatic25.AutoSize = true;
            this.lblStatic25.Location = new System.Drawing.Point(14, 3);
            this.lblStatic25.Name = "lblStatic25";
            this.lblStatic25.Size = new System.Drawing.Size(60, 13);
            this.lblStatic25.TabIndex = 74;
            this.lblStatic25.Text = "Function13";
            // 
            // panel16
            // 
            this.panel16.Controls.Add(this.rdoRadio1Off9);
            this.panel16.Controls.Add(this.rdoRadio1On9);
            this.panel16.Controls.Add(this.label1);
            this.panel16.Location = new System.Drawing.Point(205, 19);
            this.panel16.Name = "panel16";
            this.panel16.Size = new System.Drawing.Size(193, 17);
            this.panel16.TabIndex = 92;
            // 
            // rdoRadio1Off9
            // 
            this.rdoRadio1Off9.Location = new System.Drawing.Point(128, 0);
            this.rdoRadio1Off9.Name = "rdoRadio1Off9";
            this.rdoRadio1Off9.Size = new System.Drawing.Size(50, 17);
            this.rdoRadio1Off9.TabIndex = 67;
            this.rdoRadio1Off9.Text = "OFF";
            // 
            // rdoRadio1On9
            // 
            this.rdoRadio1On9.Location = new System.Drawing.Point(82, 0);
            this.rdoRadio1On9.Name = "rdoRadio1On9";
            this.rdoRadio1On9.Size = new System.Drawing.Size(45, 17);
            this.rdoRadio1On9.TabIndex = 66;
            this.rdoRadio1On9.Text = "ON";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(14, 3);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(54, 13);
            this.label1.TabIndex = 68;
            this.label1.Text = "Function9";
            // 
            // grpStatic10
            // 
            this.grpStatic10.Controls.Add(this.btnButtonSet18);
            this.grpStatic10.Controls.Add(this.label2);
            this.grpStatic10.Controls.Add(this.btnButtonSet21);
            this.grpStatic10.Controls.Add(this.label3);
            this.grpStatic10.Controls.Add(this.txtEditDcsetbuf0);
            this.grpStatic10.Controls.Add(this.btnButtonSet32);
            this.grpStatic10.Controls.Add(this.txtEditDcsetbuf1);
            this.grpStatic10.Controls.Add(this.txtEditDcsetbuf10);
            this.grpStatic10.Controls.Add(this.txtEditDcsetbuf11);
            this.grpStatic10.Controls.Add(this.txtEditDcsetbuf12);
            this.grpStatic10.Controls.Add(this.txtEditDcsetbuf13);
            this.grpStatic10.Controls.Add(this.txtEditDcsetbuf14);
            this.grpStatic10.Controls.Add(this.txtEditDcsetbuf15);
            this.grpStatic10.Controls.Add(this.txtEditDcsetbuf16);
            this.grpStatic10.Controls.Add(this.txtEditDcsetbuf17);
            this.grpStatic10.Controls.Add(this.txtEditDcsetbuf18);
            this.grpStatic10.Controls.Add(this.txtEditDcsetbuf19);
            this.grpStatic10.Controls.Add(this.txtEditDcsetbuf2);
            this.grpStatic10.Controls.Add(this.txtEditDcsetbuf20);
            this.grpStatic10.Controls.Add(this.txtEditDcsetbuf21);
            this.grpStatic10.Controls.Add(this.txtEditDcsetbuf22);
            this.grpStatic10.Controls.Add(this.txtEditDcsetbuf23);
            this.grpStatic10.Controls.Add(this.txtEditDcsetbuf24);
            this.grpStatic10.Controls.Add(this.txtEditDcsetbuf25);
            this.grpStatic10.Controls.Add(this.txtEditDcsetbuf26);
            this.grpStatic10.Controls.Add(this.txtEditDcsetbuf27);
            this.grpStatic10.Controls.Add(this.txtEditDcsetbuf28);
            this.grpStatic10.Controls.Add(this.txtEditDcsetbuf29);
            this.grpStatic10.Controls.Add(this.txtEditDcsetbuf3);
            this.grpStatic10.Controls.Add(this.txtEditDcsetbuf30);
            this.grpStatic10.Controls.Add(this.txtEditDcsetbuf31);
            this.grpStatic10.Controls.Add(this.txtEditDcsetbuf4);
            this.grpStatic10.Controls.Add(this.txtEditDcsetbuf5);
            this.grpStatic10.Controls.Add(this.txtEditDcsetbuf6);
            this.grpStatic10.Controls.Add(this.txtEditDcsetbuf7);
            this.grpStatic10.Controls.Add(this.txtEditDcsetbuf8);
            this.grpStatic10.Controls.Add(this.txtEditDcsetbuf9);
            this.grpStatic10.Location = new System.Drawing.Point(22, 99);
            this.grpStatic10.Name = "grpStatic10";
            this.grpStatic10.Size = new System.Drawing.Size(560, 155);
            this.grpStatic10.TabIndex = 100;
            this.grpStatic10.TabStop = false;
            this.grpStatic10.Text = "Install and Set Secret";
            // 
            // btnButtonSet18
            // 
            this.btnButtonSet18.Location = new System.Drawing.Point(426, 103);
            this.btnButtonSet18.Name = "btnButtonSet18";
            this.btnButtonSet18.Size = new System.Drawing.Size(122, 24);
            this.btnButtonSet18.TabIndex = 150;
            this.btnButtonSet18.Text = "SetMasterSecret";
            this.btnButtonSet18.Click += new System.EventHandler(this.btnButtonSet18_Click);
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(15, 61);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(38, 13);
            this.label2.TabIndex = 141;
            this.label2.Text = "Secret";
            // 
            // btnButtonSet21
            // 
            this.btnButtonSet21.Location = new System.Drawing.Point(426, 69);
            this.btnButtonSet21.Name = "btnButtonSet21";
            this.btnButtonSet21.Size = new System.Drawing.Size(122, 24);
            this.btnButtonSet21.TabIndex = 149;
            this.btnButtonSet21.Text = "InstallSecret";
            this.btnButtonSet21.Click += new System.EventHandler(this.btnButtonSet21_Click);
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(15, 37);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(62, 13);
            this.label3.TabIndex = 6;
            this.label3.Text = "setbuf (hex)";
            // 
            // txtEditDcsetbuf0
            // 
            this.txtEditDcsetbuf0.Location = new System.Drawing.Point(86, 33);
            this.txtEditDcsetbuf0.Name = "txtEditDcsetbuf0";
            this.txtEditDcsetbuf0.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditDcsetbuf0.Size = new System.Drawing.Size(27, 20);
            this.txtEditDcsetbuf0.TabIndex = 5;
            // 
            // txtEditDcsetbuf1
            // 
            this.txtEditDcsetbuf1.Location = new System.Drawing.Point(117, 33);
            this.txtEditDcsetbuf1.Name = "txtEditDcsetbuf1";
            this.txtEditDcsetbuf1.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditDcsetbuf1.Size = new System.Drawing.Size(24, 20);
            this.txtEditDcsetbuf1.TabIndex = 7;
            // 
            // txtEditDcsetbuf10
            // 
            this.txtEditDcsetbuf10.Location = new System.Drawing.Point(148, 59);
            this.txtEditDcsetbuf10.Name = "txtEditDcsetbuf10";
            this.txtEditDcsetbuf10.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditDcsetbuf10.Size = new System.Drawing.Size(24, 20);
            this.txtEditDcsetbuf10.TabIndex = 26;
            // 
            // txtEditDcsetbuf11
            // 
            this.txtEditDcsetbuf11.Location = new System.Drawing.Point(178, 59);
            this.txtEditDcsetbuf11.Name = "txtEditDcsetbuf11";
            this.txtEditDcsetbuf11.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditDcsetbuf11.Size = new System.Drawing.Size(26, 20);
            this.txtEditDcsetbuf11.TabIndex = 27;
            // 
            // txtEditDcsetbuf12
            // 
            this.txtEditDcsetbuf12.Location = new System.Drawing.Point(212, 59);
            this.txtEditDcsetbuf12.Name = "txtEditDcsetbuf12";
            this.txtEditDcsetbuf12.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditDcsetbuf12.Size = new System.Drawing.Size(27, 20);
            this.txtEditDcsetbuf12.TabIndex = 28;
            // 
            // txtEditDcsetbuf13
            // 
            this.txtEditDcsetbuf13.Location = new System.Drawing.Point(244, 59);
            this.txtEditDcsetbuf13.Name = "txtEditDcsetbuf13";
            this.txtEditDcsetbuf13.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditDcsetbuf13.Size = new System.Drawing.Size(24, 20);
            this.txtEditDcsetbuf13.TabIndex = 29;
            // 
            // txtEditDcsetbuf14
            // 
            this.txtEditDcsetbuf14.Location = new System.Drawing.Point(274, 59);
            this.txtEditDcsetbuf14.Name = "txtEditDcsetbuf14";
            this.txtEditDcsetbuf14.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditDcsetbuf14.Size = new System.Drawing.Size(24, 20);
            this.txtEditDcsetbuf14.TabIndex = 30;
            // 
            // txtEditDcsetbuf15
            // 
            this.txtEditDcsetbuf15.Location = new System.Drawing.Point(304, 59);
            this.txtEditDcsetbuf15.Name = "txtEditDcsetbuf15";
            this.txtEditDcsetbuf15.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditDcsetbuf15.Size = new System.Drawing.Size(26, 20);
            this.txtEditDcsetbuf15.TabIndex = 31;
            // 
            // txtEditDcsetbuf16
            // 
            this.txtEditDcsetbuf16.Location = new System.Drawing.Point(86, 85);
            this.txtEditDcsetbuf16.Name = "txtEditDcsetbuf16";
            this.txtEditDcsetbuf16.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditDcsetbuf16.Size = new System.Drawing.Size(27, 20);
            this.txtEditDcsetbuf16.TabIndex = 32;
            // 
            // txtEditDcsetbuf17
            // 
            this.txtEditDcsetbuf17.Location = new System.Drawing.Point(117, 85);
            this.txtEditDcsetbuf17.Name = "txtEditDcsetbuf17";
            this.txtEditDcsetbuf17.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditDcsetbuf17.Size = new System.Drawing.Size(24, 20);
            this.txtEditDcsetbuf17.TabIndex = 33;
            // 
            // txtEditDcsetbuf18
            // 
            this.txtEditDcsetbuf18.Location = new System.Drawing.Point(147, 85);
            this.txtEditDcsetbuf18.Name = "txtEditDcsetbuf18";
            this.txtEditDcsetbuf18.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditDcsetbuf18.Size = new System.Drawing.Size(24, 20);
            this.txtEditDcsetbuf18.TabIndex = 34;
            // 
            // txtEditDcsetbuf19
            // 
            this.txtEditDcsetbuf19.Location = new System.Drawing.Point(177, 85);
            this.txtEditDcsetbuf19.Name = "txtEditDcsetbuf19";
            this.txtEditDcsetbuf19.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditDcsetbuf19.Size = new System.Drawing.Size(26, 20);
            this.txtEditDcsetbuf19.TabIndex = 35;
            // 
            // txtEditDcsetbuf2
            // 
            this.txtEditDcsetbuf2.Location = new System.Drawing.Point(147, 33);
            this.txtEditDcsetbuf2.Name = "txtEditDcsetbuf2";
            this.txtEditDcsetbuf2.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditDcsetbuf2.Size = new System.Drawing.Size(24, 20);
            this.txtEditDcsetbuf2.TabIndex = 8;
            // 
            // txtEditDcsetbuf20
            // 
            this.txtEditDcsetbuf20.Location = new System.Drawing.Point(210, 85);
            this.txtEditDcsetbuf20.Name = "txtEditDcsetbuf20";
            this.txtEditDcsetbuf20.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditDcsetbuf20.Size = new System.Drawing.Size(27, 20);
            this.txtEditDcsetbuf20.TabIndex = 36;
            // 
            // txtEditDcsetbuf21
            // 
            this.txtEditDcsetbuf21.Location = new System.Drawing.Point(243, 85);
            this.txtEditDcsetbuf21.Name = "txtEditDcsetbuf21";
            this.txtEditDcsetbuf21.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditDcsetbuf21.Size = new System.Drawing.Size(24, 20);
            this.txtEditDcsetbuf21.TabIndex = 37;
            // 
            // txtEditDcsetbuf22
            // 
            this.txtEditDcsetbuf22.Location = new System.Drawing.Point(273, 85);
            this.txtEditDcsetbuf22.Name = "txtEditDcsetbuf22";
            this.txtEditDcsetbuf22.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditDcsetbuf22.Size = new System.Drawing.Size(24, 20);
            this.txtEditDcsetbuf22.TabIndex = 38;
            // 
            // txtEditDcsetbuf23
            // 
            this.txtEditDcsetbuf23.Location = new System.Drawing.Point(303, 85);
            this.txtEditDcsetbuf23.Name = "txtEditDcsetbuf23";
            this.txtEditDcsetbuf23.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditDcsetbuf23.Size = new System.Drawing.Size(26, 20);
            this.txtEditDcsetbuf23.TabIndex = 39;
            // 
            // txtEditDcsetbuf24
            // 
            this.txtEditDcsetbuf24.Location = new System.Drawing.Point(86, 110);
            this.txtEditDcsetbuf24.Name = "txtEditDcsetbuf24";
            this.txtEditDcsetbuf24.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditDcsetbuf24.Size = new System.Drawing.Size(27, 20);
            this.txtEditDcsetbuf24.TabIndex = 40;
            // 
            // txtEditDcsetbuf25
            // 
            this.txtEditDcsetbuf25.Location = new System.Drawing.Point(117, 110);
            this.txtEditDcsetbuf25.Name = "txtEditDcsetbuf25";
            this.txtEditDcsetbuf25.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditDcsetbuf25.Size = new System.Drawing.Size(24, 20);
            this.txtEditDcsetbuf25.TabIndex = 41;
            // 
            // txtEditDcsetbuf26
            // 
            this.txtEditDcsetbuf26.Location = new System.Drawing.Point(147, 110);
            this.txtEditDcsetbuf26.Name = "txtEditDcsetbuf26";
            this.txtEditDcsetbuf26.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditDcsetbuf26.Size = new System.Drawing.Size(24, 20);
            this.txtEditDcsetbuf26.TabIndex = 42;
            // 
            // txtEditDcsetbuf27
            // 
            this.txtEditDcsetbuf27.Location = new System.Drawing.Point(177, 110);
            this.txtEditDcsetbuf27.Name = "txtEditDcsetbuf27";
            this.txtEditDcsetbuf27.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditDcsetbuf27.Size = new System.Drawing.Size(26, 20);
            this.txtEditDcsetbuf27.TabIndex = 43;
            // 
            // txtEditDcsetbuf28
            // 
            this.txtEditDcsetbuf28.Location = new System.Drawing.Point(210, 110);
            this.txtEditDcsetbuf28.Name = "txtEditDcsetbuf28";
            this.txtEditDcsetbuf28.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditDcsetbuf28.Size = new System.Drawing.Size(27, 20);
            this.txtEditDcsetbuf28.TabIndex = 44;
            // 
            // txtEditDcsetbuf29
            // 
            this.txtEditDcsetbuf29.Location = new System.Drawing.Point(243, 110);
            this.txtEditDcsetbuf29.Name = "txtEditDcsetbuf29";
            this.txtEditDcsetbuf29.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditDcsetbuf29.Size = new System.Drawing.Size(24, 20);
            this.txtEditDcsetbuf29.TabIndex = 45;
            // 
            // txtEditDcsetbuf3
            // 
            this.txtEditDcsetbuf3.Location = new System.Drawing.Point(177, 33);
            this.txtEditDcsetbuf3.Name = "txtEditDcsetbuf3";
            this.txtEditDcsetbuf3.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditDcsetbuf3.Size = new System.Drawing.Size(26, 20);
            this.txtEditDcsetbuf3.TabIndex = 9;
            // 
            // txtEditDcsetbuf30
            // 
            this.txtEditDcsetbuf30.Location = new System.Drawing.Point(273, 110);
            this.txtEditDcsetbuf30.Name = "txtEditDcsetbuf30";
            this.txtEditDcsetbuf30.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditDcsetbuf30.Size = new System.Drawing.Size(24, 20);
            this.txtEditDcsetbuf30.TabIndex = 46;
            // 
            // txtEditDcsetbuf31
            // 
            this.txtEditDcsetbuf31.Location = new System.Drawing.Point(303, 110);
            this.txtEditDcsetbuf31.Name = "txtEditDcsetbuf31";
            this.txtEditDcsetbuf31.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditDcsetbuf31.Size = new System.Drawing.Size(26, 20);
            this.txtEditDcsetbuf31.TabIndex = 47;
            // 
            // txtEditDcsetbuf4
            // 
            this.txtEditDcsetbuf4.Location = new System.Drawing.Point(210, 33);
            this.txtEditDcsetbuf4.Name = "txtEditDcsetbuf4";
            this.txtEditDcsetbuf4.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditDcsetbuf4.Size = new System.Drawing.Size(27, 20);
            this.txtEditDcsetbuf4.TabIndex = 20;
            // 
            // txtEditDcsetbuf5
            // 
            this.txtEditDcsetbuf5.Location = new System.Drawing.Point(243, 33);
            this.txtEditDcsetbuf5.Name = "txtEditDcsetbuf5";
            this.txtEditDcsetbuf5.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditDcsetbuf5.Size = new System.Drawing.Size(24, 20);
            this.txtEditDcsetbuf5.TabIndex = 21;
            // 
            // txtEditDcsetbuf6
            // 
            this.txtEditDcsetbuf6.Location = new System.Drawing.Point(273, 33);
            this.txtEditDcsetbuf6.Name = "txtEditDcsetbuf6";
            this.txtEditDcsetbuf6.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditDcsetbuf6.Size = new System.Drawing.Size(24, 20);
            this.txtEditDcsetbuf6.TabIndex = 22;
            // 
            // txtEditDcsetbuf7
            // 
            this.txtEditDcsetbuf7.Location = new System.Drawing.Point(303, 33);
            this.txtEditDcsetbuf7.Name = "txtEditDcsetbuf7";
            this.txtEditDcsetbuf7.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditDcsetbuf7.Size = new System.Drawing.Size(26, 20);
            this.txtEditDcsetbuf7.TabIndex = 23;
            // 
            // txtEditDcsetbuf8
            // 
            this.txtEditDcsetbuf8.Location = new System.Drawing.Point(86, 59);
            this.txtEditDcsetbuf8.Name = "txtEditDcsetbuf8";
            this.txtEditDcsetbuf8.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditDcsetbuf8.Size = new System.Drawing.Size(27, 20);
            this.txtEditDcsetbuf8.TabIndex = 24;
            // 
            // txtEditDcsetbuf9
            // 
            this.txtEditDcsetbuf9.Location = new System.Drawing.Point(118, 59);
            this.txtEditDcsetbuf9.Name = "txtEditDcsetbuf9";
            this.txtEditDcsetbuf9.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditDcsetbuf9.Size = new System.Drawing.Size(24, 20);
            this.txtEditDcsetbuf9.TabIndex = 25;
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.panel2);
            this.groupBox1.Controls.Add(this.panel9);
            this.groupBox1.Controls.Add(this.panel5);
            this.groupBox1.Controls.Add(this.panel8);
            this.groupBox1.Controls.Add(this.panel16);
            this.groupBox1.Controls.Add(this.panel3);
            this.groupBox1.Controls.Add(this.panel15);
            this.groupBox1.Controls.Add(this.lblStatic3);
            this.groupBox1.Controls.Add(this.panel7);
            this.groupBox1.Controls.Add(this.txtEditDcgetbuf0);
            this.groupBox1.Controls.Add(this.panel14);
            this.groupBox1.Controls.Add(this.panel13);
            this.groupBox1.Controls.Add(this.panel4);
            this.groupBox1.Controls.Add(this.panel12);
            this.groupBox1.Controls.Add(this.panel1);
            this.groupBox1.Controls.Add(this.panel11);
            this.groupBox1.Controls.Add(this.panel10);
            this.groupBox1.Controls.Add(this.panel6);
            this.groupBox1.Location = new System.Drawing.Point(22, 270);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(560, 231);
            this.groupBox1.TabIndex = 101;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Current Data";
            // 
            // groupBox2
            // 
            this.groupBox2.Controls.Add(this.btnButtonSet29);
            this.groupBox2.Controls.Add(this.txtEditDcgetbuf6);
            this.groupBox2.Controls.Add(this.btnButtonSet33);
            this.groupBox2.Location = new System.Drawing.Point(616, 99);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(423, 155);
            this.groupBox2.TabIndex = 102;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Read Data";
            // 
            // groupBox3
            // 
            this.groupBox3.Controls.Add(this.btnButtonSet31);
            this.groupBox3.Controls.Add(this.txtEditDcgetbuf5);
            this.groupBox3.Controls.Add(this.btnButtonSet30);
            this.groupBox3.Location = new System.Drawing.Point(616, 270);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(423, 231);
            this.groupBox3.TabIndex = 103;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "Encrpt and Write Data";
            // 
            // FrmSamrtpoesampleDialog
            // 
            this.ClientSize = new System.Drawing.Size(1054, 517);
            this.Controls.Add(this.groupBox3);
            this.Controls.Add(this.groupBox2);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.grpStatic10);
            this.Controls.Add(this.grpStatic8);
            this.Font = new System.Drawing.Font("Microsoft Sans Serif", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.MaximizeBox = false;
            this.Name = "FrmSamrtpoesampleDialog";
            this.Text = "License Management Sample";
            this.Load += new System.EventHandler(this.FrmSamrtpoesampleDialog_Load);
            this.grpStatic8.ResumeLayout(false);
            this.grpStatic8.PerformLayout();
            this.panel2.ResumeLayout(false);
            this.panel2.PerformLayout();
            this.panel3.ResumeLayout(false);
            this.panel3.PerformLayout();
            this.panel4.ResumeLayout(false);
            this.panel4.PerformLayout();
            this.panel5.ResumeLayout(false);
            this.panel5.PerformLayout();
            this.panel6.ResumeLayout(false);
            this.panel6.PerformLayout();
            this.panel7.ResumeLayout(false);
            this.panel7.PerformLayout();
            this.panel8.ResumeLayout(false);
            this.panel8.PerformLayout();
            this.panel9.ResumeLayout(false);
            this.panel9.PerformLayout();
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.panel10.ResumeLayout(false);
            this.panel10.PerformLayout();
            this.panel11.ResumeLayout(false);
            this.panel11.PerformLayout();
            this.panel12.ResumeLayout(false);
            this.panel12.PerformLayout();
            this.panel13.ResumeLayout(false);
            this.panel13.PerformLayout();
            this.panel14.ResumeLayout(false);
            this.panel14.PerformLayout();
            this.panel15.ResumeLayout(false);
            this.panel15.PerformLayout();
            this.panel16.ResumeLayout(false);
            this.panel16.PerformLayout();
            this.grpStatic10.ResumeLayout(false);
            this.grpStatic10.PerformLayout();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            this.ResumeLayout(false);

        } 
		#endregion

        private Panel panel2;
        private RadioButton rdoRadio1On1;
        private RadioButton rdoRadio1Off1;
        private Label lblStatic13;
        private Panel panel3;
        private RadioButton rdoRadio1Off2;
        private RadioButton rdoRadio1On2;
        private Label lblStatic14;
        private Panel panel4;
        private RadioButton rdoRadio1Off4;
        private RadioButton rdoRadio1On4;
        private Label lblStatic16;
        private Panel panel5;
        private RadioButton rdoRadio1Off3;
        private RadioButton rdoRadio1On3;
        private Label lblStatic15;
        private Panel panel6;
        private RadioButton rdoRadio1Off8;
        private RadioButton rdoRadio1On8;
        private Label lblStatic20;
        private Panel panel7;
        private RadioButton rdoRadio1Off6;
        private RadioButton rdoRadio1On6;
        private Label lblStatic18;
        private Panel panel8;
        private RadioButton rdoRadio1Off7;
        private RadioButton rdoRadio1On7;
        private Label lblStatic19;
        private Panel panel9;
        private RadioButton rdoRadio1Off5;
        private RadioButton rdoRadio1On5;
        private Label lblStatic17;
        private Panel panel1;
        private RadioButton rdoRadio1Off16;
        private RadioButton rdoRadio1On16;
        private Label lblStatic28;
        private Panel panel10;
        private RadioButton rdoRadio1Off12;
        private RadioButton rdoRadio1On12;
        private Label lblStatic24;
        private Panel panel11;
        private RadioButton rdoRadio1Off14;
        private RadioButton rdoRadio1On14;
        private Label lblStatic26;
        private Panel panel12;
        private RadioButton rdoRadio1Off10;
        private RadioButton rdoRadio1On10;
        private Label lblStatic22;
        private Panel panel13;
        private RadioButton rdoRadio1Off15;
        private RadioButton rdoRadio1On15;
        private Label lblStatic27;
        private Panel panel14;
        private RadioButton rdoRadio1On11;
        private Label lblStatic23;
        private Panel panel15;
        private RadioButton rdoRadio1Off13;
        private RadioButton rdoRadio1On13;
        private Label lblStatic25;
        private Panel panel16;
        private RadioButton rdoRadio1Off9;
        private RadioButton rdoRadio1On9;
        private Label label1;
        private GroupBox grpStatic10;
        private Label label2;
        private Label label3;
        private TextBox txtEditDcsetbuf0;
        private TextBox txtEditDcsetbuf1;
        private TextBox txtEditDcsetbuf10;
        private TextBox txtEditDcsetbuf11;
        private TextBox txtEditDcsetbuf12;
        private TextBox txtEditDcsetbuf13;
        private TextBox txtEditDcsetbuf14;
        private TextBox txtEditDcsetbuf15;
        private TextBox txtEditDcsetbuf16;
        private TextBox txtEditDcsetbuf17;
        private TextBox txtEditDcsetbuf18;
        private TextBox txtEditDcsetbuf19;
        private TextBox txtEditDcsetbuf2;
        private TextBox txtEditDcsetbuf20;
        private TextBox txtEditDcsetbuf21;
        private TextBox txtEditDcsetbuf22;
        private TextBox txtEditDcsetbuf23;
        private TextBox txtEditDcsetbuf24;
        private TextBox txtEditDcsetbuf25;
        private TextBox txtEditDcsetbuf26;
        private TextBox txtEditDcsetbuf27;
        private TextBox txtEditDcsetbuf28;
        private TextBox txtEditDcsetbuf29;
        private TextBox txtEditDcsetbuf3;
        private TextBox txtEditDcsetbuf30;
        private TextBox txtEditDcsetbuf31;
        private TextBox txtEditDcsetbuf4;
        private TextBox txtEditDcsetbuf5;
        private TextBox txtEditDcsetbuf6;
        private TextBox txtEditDcsetbuf7;
        private TextBox txtEditDcsetbuf8;
        private TextBox txtEditDcsetbuf9;
        private Button btnButtonSet21;
        private Button btnButtonSet18;
        private RadioButton rdoRadio1Off11;
        private GroupBox groupBox1;
        private GroupBox groupBox2;
        private GroupBox groupBox3;

	}
}
