
//This code has been automatically generated by DudeLabs LLC RCConverter
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Text;
using System.Windows.Forms;
using System.IO;
using System.Runtime.InteropServices;

namespace CS_testSecurity5
{
    /// <summary>
    /// Summary description for FrmSamrtpoesampleDialog.
    /// </summary>
    public partial class FrmSamrtpoesampleDialog : System.Windows.Forms.Form
    {
        [DllImport("msvcrt.dll")]
        public static extern int srand(int seed);
        

        public FrmSamrtpoesampleDialog()
        {
            //
            // Required for Windows Form Designer support
            //
            InitializeComponent();
            m_Number = -1;
            //
            // TODO: Add any constructor code after InitializeComponent call
            //
            //RadioButton [] RadioBtnOn, RadioBtnOff;


            RadioBtnOn[0] = rdoRadio1On1;
            RadioBtnOn[1] = rdoRadio1On2;
            RadioBtnOn[2] = rdoRadio1On3;
            RadioBtnOn[3] = rdoRadio1On4;
            RadioBtnOn[4] = rdoRadio1On5;
            RadioBtnOn[5] = rdoRadio1On6;
            RadioBtnOn[6] = rdoRadio1On7;
            RadioBtnOn[7] = rdoRadio1On8;
            RadioBtnOn[8] = rdoRadio1On9;
            RadioBtnOn[9] = rdoRadio1On10;
            RadioBtnOn[10] = rdoRadio1On11;
            RadioBtnOn[11] = rdoRadio1On12;
            RadioBtnOn[12] = rdoRadio1On13;
            RadioBtnOn[13] = rdoRadio1On14;
            RadioBtnOn[14] = rdoRadio1On15;
            RadioBtnOn[15] = rdoRadio1On16;

            RadioBtnOff[0] = rdoRadio1Off1;
            RadioBtnOff[1] = rdoRadio1Off2;
            RadioBtnOff[2] = rdoRadio1Off3;
            RadioBtnOff[3] = rdoRadio1Off4;
            RadioBtnOff[4] = rdoRadio1Off5;
            RadioBtnOff[5] = rdoRadio1Off6;
            RadioBtnOff[6] = rdoRadio1Off7;
            RadioBtnOff[7] = rdoRadio1Off8;
            RadioBtnOff[8] = rdoRadio1Off9;
            RadioBtnOff[9] = rdoRadio1Off10;
            RadioBtnOff[10] = rdoRadio1Off11;
            RadioBtnOff[11] = rdoRadio1Off12;
            RadioBtnOff[12] = rdoRadio1Off13;
            RadioBtnOff[13] = rdoRadio1Off14;
            RadioBtnOff[14] = rdoRadio1Off15;
            RadioBtnOff[15] = rdoRadio1Off16;


            txtEditDcsetbuf[0] = txtEditDcsetbuf0;
            txtEditDcsetbuf[1] = txtEditDcsetbuf1;
            txtEditDcsetbuf[2] = txtEditDcsetbuf2;
            txtEditDcsetbuf[3] = txtEditDcsetbuf3;
            txtEditDcsetbuf[4] = txtEditDcsetbuf4;
            txtEditDcsetbuf[5] = txtEditDcsetbuf5;
            txtEditDcsetbuf[6] = txtEditDcsetbuf6;
            txtEditDcsetbuf[7] = txtEditDcsetbuf7;
            txtEditDcsetbuf[8] = txtEditDcsetbuf8;
            txtEditDcsetbuf[9] = txtEditDcsetbuf9;
            txtEditDcsetbuf[10] = txtEditDcsetbuf10;
            txtEditDcsetbuf[11] = txtEditDcsetbuf11;
            txtEditDcsetbuf[12] = txtEditDcsetbuf12;
            txtEditDcsetbuf[13] = txtEditDcsetbuf13;
            txtEditDcsetbuf[14] = txtEditDcsetbuf14;
            txtEditDcsetbuf[15] = txtEditDcsetbuf15;
            txtEditDcsetbuf[16] = txtEditDcsetbuf16;
            txtEditDcsetbuf[17] = txtEditDcsetbuf17;
            txtEditDcsetbuf[18] = txtEditDcsetbuf18;
            txtEditDcsetbuf[19] = txtEditDcsetbuf19;
            txtEditDcsetbuf[20] = txtEditDcsetbuf20;
            txtEditDcsetbuf[21] = txtEditDcsetbuf21;
            txtEditDcsetbuf[22] = txtEditDcsetbuf22;
            txtEditDcsetbuf[23] = txtEditDcsetbuf23;
            txtEditDcsetbuf[24] = txtEditDcsetbuf24;
            txtEditDcsetbuf[25] = txtEditDcsetbuf25;
            txtEditDcsetbuf[26] = txtEditDcsetbuf26;
            txtEditDcsetbuf[27] = txtEditDcsetbuf27;
            txtEditDcsetbuf[28] = txtEditDcsetbuf28;
            txtEditDcsetbuf[29] = txtEditDcsetbuf29;
            txtEditDcsetbuf[30] = txtEditDcsetbuf30;
            txtEditDcsetbuf[31] = txtEditDcsetbuf31;

        }

        private void btnButtonSet4_Click(object sender, EventArgs e)
        {
            //SetDlgItemText(IDC_EDIT_ERROR, "");
            txtEditError.Text = "";
        }


        public short m_Number { get; set; }
        public RadioButton[] RadioBtnOn = new RadioButton[16];
        public RadioButton[] RadioBtnOff = new RadioButton[16];


        private void cboComboCardNumber_SelectedIndexChanged(object sender, EventArgs e)
        {
            Int16 Number;
            UInt16 card_num = (UInt16)cboComboCardNumber.SelectedIndex;
            //(U16)((CComboBox*)GetDlgItem(IDC_COMBO_CARD_NUMBER))->GetCurSel();


            if (m_Number >= 0)
                SmartPoE.SmartPoE_Release_Card((ushort)m_Number);

            if ((Number = SmartPoE.SmartPoE_Register_Card(card_num)) != SmartPoE.PoE_NoError)
            {
                MessageBox.Show("Selecting card is failed");
                return;
            }

            ushort ID;
            short EEVersion, EEStandard, EEPort;
            ushort MCUVersion;
            Int16 ret = SmartPoE.SmartPoE_Get_ID((ushort)Number, out ID);
            if (ret < 0)
                txtEditError.Text = "Error";
            else
                txtEditId.Text = ID.ToString();


            m_Number = Number;

            /////////////////////////////

            ret = SmartPoE.GIE_Get_Chk_EEVersion((ushort)Number, out EEVersion);
            if (ret < 0)
                txtEditError.Text = "Error";
            else
                txtEditId14.Text = EEVersion.ToString();


            ret = SmartPoE.GIE_Get_Chk_EEStandard((ushort)Number, out EEStandard);
            if (ret < 0)
                txtEditError.Text = "Error";
            else
                txtEditId15.Text = EEStandard.ToString();

            ret = SmartPoE.GIE_Get_Chk_EEPort((UInt16)Number, out EEPort);
            if (ret < 0)
                txtEditError.Text = "Error";
            else
                txtEditId16.Text = EEPort.ToString();

            UInt32 ID2, ID3;
            ret = SmartPoE.SmartPoE_Get_CPLDVersion((UInt16)Number, out ID2, out ID3);
            if (ret < 0)
                txtEditError.Text = "Error";
            else
            {
                txtEditId18.Text = String.Format("{0:x}", ID2);
                txtEditId19.Text = String.Format("{0:x}", ID3);
            }

            ret = SmartPoE.SmartPoE_Get_MCUVersion((UInt16)Number, out MCUVersion);
            if (ret < 0)
                txtEditId20.Text = "Error";
            else
                txtEditId20.Text = Convert.ToString(MCUVersion, 16);


            /////////////////////////////

        }

        private void FrmSamrtpoesampleDialog_Load(object sender, EventArgs e)
        {
            // Set the icon for this dialog.  The framework does this automatically
            //  when the application's main window is not a dialog


            //TBD
            //SetIcon(m_hIcon, TRUE);			// Set big icon
            //SetIcon(m_hIcon, FALSE);		// Set small icon

            UInt16 i;
            //CString str;
            short num;

            for (i = 0; i < SmartPoE.MAX_CARD; i++)
            {
                if ((num = SmartPoE.SmartPoE_Register_Card(i)) != SmartPoE.PoE_NoError)
                    break;

                SmartPoE.SmartPoE_Release_Card((UInt16)num);
                cboComboCardNumber.Items.Add(String.Format("{0:d}", i));
            }

            if (i == 0)
            {
                MessageBox.Show("No card is found!");
                return;
            }

            cboComboCardNumber.SelectedIndex = 0;
            cboComboCardNumber_SelectedIndexChanged(sender, e);

            #region 
            rdoRadio1Off1.Checked = true;
            rdoRadio1Off2.Checked = true;
            rdoRadio1Off3.Checked = true;
            rdoRadio1Off4.Checked = true;
            rdoRadio1Off5.Checked = true;
            rdoRadio1Off6.Checked = true;
            rdoRadio1Off7.Checked = true;
            rdoRadio1Off8.Checked = true;
            rdoRadio1Off9.Checked = true;
            rdoRadio1Off10.Checked = true;
            rdoRadio1Off11.Checked = true;
            rdoRadio1Off12.Checked = true;
            rdoRadio1Off13.Checked = true;
            rdoRadio1Off14.Checked = true;
            rdoRadio1Off15.Checked = true;
            rdoRadio1Off16.Checked = true;

            rdoRadio1On1.Checked = false;
            rdoRadio1On2.Checked = false;
            rdoRadio1On3.Checked = false;
            rdoRadio1On4.Checked = false;
            rdoRadio1On5.Checked = false;
            rdoRadio1On6.Checked = false;
            rdoRadio1On7.Checked = false;
            rdoRadio1On8.Checked = false;
            rdoRadio1On9.Checked = false;
            rdoRadio1On10.Checked = false;
            rdoRadio1On11.Checked = false;
            rdoRadio1On12.Checked = false;
            rdoRadio1On13.Checked = false;
            rdoRadio1On14.Checked = false;
            rdoRadio1On15.Checked = false;
            rdoRadio1On16.Checked = false;
            #endregion

            txtEditDcgetbuf0.Text = "00000000000000000000000000000000";


            //cannot find these items
            for (i = 0; i < 32; i++)
            {
                txtEditDcsetbuf[i].Text = string.Format("{0:X}", i);
            }

            //txtEditDcsetbuf[0].Text = "00";

            //txtEditDcgetbuf3.Text = "0";



            srand((int)DateTime.Now.ToBinary());
            //return true;  // return TRUE  unless you set the focus to a control
        }
        public System.Windows.Forms.TextBox[] txtEditDcsetbuf = new System.Windows.Forms.TextBox[32];
        private void btnButtonSet32_Click(object sender, EventArgs e)
        {
            byte bitstatus = 0;
            byte lockstatus = 0;
            UInt16 wCardNum = (ushort)m_Number;
            int err;

            err = AD_License_management.AD_ReadInstallSecretStatus(wCardNum, out bitstatus, out lockstatus);
            
            // bitsatus = 0 (Non-burned card)
            // bitsatus = 1 (Burned card)
            // bitsatus = 2 (Burned card and data locked)
            // lockstatus = 0 (Secret non-locked)
            // lockstatus = 1 (Secret locked)

            MessageBox.Show("Card Status:" + bitstatus.ToString() + "," + "Secret Status:" + lockstatus.ToString());
                
        }


        private void btnButtonSet29_Click(object sender, EventArgs e)
        {
            // TODO: 在此加入控制項告知處理常式程式碼

            UInt16 wCardNum = (ushort)m_Number;
            string str;
            string str2;
            string str3;
            string str4;

            //  byte challenge[32];
            byte[] data = new byte[32];
            byte[] new_data = new byte[32];
            byte[] data1 = new byte[32];
            byte[] mac = new byte[32];
            byte[] read_mac = new byte[32];

            byte[] page7SavedData = new byte[32];
            byte[] page8SavedData = new byte[32];
            byte[] page9SavedData = new byte[32];

            int result;
            int compareOK = 1;
            //UInt16 startPage = 0x07;     
            UInt16 startPage = 0x01;
            int num_pages_to_test = 1;
            int num_bytes_to_test = 32;

            ////////////////////////////

            byte[] notUsed = new byte[1];
            UInt16 zeroLen = 0;
            UInt16 len32 = 32;

            byte[] data3 = new byte[32];
            byte[] data4 = new byte[12];
            byte[] data5 = new byte[1];
            int i;
            int rslt;
            int rt = 1;
            int block;
            int skip_setup = 0;
            int page;
            int cnt;

            byte[] partial = new byte[32];
            byte[] new_page = new byte[32];
            int current_secret = 0;
            int cleared_byte;
            byte[] memimage = new byte[512];
            byte[] master_secret = new byte[32];
            byte[] binding = new byte[32];
            byte[] romid = new byte[8];
            byte[] manid = new byte[2];
            byte[] challenge = new byte[8];

            byte[] ITROMId = new byte[8];
            byte[] ITMANId = new byte[2];
            byte[] ITmaster_secret = new byte[32];
            byte[] ITpartial = new byte[32];
            byte[] ITbinding = new byte[32];

            String path = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
            path = path + "\\ADLINK";
            try
            {
                // Determine whether the directory exists.
                if (Directory.Exists(path))
                    Console.WriteLine("That path exists already.");
                else
                {
                    // Try to create the directory.
                    DirectoryInfo di = Directory.CreateDirectory(path);
                    Console.WriteLine("The directory was created successfully at {0}.", Directory.GetCreationTime(path));
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("The process failed: {0}", e.ToString());
            }
            finally { }

            // open log file and print time stamp
            path = path + "\\log8-2.txt";
            try
            {
                using (StreamWriter w = File.AppendText(path))
                {
                    //RandomNumbers.Seed((uint)time(null));
                    w.WriteLine("AD_EncryptReadSegment_ex2, wCardNum {0}", wCardNum);
                    rslt = AD_License_management.AD_EncryptReadSegment(wCardNum, data, romid, manid, read_mac, challenge);

                    w.Write("data: ");
                    for (i = 0; i < 32; i++)
                    {
                        w.Write("{0:X2}", data[i]);
                    }
                    w.WriteLine("");

                    w.Write("romid: ");
                    for (i = 0; i < 8; i++)
                    {
                        w.Write("{0:X2}", romid[i]);
                    }
                    w.WriteLine("");

                    w.Write("manid: ");
                    for (i = 0; i < 2; i++)
                    {
                        w.Write("{0:X2}", manid[i]);
                    }
                    w.WriteLine("");

                    w.Write("read_mac: ");
                    for (i = 0; i < 32; i++)
                    {
                        w.Write("{0:X2}", read_mac[i]);
                    }
                    w.WriteLine("");

                    w.Write("challenge: ");
                    for (i = 0; i < 8; i++)
                    {
                        w.Write("{0:X2}", challenge[i]);
                    }
                    w.WriteLine("");


                    //for (i = 0; i < 16; i++)
                    //{


                    //    //((CButton)GetDlgItem(IDC_RADIO1_ON1 + (i * 2))).SetCheck(data[i] == 0x71 + i != 0 ? 1 : 0);
                    //    //((CButton)GetDlgItem(IDC_RADIO1_OFF1 + (i * 2))).SetCheck(data[i] == 0x61 + i != 0 ? 1 : 0);

                    //    //TBD check data[i] == 0x71 + i != 0
                    //    RadioBtnOn[i].Checked = (data[i] == 0x71 ? true : false);
                    //    RadioBtnOff[i].Checked = (data[i] == 0x61 ? true : false);
                    //}

                    str = ""; //data[32] + romid[8] + manid[2] + read_mac[32] + challenge[8]

                    for (i = 0; i < 32; i++)
                    {
                        str += String.Format("{0:X2}", data[i]);
                    }
                    txtEditDcgetbuf0.Text = str;

                    for (i = 0; i < 8; i++)
                    {
                        str += String.Format("{0:X2}", romid[i]);
                    }
                    for (i = 0; i < 2; i++)
                    {
                        str += String.Format("{0:X2}", manid[i]);
                    }

                    for (i = 0; i < 32; i++)
                    {
                        str += String.Format("{0:X2}", read_mac[i]);
                    }

                    for (i = 0; i < 8; i++)
                    {
                        str += String.Format("{0:X2}", challenge[i]);
                    }
                    txtEditDcgetbuf6.Text = str;


                    w.Write("AD_EncryptReadSegment:  ----------------------------------");
                    w.Write("{0}\r\n", (rslt) != 0 ? "FAIL" : "SUCCESS");
                    if (rslt != 0)
                    {
                        rt = 0;
                    }


                    if (rt == 1)
                    {
                        w.Write("Test Pass!");
                    }
                    else
                    {
                        w.Write("Test Fail!");
                    }
                }
            }
            catch 
            {
                MessageBox.Show("ERROR, Could not open LOT.TXT log file!\n");                
            }
        }

        private void btnButtonSet33_Click(object sender, EventArgs e)
        {
            // TODO: 在此加入控制項告知處理常式程式碼
            UInt16 wCardNum = (ushort) m_Number;

            string str;
            string str2;
            string str3;
            string str4;
            byte[] challenge = new byte[32];
            byte[] data = new byte[32];
            byte[] new_data = new byte[32];
            byte[] data1 = new byte[32];
            byte[] enc_data = new byte[32];
            byte[] chk_mac = new byte[32];
            byte[] mac = new byte[32];
            byte[] read_mac = new byte[32];

            byte[] page7SavedData = new byte[32];
            byte[] page8SavedData = new byte[32];
            byte[] page9SavedData = new byte[32];

            int result;
            int compareOK = 1;
            //UInt16 startPage = 0x07;     
            UInt16 startPage = 0x01;
            int num_pages_to_test = 1;
            int num_bytes_to_test = 32;

            ////////////////////////////

            byte[] notUsed = new byte[1];
            UInt16 zeroLen = 0;
            UInt16 len32 = 32;

            byte[] data3 = new byte[32];
            byte[] data4 = new byte[12];
            byte[] data5 = new byte[1];
            int i;
            int rslt = 0;
            int rt = 1;
            int block;
            int skip_setup = 0;
            int page;
            int cnt;

            byte[] partial = new byte[32];
            byte[] new_page = new byte[32];
            int current_secret = 0;
            int cleared_byte;
            byte[] memimage = new byte[512];
            byte[] master_secret = new byte[32];
            byte[] binding = new byte[32];
            byte[] romid = new byte[8];
            byte[] manid = new byte[2];


            //UCHAR   ITROMId[8];
            //UCHAR   ITMANId[2];
            //UCHAR   ITmaster_secret[32];
            //UCHAR   ITpartial[32];
            //UCHAR   ITbinding[32];

            string strHex;

            String path = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
            path = path + "\\ADLINK";
            try
            {
                // Determine whether the directory exists.
                if (Directory.Exists(path))
                    Console.WriteLine("That path exists already.");
                else
                {
                    // Try to create the directory.
                    DirectoryInfo di = Directory.CreateDirectory(path);
                    Console.WriteLine("The directory was created successfully at {0}.", Directory.GetCreationTime(path));
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("The process failed: {0}", e.ToString());
            }
            finally { }

            // open log file and print time stamp            
            path = path + "\\log8-6.txt";      
            try
            {
                using (StreamWriter w = File.AppendText(path))
                {
                    //RandomNumbers.Seed((uint)time(null));
                    w.Write("num_bytes_to_test: ");
                    w.Write("{0}", num_bytes_to_test);

                    //GetDlgItemText(IDC_EDIT_DCGETBUF6, str); //data[32] + romid[8] + manid[2] + read_mac[32];
                    str = txtEditDcgetbuf6.Text;

                    for (i = 0; i < 32; i++)
                    {                        
                        
                        strHex = str.Substring((i * 2) + (0 * 2), 1);
                        strHex = strHex + str.Substring((i * 2) + 1 + (0 * 2), 1);
                        data[i] = (byte)hex2uint(strHex);
                    }

                    for (i = 0; i < 8; i++)
                    {                        
                        strHex = str.Substring((i * 2) + (32 * 2), 2);                        
                        romid[i] = (byte)hex2uint(strHex);
                    }

                    for (i = 0; i < 2; i++)
                    {
                        strHex = str.Substring((i * 2) + (40 * 2), 2);
                        manid[i] = (byte)hex2uint(strHex);
                    }

                    for (i = 0; i < 32; i++)
                    {
                        strHex = str.Substring((i * 2) + (42 * 2), 2);
                        read_mac[i] = (byte)hex2uint(strHex);
                    }


                    for (i = 0; i < 16; i++)
                    {
                        //((CButton)GetDlgItem(IDC_RADIO1_ON1 + (i * 2))).SetCheck(data[i] == 0x71 + i != 0 ? 1 : 0);
                        //((CButton)GetDlgItem(IDC_RADIO1_OFF1 + (i * 2))).SetCheck(data[i] == 0x61 + i != 0 ? 1 : 0);
                        RadioBtnOn[i].Checked = (data[i] == 0x71 + i != false) ? true : false;
                        RadioBtnOff[i].Checked = (data[i] == 0x61 + i != false) ? true : false;
                    }

                    w.Write("data: ");
                    for (i = 0; i < 32; i++)
                    {
                        w.Write("{0:X2}", data[i]);
                    }
                    w.Write("\r\n");

                    w.Write("romid: ");
                    for (i = 0; i < 8; i++)
                    {
                        w.Write("{0:X2}", romid[i]);
                    }
                    w.Write("\r\n");

                    w.Write("manid: ");
                    for (i = 0; i < 2; i++)
                    {
                        w.Write("{0:X2}", manid[i]);
                    }
                    w.Write("\r\n");

                    w.Write("data: ");
                    for (i = 0; i < 32; i++)
                    {
                        w.Write("{0:X2}", read_mac[i]);
                    }
                    w.Write("\n");

                    w.Write("Check ON/OFF: ----------------------------------");
                    w.Write(" {0}\r\n", (rslt) != 0 ? "FAIL" : "SUCCESS");
                    if (rslt != 0)
                    {
                        rt = 0;
                    }

                    if (rt == 1)
                    {
                        w.Write("Test Pass!");
                    }
                    else
                    {
                        w.Write("Test Fail!");
                    }
                }
            }
            catch
            {            
                MessageBox.Show("ERROR, Could not open LOT.TXT log file!\n");                
            }
        }

        private uint hex2uint(string h)
        {
            int len;
            string str;
            uint ret = 0;
            sbyte c;

            len = h.Length;
            if (len > 16 || len <= 0)
            {
                return 0;
            }

            h.ToUpper();
            //str = h.GetBuffer(10); 
            str = h;

            for (int i = 0; i < len; i++)
            {
                c = (sbyte)str[i];
                if (c >= '0' && c <= '9')
                {
                    ret = (uint) ((ret << 4) + c - '0');
                }
                else if (c >= 'A' && c <= 'F')
                {
                    ret = (uint)((ret << 4) + c - 'A' + 10);
                }
                else
                {
                    return 0;
                }
            }

            return ret;
        }

        private void btnButtonSet31_Click(object sender, EventArgs e)
        {
            // TODO: 在此加入控制項告知處理常式程式碼
            UInt16 wCardNum = (ushort) m_Number;

            string str;
            string str2;
            string str3;
            string str4;
            byte[] data = new byte[32];
            byte[] new_data = new byte[32];
            byte[] data1 = new byte[32];
            byte[] enc_data = new byte[32];
            byte[] chk_mac = new byte[32];
            byte[] mac = new byte[32];
            byte[] read_mac = new byte[32];

            byte[] page7SavedData = new byte[32];
            byte[] page8SavedData = new byte[32];
            byte[] page9SavedData = new byte[32];

            int result;
            int compareOK = 1;
            UInt16 startPage = 0x01;
            int num_pages_to_test = 1;
            int num_bytes_to_test = 32;

            ////////////////////////////

            byte[] notUsed = new byte[1];
            UInt16 zeroLen = 0;
            UInt16 len32 = 32;

            byte[] data3 = new byte[32];
            byte[] data4 = new byte[12];
            byte[] data5 = new byte[1];
            int i;
            int rslt;
            int rt = 1;
            int block;
            int skip_setup = 0;
            int page;
            int cnt;

            byte[] partial = new byte[32];
            byte[] new_page = new byte[32];
            int current_secret = 0;
            int cleared_byte;
            byte[] memimage = new byte[512];
            byte[] master_secret = new byte[32];
            byte[] binding = new byte[32];
            byte[] romid = new byte[8];
            byte[] manid = new byte[2];
            byte[] challenge = new byte[8];

            byte[] ITROMId = new byte[8];
            byte[] ITMANId = new byte[2];
            byte[] ITmaster_secret = new byte[32];
            byte[] ITpartial = new byte[32];
            byte[] ITbinding = new byte[32];

            string strHex;

            String path = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
            path = path + "\\ADLINK";
            try
            {
                // Determine whether the directory exists.
                if (Directory.Exists(path))
                    Console.WriteLine("That path exists already.");
                else
                {
                    // Try to create the directory.
                    DirectoryInfo di = Directory.CreateDirectory(path);
                    Console.WriteLine("The directory was created successfully at {0}.", Directory.GetCreationTime(path));
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("The process failed: {0}", e.ToString());
            }
            finally { }

            // open log file and print time stamp            
            path = path + "\\log8-2.txt";           
            try
            {
                using (StreamWriter w = File.AppendText(path))
                {
                    //RandomNumbers.Seed((uint)time(null));
                    w.Write("num_bytes_to_test: ");
                    w.Write("{0}", num_bytes_to_test);
                    
                    str = txtEditDcgetbuf6.Text;
                    for (i = 0; i < 32; i++)
                    {
                        //strHex = str[(i * 2) + (0 * 2)];
                        //strHex = strHex + str[(i * 2) + 1 + (0 * 2)];
                        strHex = str.Substring((i * 2) + (0 * 2), 2);
                        data[i] = (byte)hex2uint(strHex);
                    }

                    for (i = 0; i < 8; i++)
                    {
                        //strHex = str[(i * 2) + (32 * 2)];
                        //strHex = strHex + str[(i * 2) + 1 + (32 * 2)];
                        strHex = str.Substring((i * 2) + (32 * 2), 2);
                        romid[i] = (byte)hex2uint(strHex);
                    }

                    for (i = 0; i < 2; i++)
                    {
                        //strHex = str[(i * 2) + (40 * 2)];
                        //strHex = strHex + str[(i * 2) + 1 + (40 * 2)];
                        strHex = str.Substring((i * 2) + (40 * 2), 2);
                        manid[i] = (byte)hex2uint(strHex);
                    }

                    for (i = 0; i < 32; i++)
                    {
                        //strHex = str[(i * 2) + (42 * 2)];
                        //strHex = strHex + str[(i * 2) + 1 + (42 * 2)];
                        strHex = str.Substring((i * 2) + (42 * 2), 2);
                        read_mac[i] = (byte)hex2uint(strHex);
                    }

                    for (i = 0; i < 8; i++)
                    {
                        //strHex = str[(i * 2) + (74 * 2)];
                        //strHex = strHex + str[(i * 2) + 1 + (74 * 2)];
                        strHex = str.Substring((i * 2) + (74 * 2), 2);
                        challenge[i] = (byte)hex2uint(strHex);
                    }

                    for (i = 0; i < 16; i++)
                    {
                        //new_data[i] = (byte)((CButton)GetDlgItem(IDC_RADIO1_ON1 + (i * 2))).GetCheck() ? 0x71 + i : 0x61 + i;
                        new_data[i] = (byte)(RadioBtnOn[i].Checked ? 0x71 + i : 0x61 + i);
                    }

                    for (i = 16; i < 32; i++)
                    {
                        new_data[i] = (byte)1;
                    }

                    w.Write("AD_EncryptComputeEnc_ex2, wCardNum {0}\r\n", wCardNum);
                    rslt = AD_License_management.AD_EncryptComputeEnc(wCardNum, new_data, romid, manid, read_mac, challenge, enc_data, chk_mac);

                    w.Write("enc_data: ");
                    for (i = 0; i < num_bytes_to_test; i++)
                    {
                        w.Write("{0:X2}", enc_data[i]);
                    }
                    w.Write("\r\n");

                    w.Write("chk_mac: ");
                    for (i = 0; i < num_bytes_to_test; i++)
                    {
                        w.Write("{0:X2}", chk_mac[i]);
                    }
                    w.Write("\r\n");

                    w.Write("data: ");
                    for (i = 0; i < 32; i++)
                    {
                        w.Write("{0:X2}", data[i]);
                    }
                    w.Write("\r\n");

                    w.Write("romid: ");
                    for (i = 0; i < 8; i++)
                    {
                        w.Write("{0:X2}", romid[i]);
                    }
                    w.Write("\r\n");

                    w.Write("manid: ");
                    for (i = 0; i < 2; i++)
                    {
                        w.Write("{0:X2}", manid[i]);
                    }
                    w.Write("\r\n");

                    w.Write("read_mac: ");
                    for (i = 0; i < 32; i++)
                    {
                        w.Write("{0:X2}", read_mac[i]);
                    }
                    w.Write("\r\n");

                    w.Write("challenge: ");
                    for (i = 0; i < 8; i++)
                    {
                        w.Write("{0:X2}", challenge[i]);
                    }
                    w.Write("\r\n");


                    str = ""; //data[32] + romid[8] + manid[2] + enc_data[32] + chk_mac[32] + challenge[8]
                    for (i = 0; i < 32; i++)
                    {                        
                        str += string.Format("{0:X2}", data[i]);
                    }
                    txtEditDcgetbuf0.Text = str;                    

                    for (i = 0; i < 8; i++)
                    {                        
                        str += string.Format("{0:X2}", romid[i]);
                    }

                    for (i = 0; i < 2; i++)
                    {                        
                        str += string.Format("{0:X2}", manid[i]);
                    }

                    for (i = 0; i < 32; i++)
                    {                        
                        str += string.Format("{0:X2}", enc_data[i]);
                    }

                    for (i = 0; i < 32; i++)
                    {                     
                        str += string.Format("{0:X2}", chk_mac[i]);
                    }

                    for (i = 0; i < 8; i++)
                    {                        
                        str += string.Format("{0:X2}", challenge[i]);
                    }
                    txtEditDcgetbuf5.Text = str;  //data[32] + romid[8] + manid[2] + enc_data[32] + chk_mac[32] + challenge[8]\                    


                    w.Write("AD_EncryptComputeEnc_ex2: ----------------------------------");
                    w.Write(" {0}\r\n", (rslt==1) ? "FAIL" : "SUCCESS");
                    if (rslt==1)
                    {
                        rt = 0;
                    }

                    if (rt == 1)
                    {
                        w.Write("Test Pass!");
                    }
                    else
                    {
                        w.Write("Test Fail!");
                    }
                }
            }
            catch 
            {
                MessageBox.Show("ERROR, Could not open LOT.TXT log file!\n");                
            }
        }

        private void btnButtonSet30_Click(object sender, EventArgs e)
        {
            UInt16 wCardNum = (ushort)m_Number;

            byte[] data = new byte[32];
            byte[] new_data = new byte[32];
            byte[] data1 = new byte[32];
            byte[] enc_data = new byte[32];
            byte[] mac = new byte[32];
            byte[] read_mac = new byte[32];

            byte[] page7SavedData = new byte[32];
            byte[] page8SavedData = new byte[32];
            byte[] page9SavedData = new byte[32];

            int result;
            int compareOK = 1;
            UInt16 startPage = 0x01;
            int num_pages_to_test = 1;
            int num_bytes_to_test = 32;

            ////////////////////////////

            byte[] notUsed = new byte[1];
            UInt16 zeroLen = 0;
            UInt16 len32 = 32;

            byte[] data3 = new byte[32];
            byte[] chk_mac = new byte[32];
            byte[] data4 = new byte[12];
            byte[] data5 = new byte[1];
            int i;
            int rslt;
            int rt = 1;
            int block;
            int skip_setup = 0;
            int page;
            int cnt;

            byte[] partial = new byte[32];
            byte[] new_page = new byte[32];
            int current_secret = 0;
            int cleared_byte;
            byte[] memimage = new byte[512];
            byte[] master_secret = new byte[32];
            byte[] binding = new byte[32];
            byte[] romid = new byte[8];
            byte[] manid = new byte[2];
            byte[] challenge = new byte[8];

            byte[] ITROMId = new byte[8];
            byte[] ITMANId = new byte[2];
            byte[] ITmaster_secret = new byte[32];
            byte[] ITpartial = new byte[32];
            byte[] ITbinding = new byte[32];

            string str;
            string strHex;

            String path = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
            path = path + "\\ADLINK";
            try
            {
                // Determine whether the directory exists.
                if (Directory.Exists(path))
                    Console.WriteLine("That path exists already.");
                else
                {
                    // Try to create the directory.
                    DirectoryInfo di = Directory.CreateDirectory(path);
                    Console.WriteLine("The directory was created successfully at {0}.", Directory.GetCreationTime(path));
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("The process failed: {0}", e.ToString());
            }
            finally { }

            // open log file and print time stamp
            path = path + "\\log8-2.txt";

            try
            {
                using (StreamWriter w = File.AppendText(path))
                {
                    //RandomNumbers.Seed((uint)time(null));

                    w.Write("num_bytes_to_test: ");
                    w.Write("{0}", num_bytes_to_test);

                    str = txtEditDcgetbuf5.Text; //data[32] + romid[8] + manid[2] + enc_data[32] + chk_mac[32] + challenge[8]


                    for (i = 0; i < 32; i++)
                    {
                        strHex = str.Substring((i * 2) + (0 * 2), 2);
                        data[i] = (byte)hex2uint(strHex);
                    }

                    for (i = 0; i < 8; i++)
                    {
                        strHex = str.Substring((i * 2) + (32 * 2), 2);
                        romid[i] = (byte)hex2uint(strHex);
                    }

                    for (i = 0; i < 2; i++)
                    {
                        strHex = str.Substring((i * 2) + (40 * 2), 2);
                        manid[i] = (byte)hex2uint(strHex);
                    }

                    for (i = 0; i < 32; i++)
                    {
                        strHex = str.Substring((i * 2) + (42 * 2), 2);
                        enc_data[i] = (byte)hex2uint(strHex);
                    }

                    for (i = 0; i < 32; i++)
                    {
                        strHex = str.Substring((i * 2) + (74 * 2), 2);
                        chk_mac[i] = (byte)hex2uint(strHex);
                    }

                    for (i = 0; i < 8; i++)
                    {
                        strHex = str.Substring((i * 2) + (106 * 2), 2);
                        challenge[i] = (byte)hex2uint(strHex);
                    }

                    w.Write("AD_EncryptAuthWritePageEnc_ex2, wCardNum {0}\r\n", wCardNum);
                    rslt = AD_License_management.AD_EncryptAuthWritePageEnc(wCardNum, (ushort)num_bytes_to_test, enc_data, data, romid, manid, chk_mac, challenge, 0);


                    w.Write("enc_data: ");
                    for (i = 0; i < num_bytes_to_test; i++)
                    {
                        w.Write("{0:X2}", enc_data[i]);
                    }
                    w.Write("\r\n");

                    w.Write("data: ");
                    for (i = 0; i < 32; i++)
                    {
                        w.Write("{0:X2}", data[i]);
                    }
                    w.Write("\r\n");

                    w.Write("romid: ");
                    for (i = 0; i < 8; i++)
                    {
                        w.Write("{0:X2}", romid[i]);
                    }
                    w.Write("\r\n");

                    w.Write("manid: ");
                    for (i = 0; i < 2; i++)
                    {
                        w.Write("{0:X2}", manid[i]);
                    }
                    w.Write("\r\n");

                    w.Write("chk_mac: ");
                    for (i = 0; i < 32; i++)
                    {
                        w.Write("{0:X2}", chk_mac[i]);
                    }
                    w.Write("\r\n");

                    w.Write("challenge: ");
                    for (i = 0; i < 8; i++)
                    {
                        w.Write("{0:X2}", challenge[i]);
                    }
                    w.Write("\r\n");


                    w.Write("AD_EncryptAuthWritePageEnc_ex2: ----------------------------------");
                    w.Write(" {0}\r\n", (rslt == 1) ? "FAIL" : "SUCCESS");
                    if (rslt == 1)
                    {
                        rt = 0;
                    }

                    w.Write("AD_EncryptReadSegment_ex2, wCardNum {0}\r\n", wCardNum);
                    rslt = AD_License_management.AD_EncryptReadSegment(wCardNum, data1, romid, manid, chk_mac, challenge);


                    w.Write("data1: ");
                    for (i = 0; i < 32; i++)
                    {
                        w.Write("{0:X2}", data1[i]);
                    }
                    w.Write("\r\n");

                    w.Write("romid: ");
                    for (i = 0; i < 8; i++)
                    {
                        w.Write("{0:X2}", romid[i]);
                    }
                    w.Write("\r\n");

                    w.Write("manid: ");
                    for (i = 0; i < 2; i++)
                    {
                        w.Write("{0:X2}", manid[i]);
                    }
                    w.Write("\r\n");


                    w.Write("AD_EncryptReadSegment_ex2:  ----------------------------------");
                    w.Write(" {0}\r\n", (rslt == 1) ? "FAIL" : "SUCCESS");
                    if (rslt == 1)
                    {
                        rt = 0;
                    }


                    if (rt == 1)
                    {
                        w.Write("Test Pass!");
                    }
                    else
                    {
                        w.Write("Test Fail!");
                    }
                }
            }
            catch 
            {
                MessageBox.Show("ERROR, Could not open LOT.TXT log file!\n");                
            }
        }

        private void btnButtonSet21_Click(object sender, EventArgs e)
        {
            UInt16 wCardNum = (ushort)m_Number;

            byte[] challenge = new byte[32];
            byte[] data = new byte[32];
            byte[] new_data = new byte[32];
            byte[] data1 = new byte[32];
            byte[] mac = new byte[32];

            byte[] page7SavedData = new byte[32];
            byte[] page8SavedData = new byte[32];
            byte[] page9SavedData = new byte[32];

            int result;
            int compareOK = 1;
            UInt16 startPage = 0x01;
            int num_pages_to_test = 1;
            int num_bytes_to_test = 32;

            ////////////////////////////

            Byte[] notUsed = new Byte[1];
            UInt16 zeroLen = 0;
            UInt16 len32 = 32;

            byte[] data3 = new byte[32];
            byte[] data4 = new byte[12];
            byte[] data5 = new byte[1];
            int i;
            int rslt;
            int rt = 1;
            int block;
            int skip_setup = 0;
            int page;
            int cnt;

            byte[] partial = new byte[32];
            byte[] new_page = new byte[32];
            int current_secret = 0;
            int cleared_byte;
            byte[] memimage = new byte[512];
            byte[] master_secret = new byte[32];
            byte[] binding = new byte[32];
            byte[] romid = new byte[8];
            byte[] manid = new byte[2];

            byte[] ITROMId = new byte[8];
            byte[] ITMANId = new byte[2];
            byte[] ITmaster_secret = new byte[32];
            byte[] ITpartial = new byte[32];
            byte[] ITbinding = new byte[32];

            string strHex;

            String path = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
            path = path + "\\ADLINK";
            try
            {
                // Determine whether the directory exists.
                if (Directory.Exists(path))
                    Console.WriteLine("That path exists already.");
                else
                {
                    // Try to create the directory.
                    DirectoryInfo di = Directory.CreateDirectory(path);
                    Console.WriteLine("The directory was created successfully at {0}.", Directory.GetCreationTime(path));
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("The process failed: {0}", e.ToString());
            } 
            finally { }

            // open log file and print time stamp
            path = path + "\\log6-0.txt";
            try
            {
                using (StreamWriter w = File.AppendText(path))
                {
                    //RandomNumbers.Seed((uint)time(null));

                    for (i = 0; i < 32; i++)
                    {
                        strHex = txtEditDcsetbuf[i].Text;
                        master_secret[i] = (byte)hex2uint(strHex);
                    }

                    w.Write("master_secret: ");
                    for (i = 0; i < 32; i++)
                    {
                        w.Write("{0:X2}", master_secret[i]);
                    }
                    w.Write("\r\n");

                    //MessageBox("The Card will InstallSecret!!!");

                    var msgtmp = MessageBox.Show("The Card will InstallSecret!!!", "InstallSecret", MessageBoxButtons.YesNo, MessageBoxIcon.Question);
                    if (msgtmp == DialogResult.Yes)
                    {
                        w.Write("AD_SetMasterSecret, wCardNum {0}\r\n", wCardNum);
                        rslt = AD_License_management.AD_InstallSecret(wCardNum, master_secret, false);

                        w.Write(" {0}\r\n", (rslt) != 0 ? "FAIL" : "SUCCESS");
                        if (rslt != 0)
                        {
                            rt = 0;
                        }

                        if (rt == 1)
                        {
                            w.Write("Test Pass!");
                        }
                        else
                        {
                            w.Write("Test Fail!");
                        }
                    }
                    else
                    {
                        w.Write("Test Cancel");
                    }
                }
            }
            catch
            {
                MessageBox.Show("ERROR, Could not open LOT.TXT log file!\n");

            }
        }

        private void btnButtonSet18_Click(object sender, EventArgs e)
        {
            UInt16 wCardNum = (ushort)m_Number;

            byte[] challenge = new byte[32];
            byte[] data = new byte[32];
            byte[] new_data = new byte[32];
            byte[] data1 = new byte[32];
            byte[] mac = new byte[32];

            byte[] page7SavedData = new byte[32];
            byte[] page8SavedData = new byte[32];
            byte[] page9SavedData = new byte[32];

            int result;
            int compareOK = 1;
            UInt16 startPage = 0x01;
            int num_pages_to_test = 1;
            int num_bytes_to_test = 32;

            ////////////////////////////

            byte[] notUsed = new byte[1];
            UInt16 zeroLen = 0;
            UInt16 len32 = 32;

            byte[] data3 = new byte[32];
            byte[] data4 = new byte[12];
            byte[] data5 = new byte[1];
            int i;
            int rslt;
            int rt = 1;
            int block;
            int skip_setup = 0;
            int page;
            int cnt;

            byte[] partial = new byte[32];
            byte[] new_page = new byte[32];
            int current_secret = 0;
            int cleared_byte;
            byte[] memimage = new byte[512];
            byte[] master_secret = new byte[32];
            byte[] binding = new byte[32];
            byte[] romid = new byte[8];
            byte[] manid = new byte[2];

            byte[] ITROMId = new byte[8];
            byte[] ITMANId = new byte[2];
            byte[] ITmaster_secret = new byte[32];
            byte[] ITpartial = new byte[32];
            byte[] ITbinding = new byte[32];

            string strHex;

            String path = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
            path = path + "\\ADLINK";
            try
            {
                // Determine whether the directory exists.
                if (Directory.Exists(path))
                    Console.WriteLine("That path exists already.");
                else
                {
                    // Try to create the directory.
                    DirectoryInfo di = Directory.CreateDirectory(path);
                    Console.WriteLine("The directory was created successfully at {0}.", Directory.GetCreationTime(path));
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("The process failed: {0}", e.ToString());
            }
            finally { }

            // open log file and print time stamp			
            path = path + "\\log6-1.txt";			
            try
            {
                using (StreamWriter w = File.AppendText(path))
                {
                    //RandomNumbers.Seed((uint)time(null));
                    for (i = 0; i < 32; i++)
                    {
                        strHex = txtEditDcsetbuf[i].Text;
                        master_secret[i] = (byte)hex2uint(strHex);
                    }

                    w.Write("master_secret: ");
                    for (i = 0; i < 32; i++)
                    {
                        w.Write("{0:X2}", master_secret[i]);
                    }
                    w.Write("\r\n");

                    w.Write("AD_SetMasterSecret, wCardNum {0}\r\n", wCardNum);
                    rslt = AD_License_management.AD_SetMasterSecret(wCardNum, master_secret);

                    w.Write(" {0}\r\n", (rslt) != 0 ? "FAIL" : "SUCCESS");
                    if (rslt != 0)
                    {
                        rt = 0;
                    }


                    if (rt == 1)
                    {
                        w.Write("Test Pass!");
                    }
                    else
                    {
                        w.Write("Test Fail!");
                    }
                }
            }
            catch
            {
                MessageBox.Show("ERROR, Could not open LOT.TXT log file!\n");

            }
        }
    }
}
