
'This code has been automatically generated by DudeLabs LLC RCConverter
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Drawing
Imports System.Text
Imports System.Windows.Forms
Imports System.IO
Imports System.Runtime.InteropServices

''' <summary>
''' Summary description for FrmSamrtpoesampleDialog.
''' </summary>
Public Partial Class FrmSamrtpoesampleDialog
	Inherits System.Windows.Forms.Form
	<DllImport("msvcrt.dll")> _
	Public Shared Function srand(seed As Integer) As Integer
	End Function


	Public Sub New()
		'
		' Required for Windows Form Designer support
		'
		InitializeComponent()
		m_Number = -1
		'
		' TODO: Add any constructor code after InitializeComponent call
		'
		'RadioButton [] RadioBtnOn, RadioBtnOff;


		RadioBtnOn(0) = rdoRadio1On1
		RadioBtnOn(1) = rdoRadio1On2
		RadioBtnOn(2) = rdoRadio1On3
		RadioBtnOn(3) = rdoRadio1On4
		RadioBtnOn(4) = rdoRadio1On5
		RadioBtnOn(5) = rdoRadio1On6
		RadioBtnOn(6) = rdoRadio1On7
		RadioBtnOn(7) = rdoRadio1On8
		RadioBtnOn(8) = rdoRadio1On9
		RadioBtnOn(9) = rdoRadio1On10
		RadioBtnOn(10) = rdoRadio1On11
		RadioBtnOn(11) = rdoRadio1On12
		RadioBtnOn(12) = rdoRadio1On13
		RadioBtnOn(13) = rdoRadio1On14
		RadioBtnOn(14) = rdoRadio1On15
		RadioBtnOn(15) = rdoRadio1On16

		RadioBtnOff(0) = rdoRadio1Off1
		RadioBtnOff(1) = rdoRadio1Off2
		RadioBtnOff(2) = rdoRadio1Off3
		RadioBtnOff(3) = rdoRadio1Off4
		RadioBtnOff(4) = rdoRadio1Off5
		RadioBtnOff(5) = rdoRadio1Off6
		RadioBtnOff(6) = rdoRadio1Off7
		RadioBtnOff(7) = rdoRadio1Off8
		RadioBtnOff(8) = rdoRadio1Off9
		RadioBtnOff(9) = rdoRadio1Off10
		RadioBtnOff(10) = rdoRadio1Off11
		RadioBtnOff(11) = rdoRadio1Off12
		RadioBtnOff(12) = rdoRadio1Off13
		RadioBtnOff(13) = rdoRadio1Off14
		RadioBtnOff(14) = rdoRadio1Off15
		RadioBtnOff(15) = rdoRadio1Off16


		txtEditDcsetbuf(0) = txtEditDcsetbuf0
		txtEditDcsetbuf(1) = txtEditDcsetbuf1
		txtEditDcsetbuf(2) = txtEditDcsetbuf2
		txtEditDcsetbuf(3) = txtEditDcsetbuf3
		txtEditDcsetbuf(4) = txtEditDcsetbuf4
		txtEditDcsetbuf(5) = txtEditDcsetbuf5
		txtEditDcsetbuf(6) = txtEditDcsetbuf6
		txtEditDcsetbuf(7) = txtEditDcsetbuf7
		txtEditDcsetbuf(8) = txtEditDcsetbuf8
		txtEditDcsetbuf(9) = txtEditDcsetbuf9
		txtEditDcsetbuf(10) = txtEditDcsetbuf10
		txtEditDcsetbuf(11) = txtEditDcsetbuf11
		txtEditDcsetbuf(12) = txtEditDcsetbuf12
		txtEditDcsetbuf(13) = txtEditDcsetbuf13
		txtEditDcsetbuf(14) = txtEditDcsetbuf14
		txtEditDcsetbuf(15) = txtEditDcsetbuf15
		txtEditDcsetbuf(16) = txtEditDcsetbuf16
		txtEditDcsetbuf(17) = txtEditDcsetbuf17
		txtEditDcsetbuf(18) = txtEditDcsetbuf18
		txtEditDcsetbuf(19) = txtEditDcsetbuf19
		txtEditDcsetbuf(20) = txtEditDcsetbuf20
		txtEditDcsetbuf(21) = txtEditDcsetbuf21
		txtEditDcsetbuf(22) = txtEditDcsetbuf22
		txtEditDcsetbuf(23) = txtEditDcsetbuf23
		txtEditDcsetbuf(24) = txtEditDcsetbuf24
		txtEditDcsetbuf(25) = txtEditDcsetbuf25
		txtEditDcsetbuf(26) = txtEditDcsetbuf26
		txtEditDcsetbuf(27) = txtEditDcsetbuf27
		txtEditDcsetbuf(28) = txtEditDcsetbuf28
		txtEditDcsetbuf(29) = txtEditDcsetbuf29
		txtEditDcsetbuf(30) = txtEditDcsetbuf30

		txtEditDcsetbuf(31) = txtEditDcsetbuf31
	End Sub

    Private Sub btnButtonSet4_Click(ByVal sender As Object, ByVal e As EventArgs) Handles btnButtonSet4.Click
        'SetDlgItemText(IDC_EDIT_ERROR, "");
        txtEditError.Text = ""
    End Sub


	Public Property m_Number() As Short
		Get
			Return m_m_Number
		End Get
		Set
			m_m_Number = Value
		End Set
	End Property
	Private m_m_Number As Short
	Public RadioBtnOn As RadioButton() = New RadioButton(15) {}
	Public RadioBtnOff As RadioButton() = New RadioButton(15) {}


    Private Sub cboComboCardNumber_SelectedIndexChanged(ByVal sender As Object, ByVal e As EventArgs) Handles cboComboCardNumber.SelectedIndexChanged
        Dim Number As Int16
        Dim card_num As UInt16 = CType(cboComboCardNumber.SelectedIndex, UInt16)
        '(U16)((CComboBox*)GetDlgItem(IDC_COMBO_CARD_NUMBER))->GetCurSel();


        If m_Number >= 0 Then
            SmartPoE.Release_Card(CUShort(m_Number))
        End If

        If (InlineAssignHelper(Number, SmartPoE.Register_Card(card_num))) <> SmartPoE.PoE_NoError Then
            MessageBox.Show("Selecting card is failed")
            Return
        End If

        Dim ID As UInt16
        Dim ret As Int16 = SmartPoE.Get_ID(CType(Number, UInt16), ID)
        If ret < 0 Then
            txtEditError.Text = "Error"
        Else
            txtEditId.Text = ID.ToString()
        End If


        m_Number = Number

        '''//////////////////////////

        ret = SmartPoE.Get_Chk_EEVersion(CType(Number, UInt16), ID)
        If ret < 0 Then
            txtEditError.Text = "Error"
        Else
            txtEditId14.Text = ID.ToString()
        End If


        ret = SmartPoE.Get_Chk_EEStandard(CType(Number, UInt16), ID)
        If ret < 0 Then
            txtEditError.Text = "Error"
        Else
            txtEditId15.Text = ID.ToString()
        End If

        ret = SmartPoE.Get_Chk_EEPort(CType(Number, UInt16), ID)
        If ret < 0 Then
            txtEditError.Text = "Error"
        Else
            txtEditId16.Text = ID.ToString()
        End If

        Dim ID2 As UInt32, ID3 As UInt32
        ret = SmartPoE.Get_CPLDVersion(CType(Number, UInt16), ID2, ID3)
        If ret < 0 Then
            txtEditError.Text = "Error"
        Else
            txtEditId18.Text = [String].Format("{0:x}", ID2)
            txtEditId19.Text = [String].Format("{0:x}", ID3)
        End If

        Dim MCUID As UInt16
        ret = SmartPoE.Get_MCUVersion(CType(Number, UInt16), MCUID)
        If ret < 0 Then
            txtEditId20.Text = "Error"
        Else
            txtEditId20.Text = [String].Format("{0:x}", MCUID)
        End If


        'Get_MCUVersion


        '''//////////////////////////

    End Sub

    Private Sub FrmSamrtpoesampleDialog_Load(ByVal sender As Object, ByVal e As EventArgs) Handles MyBase.Load
        ' Set the icon for this dialog.  The framework does this automatically
        '  when the application's main window is not a dialog


        'TBD
        'SetIcon(m_hIcon, TRUE);			// Set big icon
        'SetIcon(m_hIcon, FALSE);		// Set small icon

        Dim i As UInt16
        'CString str;
        Dim num As Short

        For i = 0 To SmartPoE.MAX_CARD - 1
            If (InlineAssignHelper(num, SmartPoE.Register_Card(i))) <> SmartPoE.PoE_NoError Then
                Exit For
            End If

            SmartPoE.Release_Card(CType(num, UInt16))
            cboComboCardNumber.Items.Add([String].Format("{0:d}", i))
        Next

        If i = 0 Then
            MessageBox.Show("No card is found!")
            Return
        End If

        cboComboCardNumber.SelectedIndex = 0
        cboComboCardNumber_SelectedIndexChanged(sender, e)


        'cannot find these 5 items
        'SetDlgItemText(IDC_EDIT_DCSET4, "00");           
        'SetDlgItemText(IDC_EDIT_DCSET0, "55");            
        '_itoa_s(0, txt, sizeof(txt), 10);
        'SetDlgItemText(IDC_EDIT_DCSET1, txt);            
        '_itoa_s(4, txt, sizeof(txt), 10);
        'SetDlgItemText(IDC_EDIT_DCSET2, txt);
        '_itoa_s(10, txt, sizeof(txt), 10);
        'SetDlgItemText(IDC_EDIT_DCSET3, txt);






        rdoRadio1Off1.Checked = True
        rdoRadio1Off2.Checked = True
        rdoRadio1Off3.Checked = True
        rdoRadio1Off4.Checked = True
        rdoRadio1Off5.Checked = True
        rdoRadio1Off6.Checked = True
        rdoRadio1Off7.Checked = True
        rdoRadio1Off8.Checked = True
        rdoRadio1Off9.Checked = True
        rdoRadio1Off10.Checked = True
        rdoRadio1Off11.Checked = True
        rdoRadio1Off12.Checked = True
        rdoRadio1Off13.Checked = True
        rdoRadio1Off14.Checked = True
        rdoRadio1Off15.Checked = True
        rdoRadio1Off16.Checked = True

        rdoRadio1On1.Checked = False
        rdoRadio1On2.Checked = False
        rdoRadio1On3.Checked = False
        rdoRadio1On4.Checked = False
        rdoRadio1On5.Checked = False
        rdoRadio1On6.Checked = False
        rdoRadio1On7.Checked = False
        rdoRadio1On8.Checked = False
        rdoRadio1On9.Checked = False
        rdoRadio1On10.Checked = False
        rdoRadio1On11.Checked = False
        rdoRadio1On12.Checked = False
        rdoRadio1On13.Checked = False
        rdoRadio1On14.Checked = False
        rdoRadio1On15.Checked = False
        rdoRadio1On16.Checked = False


        txtEditDcgetbuf0.Text = "00000000000000000000000000000000"


        'cannot find these items
        For i = 0 To 31
            txtEditDcsetbuf(i).Text = String.Format("{0:X}", i)
        Next

        'txtEditDcsetbuf[0].Text = "00";

        'txtEditDcgetbuf3.Text = "0";



        'srand(CInt(DateTime.Now.ToBinary()))
        'return true;  // return TRUE  unless you set the focus to a control
    End Sub
	Public txtEditDcsetbuf As System.Windows.Forms.TextBox() = New System.Windows.Forms.TextBox(31) {}
    Private Sub btnButtonSet32_Click(ByVal sender As Object, ByVal e As EventArgs) Handles btnButtonSet32.Click
        Dim bitstatus As Byte
        Dim lockstatus As Byte
        Dim wCardNum As UInt16 = CType(m_Number, System.UInt16)
        Dim err As Integer

        err = AD_License_management.AD_ReadInstallSecretStatus(wCardNum, bitstatus, lockstatus)

        ' bitsatus = 0 (Non-burned card)
        ' bitsatus = 1 (Burned card)
        ' bitsatus = 2 (Burned card and data locked)
        ' lockstatus = 0 (Secret non-locked)
        ' lockstatus = 1 (Secret locked)

        MessageBox.Show("Card Status:" + bitstatus.ToString() + "," + "Secret Status" + lockstatus.ToString())
    End Sub

    Private Sub btnButtonSet29_Click(ByVal sender As Object, ByVal e As EventArgs) Handles btnButtonSet29.Click

        Dim wCardNum As UInt16 = CUShort(m_Number)
        Dim str As String
        Dim str2 As String
        Dim str3 As String
        Dim str4 As String

        '  byte challenge[32];
        Dim data As Byte() = New Byte(31) {}
        Dim new_data As Byte() = New Byte(31) {}
        Dim data1 As Byte() = New Byte(31) {}
        Dim mac As Byte() = New Byte(31) {}
        Dim read_mac As Byte() = New Byte(31) {}

        Dim page7SavedData As Byte() = New Byte(31) {}
        Dim page8SavedData As Byte() = New Byte(31) {}
        Dim page9SavedData As Byte() = New Byte(31) {}

        Dim result As Integer
        Dim compareOK As Integer = 1
        'UInt16 startPage = 0x07;     
        Dim startPage As UInt16 = &H1
        Dim num_pages_to_test As Integer = 1
        Dim num_bytes_to_test As Integer = 32

        '''/////////////////////////

        Dim notUsed As Byte() = New Byte(0) {}
        Dim zeroLen As UInt16 = 0
        Dim len32 As UInt16 = 32

        Dim data3 As Byte() = New Byte(31) {}
        Dim data4 As Byte() = New Byte(11) {}
        Dim data5 As Byte() = New Byte(0) {}
        Dim i As Integer
        Dim rslt As Integer
        Dim rt As Integer = 1
        Dim block As Integer
        Dim skip_setup As Integer = 0
        Dim page As Integer
        Dim cnt As Integer

        Dim [partial] As Byte() = New Byte(31) {}
        Dim new_page As Byte() = New Byte(31) {}
        Dim current_secret As Integer = 0
        Dim cleared_byte As Integer
        Dim memimage As Byte() = New Byte(511) {}
        Dim master_secret As Byte() = New Byte(31) {}
        Dim binding As Byte() = New Byte(31) {}
        Dim romid As Byte() = New Byte(7) {}
        Dim manid As Byte() = New Byte(1) {}
        Dim challenge As Byte() = New Byte(7) {}

        Dim ITROMId As Byte() = New Byte(7) {}
        Dim ITMANId As Byte() = New Byte(1) {}
        Dim ITmaster_secret As Byte() = New Byte(31) {}
        Dim ITpartial As Byte() = New Byte(31) {}
        Dim ITbinding As Byte() = New Byte(31) {}

        Dim TempUserPath As String = My.Computer.FileSystem.SpecialDirectories.MyDocuments
        TempUserPath = TempUserPath + "//ADLINK"

        Try
            ' Determine whether the directory exists.
            If Directory.Exists(TempUserPath) Then
            Else
                ' Try to create the directory.
                Dim di As DirectoryInfo = Directory.CreateDirectory(TempUserPath)
            End If

        Catch ex As Exception
            Console.WriteLine("The process failed: {0}.", e.ToString())
        End Try

        ' open log file and print time stamp
        TempUserPath = TempUserPath + "//log8-2.txt"
        Try
            Using w As StreamWriter = File.AppendText(TempUserPath)
                'RandomNumbers.Seed((uint)time(null));
                w.WriteLine("AD_EncryptReadSegment_ex2, wCardNum {0}", wCardNum)
                rslt = AD_License_management.AD_EncryptReadSegment(wCardNum, data, romid, manid, read_mac, challenge)

                w.Write("data: ")
                For i = 0 To 31
                    w.Write("{0:X2}", data(i))
                Next
                w.WriteLine("")

                w.Write("romid: ")
                For i = 0 To 7
                    w.Write("{0:X2}", romid(i))
                Next
                w.WriteLine("")

                w.Write("manid: ")
                For i = 0 To 1
                    w.Write("{0:X2}", manid(i))
                Next
                w.WriteLine("")

                w.Write("read_mac: ")
                For i = 0 To 31
                    w.Write("{0:X2}", read_mac(i))
                Next
                w.WriteLine("")

                w.Write("challenge: ")
                For i = 0 To 7
                    w.Write("{0:X2}", challenge(i))
                Next
                w.WriteLine("")


                'For i = 0 To 15


                '    '((CButton)GetDlgItem(IDC_RADIO1_ON1 + (i * 2))).SetCheck(data[i] == 0x71 + i != 0 ? 1 : 0);
                '    '((CButton)GetDlgItem(IDC_RADIO1_OFF1 + (i * 2))).SetCheck(data[i] == 0x61 + i != 0 ? 1 : 0);

                '    'TBD check data[i] == 0x71 + i != 0
                '    RadioBtnOn(i).Checked = (If(data(i) = &H71, True, False))
                '    RadioBtnOff(i).Checked = (If(data(i) = &H61, True, False))
                'Next

                str = ""
                'data[32] + romid[8] + manid[2] + read_mac[32] + challenge[8]
                For i = 0 To 31
                    str += [String].Format("{0:X2}", data(i))
                Next
                txtEditDcgetbuf0.Text = str

                For i = 0 To 7
                    str += [String].Format("{0:X2}", romid(i))
                Next
                For i = 0 To 1
                    str += [String].Format("{0:X2}", manid(i))
                Next

                For i = 0 To 31
                    str += [String].Format("{0:X2}", read_mac(i))
                Next

                For i = 0 To 7
                    str += [String].Format("{0:X2}", challenge(i))
                Next
                txtEditDcgetbuf6.Text = str


                w.Write("AD_EncryptReadSegment:  ----------------------------------")
                w.Write("{0}" & vbCr & vbLf, If((rslt) <> 0, "FAIL", "SUCCESS"))
                If rslt <> 0 Then
                    rt = 0
                End If


                If rt = 1 Then
                    w.Write("Test Pass!")
                Else
                    w.Write("Test Fail!")
                End If
            End Using
        Catch
            MessageBox.Show("ERROR, Could not open LOT.TXT log file!" & vbLf)
        End Try
    End Sub

    Private Sub btnButtonSet33_Click(ByVal sender As Object, ByVal e As EventArgs) Handles btnButtonSet33.Click
        ' TODO: ?®Ê≠§?†ÂÖ•?ßÂà∂?ÖÂ??•Ë??ÜÂ∏∏ÂºèÁ?ÂºèÁ¢º
        Dim wCardNum As UInt16 = CUShort(m_Number)

        Dim str As String
        Dim str2 As String
        Dim str3 As String
        Dim str4 As String
        Dim challenge As Byte() = New Byte(31) {}
        Dim data As Byte() = New Byte(31) {}
        Dim new_data As Byte() = New Byte(31) {}
        Dim data1 As Byte() = New Byte(31) {}
        Dim enc_data As Byte() = New Byte(31) {}
        Dim chk_mac As Byte() = New Byte(31) {}
        Dim mac As Byte() = New Byte(31) {}
        Dim read_mac As Byte() = New Byte(31) {}

        Dim page7SavedData As Byte() = New Byte(31) {}
        Dim page8SavedData As Byte() = New Byte(31) {}
        Dim page9SavedData As Byte() = New Byte(31) {}

        Dim result As Integer
        Dim compareOK As Integer = 1
        'UInt16 startPage = 0x07;     
        Dim startPage As UInt16 = &H1
        Dim num_pages_to_test As Integer = 1
        Dim num_bytes_to_test As Integer = 32

        '''/////////////////////////

        Dim notUsed As Byte() = New Byte(0) {}
        Dim zeroLen As UInt16 = 0
        Dim len32 As UInt16 = 32

        Dim data3 As Byte() = New Byte(31) {}
        Dim data4 As Byte() = New Byte(11) {}
        Dim data5 As Byte() = New Byte(0) {}
        Dim i As Integer
        Dim rslt As Integer = 0
        Dim rt As Integer = 1
        Dim block As Integer
        Dim skip_setup As Integer = 0
        Dim page As Integer
        Dim cnt As Integer

        Dim [partial] As Byte() = New Byte(31) {}
        Dim new_page As Byte() = New Byte(31) {}
        Dim current_secret As Integer = 0
        Dim cleared_byte As Integer
        Dim memimage As Byte() = New Byte(511) {}
        Dim master_secret As Byte() = New Byte(31) {}
        Dim binding As Byte() = New Byte(31) {}
        Dim romid As Byte() = New Byte(7) {}
        Dim manid As Byte() = New Byte(1) {}


        'UCHAR   ITROMId[8];
        'UCHAR   ITMANId[2];
        'UCHAR   ITmaster_secret[32];
        'UCHAR   ITpartial[32];
        'UCHAR   ITbinding[32];

        Dim strHex As String

        Dim TempUserPath As String = My.Computer.FileSystem.SpecialDirectories.MyDocuments
        TempUserPath = TempUserPath + "//ADLINK"

        Try
            ' Determine whether the directory exists.
            If Directory.Exists(TempUserPath) Then
            Else
                ' Try to create the directory.
                Dim di As DirectoryInfo = Directory.CreateDirectory(TempUserPath)
            End If

        Catch ex As Exception
            Console.WriteLine("The process failed: {0}.", e.ToString())
        End Try

        ' open log file and print time stamp            
        TempUserPath = TempUserPath + "//log8-6.txt"
        Try
            Using w As StreamWriter = File.AppendText(TempUserPath)
                'RandomNumbers.Seed((uint)time(null));
                w.Write("num_bytes_to_test: ")
                w.Write("{0}", num_bytes_to_test)

                'GetDlgItemText(IDC_EDIT_DCGETBUF6, str); //data[32] + romid[8] + manid[2] + read_mac[32];
                str = txtEditDcgetbuf6.Text

                For i = 0 To 31

                    strHex = str.Substring((i * 2) + (0 * 2), 1)
                    strHex = strHex & str.Substring((i * 2) + 1 + (0 * 2), 1)
                    data(i) = CByte(hex2uint(strHex))
                Next

                For i = 0 To 7
                    strHex = str.Substring((i * 2) + (32 * 2), 2)
                    romid(i) = CByte(hex2uint(strHex))
                Next

                For i = 0 To 1
                    strHex = str.Substring((i * 2) + (40 * 2), 2)
                    manid(i) = CByte(hex2uint(strHex))
                Next

                For i = 0 To 31
                    strHex = str.Substring((i * 2) + (42 * 2), 2)
                    read_mac(i) = CByte(hex2uint(strHex))
                Next


                For i = 0 To 15
                    '((CButton)GetDlgItem(IDC_RADIO1_ON1 + (i * 2))).SetCheck(data[i] == 0x71 + i != 0 ? 1 : 0);
                    '((CButton)GetDlgItem(IDC_RADIO1_OFF1 + (i * 2))).SetCheck(data[i] == 0x61 + i != 0 ? 1 : 0);
                    RadioBtnOn(i).Checked = If((data(i) = &H71 + i <> False), True, False)
                    RadioBtnOff(i).Checked = If((data(i) = &H61 + i <> False), True, False)
                Next

                w.Write("data: ")
                For i = 0 To 31
                    w.Write("{0:X2}", data(i))
                Next
                w.Write(vbCr & vbLf)

                w.Write("romid: ")
                For i = 0 To 7
                    w.Write("{0:X2}", romid(i))
                Next
                w.Write(vbCr & vbLf)

                w.Write("manid: ")
                For i = 0 To 1
                    w.Write("{0:X2}", manid(i))
                Next
                w.Write(vbCr & vbLf)

                w.Write("data: ")
                For i = 0 To 31
                    w.Write("{0:X2}", read_mac(i))
                Next
                w.Write(vbLf)

                w.Write("Check ON/OFF: ----------------------------------")
                w.Write(" {0}" & vbCr & vbLf, If((rslt) <> 0, "FAIL", "SUCCESS"))
                If rslt <> 0 Then
                    rt = 0
                End If

                If rt = 1 Then
                    w.Write("Test Pass!")
                Else
                    w.Write("Test Fail!")
                End If
            End Using
        Catch
            MessageBox.Show("ERROR, Could not open LOT.TXT log file!" & vbLf)
        End Try
    End Sub

	Private Function hex2uint(h As String) As UInteger
		Dim len As Integer
		Dim str As String
		Dim ret As UInteger = 0
		Dim c As SByte

		len = h.Length
		If len > 16 OrElse len <= 0 Then
			Return 0
		End If

		h.ToUpper()
		'str = h.GetBuffer(10); 
		str = h

		For i As Integer = 0 To len - 1
			c = CSByte(AscW(str(i)))
            If c >= Asc("0") AndAlso c <= Asc("9") Then
                ret = CUInt((ret << 4) + c - Asc("0"))
            ElseIf c >= Asc("A") AndAlso c <= Asc("F") Then
                ret = CUInt((ret << 4) + c - Asc("A") + 10)
            Else
                Return 0
            End If
		Next

		Return ret
	End Function

    Private Sub btnButtonSet31_Click(ByVal sender As Object, ByVal e As EventArgs) Handles btnButtonSet31.Click
        ' TODO: ?®Ê≠§?†ÂÖ•?ßÂà∂?ÖÂ??•Ë??ÜÂ∏∏ÂºèÁ?ÂºèÁ¢º
        Dim wCardNum As UInt16 = CUShort(m_Number)

        Dim str As String
        Dim str2 As String
        Dim str3 As String
        Dim str4 As String
        Dim data As Byte() = New Byte(31) {}
        Dim new_data As Byte() = New Byte(31) {}
        Dim data1 As Byte() = New Byte(31) {}
        Dim enc_data As Byte() = New Byte(31) {}
        Dim chk_mac As Byte() = New Byte(31) {}
        Dim mac As Byte() = New Byte(31) {}
        Dim read_mac As Byte() = New Byte(31) {}

        Dim page7SavedData As Byte() = New Byte(31) {}
        Dim page8SavedData As Byte() = New Byte(31) {}
        Dim page9SavedData As Byte() = New Byte(31) {}

        Dim result As Integer
        Dim compareOK As Integer = 1
        Dim startPage As UInt16 = &H1
        Dim num_pages_to_test As Integer = 1
        Dim num_bytes_to_test As Integer = 32

        '''/////////////////////////

        Dim notUsed As Byte() = New Byte(0) {}
        Dim zeroLen As UInt16 = 0
        Dim len32 As UInt16 = 32

        Dim data3 As Byte() = New Byte(31) {}
        Dim data4 As Byte() = New Byte(11) {}
        Dim data5 As Byte() = New Byte(0) {}
        Dim i As Integer
        Dim rslt As Integer
        Dim rt As Integer = 1
        Dim block As Integer
        Dim skip_setup As Integer = 0
        Dim page As Integer
        Dim cnt As Integer

        Dim [partial] As Byte() = New Byte(31) {}
        Dim new_page As Byte() = New Byte(31) {}
        Dim current_secret As Integer = 0
        Dim cleared_byte As Integer
        Dim memimage As Byte() = New Byte(511) {}
        Dim master_secret As Byte() = New Byte(31) {}
        Dim binding As Byte() = New Byte(31) {}
        Dim romid As Byte() = New Byte(7) {}
        Dim manid As Byte() = New Byte(1) {}
        Dim challenge As Byte() = New Byte(7) {}

        Dim ITROMId As Byte() = New Byte(7) {}
        Dim ITMANId As Byte() = New Byte(1) {}
        Dim ITmaster_secret As Byte() = New Byte(31) {}
        Dim ITpartial As Byte() = New Byte(31) {}
        Dim ITbinding As Byte() = New Byte(31) {}

        Dim strHex As String

        Dim TempUserPath As String = My.Computer.FileSystem.SpecialDirectories.MyDocuments
        TempUserPath = TempUserPath + "//ADLINK"

        Try
            ' Determine whether the directory exists.
            If Directory.Exists(TempUserPath) Then
            Else
                ' Try to create the directory.
                Dim di As DirectoryInfo = Directory.CreateDirectory(TempUserPath)
            End If

        Catch ex As Exception
            Console.WriteLine("The process failed: {0}.", e.ToString())
        End Try

        ' open log file and print time stamp            
        TempUserPath = TempUserPath + "//log8-4.txt"
        Try
            Using w As StreamWriter = File.AppendText(TempUserPath)
                'RandomNumbers.Seed((uint)time(null));
                w.Write("num_bytes_to_test: ")
                w.Write("{0}", num_bytes_to_test)

                str = txtEditDcgetbuf6.Text
                For i = 0 To 31
                    'strHex = str[(i * 2) + (0 * 2)];
                    'strHex = strHex + str[(i * 2) + 1 + (0 * 2)];
                    strHex = str.Substring((i * 2) + (0 * 2), 2)
                    data(i) = CByte(hex2uint(strHex))
                Next

                For i = 0 To 7
                    'strHex = str[(i * 2) + (32 * 2)];
                    'strHex = strHex + str[(i * 2) + 1 + (32 * 2)];
                    strHex = str.Substring((i * 2) + (32 * 2), 2)
                    romid(i) = CByte(hex2uint(strHex))
                Next

                For i = 0 To 1
                    'strHex = str[(i * 2) + (40 * 2)];
                    'strHex = strHex + str[(i * 2) + 1 + (40 * 2)];
                    strHex = str.Substring((i * 2) + (40 * 2), 2)
                    manid(i) = CByte(hex2uint(strHex))
                Next

                For i = 0 To 31
                    'strHex = str[(i * 2) + (42 * 2)];
                    'strHex = strHex + str[(i * 2) + 1 + (42 * 2)];
                    strHex = str.Substring((i * 2) + (42 * 2), 2)
                    read_mac(i) = CByte(hex2uint(strHex))
                Next

                For i = 0 To 7
                    'strHex = str[(i * 2) + (74 * 2)];
                    'strHex = strHex + str[(i * 2) + 1 + (74 * 2)];
                    strHex = str.Substring((i * 2) + (74 * 2), 2)
                    challenge(i) = CByte(hex2uint(strHex))
                Next

                For i = 0 To 15
                    'new_data[i] = (byte)((CButton)GetDlgItem(IDC_RADIO1_ON1 + (i * 2))).GetCheck() ? 0x71 + i : 0x61 + i;
                    new_data(i) = CByte(If(RadioBtnOn(i).Checked, &H71 + i, &H61 + i))
                Next

                For i = 16 To 31
                    new_data(i) = CByte(0)
                Next

                w.Write("AD_EncryptComputeEnc_ex2, wCardNum {0}" & vbCr & vbLf, wCardNum)
                rslt = AD_License_management.AD_EncryptComputeEnc(wCardNum, new_data, romid, manid, read_mac, challenge, _
                 enc_data, chk_mac)

                w.Write("enc_data: ")
                For i = 0 To num_bytes_to_test - 1
                    w.Write("{0:X2}", enc_data(i))
                Next
                w.Write(vbCr & vbLf)

                w.Write("chk_mac: ")
                For i = 0 To num_bytes_to_test - 1
                    w.Write("{0:X2}", chk_mac(i))
                Next
                w.Write(vbCr & vbLf)

                w.Write("data: ")
                For i = 0 To 31
                    w.Write("{0:X2}", data(i))
                Next
                w.Write(vbCr & vbLf)

                w.Write("romid: ")
                For i = 0 To 7
                    w.Write("{0:X2}", romid(i))
                Next
                w.Write(vbCr & vbLf)

                w.Write("manid: ")
                For i = 0 To 1
                    w.Write("{0:X2}", manid(i))
                Next
                w.Write(vbCr & vbLf)

                w.Write("read_mac: ")
                For i = 0 To 31
                    w.Write("{0:X2}", read_mac(i))
                Next
                w.Write(vbCr & vbLf)

                w.Write("challenge: ")
                For i = 0 To 7
                    w.Write("{0:X2}", challenge(i))
                Next
                w.Write(vbCr & vbLf)


                str = ""
                'data[32] + romid[8] + manid[2] + enc_data[32] + chk_mac[32] + challenge[8]
                For i = 0 To 31
                    str += String.Format("{0:X2}", data(i))
                Next
                txtEditDcgetbuf0.Text = str

                For i = 0 To 7
                    str += String.Format("{0:X2}", romid(i))
                Next

                For i = 0 To 1
                    str += String.Format("{0:X2}", manid(i))
                Next

                For i = 0 To 31
                    str += String.Format("{0:X2}", enc_data(i))
                Next

                For i = 0 To 31
                    str += String.Format("{0:X2}", chk_mac(i))
                Next

                For i = 0 To 7
                    str += String.Format("{0:X2}", challenge(i))
                Next
                txtEditDcgetbuf5.Text = str
                'data[32] + romid[8] + manid[2] + enc_data[32] + chk_mac[32] + challenge[8]\                    

                w.Write("AD_EncryptComputeEnc_ex2: ----------------------------------")
                w.Write(" {0}" & vbCr & vbLf, If((rslt = 1), "FAIL", "SUCCESS"))
                If rslt = 1 Then
                    rt = 0
                End If

                If rt = 1 Then
                    w.Write("Test Pass!")
                Else
                    w.Write("Test Fail!")
                End If
            End Using
        Catch
            MessageBox.Show("ERROR, Could not open LOT.TXT log file!" & vbLf)
        End Try
    End Sub

    Private Sub btnButtonSet30_Click(ByVal sender As Object, ByVal e As EventArgs) Handles btnButtonSet30.Click
        Dim wCardNum As UInt16 = CUShort(m_Number)

        Dim data As Byte() = New Byte(31) {}
        Dim new_data As Byte() = New Byte(31) {}
        Dim data1 As Byte() = New Byte(31) {}
        Dim enc_data As Byte() = New Byte(31) {}
        Dim mac As Byte() = New Byte(31) {}
        Dim read_mac As Byte() = New Byte(31) {}

        Dim page7SavedData As Byte() = New Byte(31) {}
        Dim page8SavedData As Byte() = New Byte(31) {}
        Dim page9SavedData As Byte() = New Byte(31) {}

        Dim result As Integer
        Dim compareOK As Integer = 1
        Dim startPage As UInt16 = &H1
        Dim num_pages_to_test As Integer = 1
        Dim num_bytes_to_test As Integer = 32

        '''/////////////////////////

        Dim notUsed As Byte() = New Byte(0) {}
        Dim zeroLen As UInt16 = 0
        Dim len32 As UInt16 = 32

        Dim data3 As Byte() = New Byte(31) {}
        Dim chk_mac As Byte() = New Byte(31) {}
        Dim data4 As Byte() = New Byte(11) {}
        Dim data5 As Byte() = New Byte(0) {}
        Dim i As Integer
        Dim rslt As Integer
        Dim rt As Integer = 1
        Dim block As Integer
        Dim skip_setup As Integer = 0
        Dim page As Integer
        Dim cnt As Integer

        Dim [partial] As Byte() = New Byte(31) {}
        Dim new_page As Byte() = New Byte(31) {}
        Dim current_secret As Integer = 0
        Dim cleared_byte As Integer
        Dim memimage As Byte() = New Byte(511) {}
        Dim master_secret As Byte() = New Byte(31) {}
        Dim binding As Byte() = New Byte(31) {}
        Dim romid As Byte() = New Byte(7) {}
        Dim manid As Byte() = New Byte(1) {}
        Dim challenge As Byte() = New Byte(7) {}

        Dim ITROMId As Byte() = New Byte(7) {}
        Dim ITMANId As Byte() = New Byte(1) {}
        Dim ITmaster_secret As Byte() = New Byte(31) {}
        Dim ITpartial As Byte() = New Byte(31) {}
        Dim ITbinding As Byte() = New Byte(31) {}

        Dim str As String
        Dim strHex As String

        Dim TempUserPath As String = My.Computer.FileSystem.SpecialDirectories.MyDocuments
        TempUserPath = TempUserPath + "//ADLINK"

        Try
            ' Determine whether the directory exists.
            If Directory.Exists(TempUserPath) Then
            Else
                ' Try to create the directory.
                Dim di As DirectoryInfo = Directory.CreateDirectory(TempUserPath)
            End If

        Catch ex As Exception
            Console.WriteLine("The process failed: {0}.", e.ToString())
        End Try

        ' open log file and print time stamp
        TempUserPath = TempUserPath + "//log8-5.txt"

        Try
            Using w As StreamWriter = File.AppendText(TempUserPath)
                'RandomNumbers.Seed((uint)time(null));

                w.Write("num_bytes_to_test: ")
                w.Write("{0}", num_bytes_to_test)

                str = txtEditDcgetbuf5.Text
                'data[32] + romid[8] + manid[2] + enc_data[32] + chk_mac[32] + challenge[8]

                For i = 0 To 31
                    strHex = str.Substring((i * 2) + (0 * 2), 2)
                    data(i) = CByte(hex2uint(strHex))
                Next

                For i = 0 To 7
                    strHex = str.Substring((i * 2) + (32 * 2), 2)
                    romid(i) = CByte(hex2uint(strHex))
                Next

                For i = 0 To 1
                    strHex = str.Substring((i * 2) + (40 * 2), 2)
                    manid(i) = CByte(hex2uint(strHex))
                Next

                For i = 0 To 31
                    strHex = str.Substring((i * 2) + (42 * 2), 2)
                    enc_data(i) = CByte(hex2uint(strHex))
                Next

                For i = 0 To 31
                    strHex = str.Substring((i * 2) + (74 * 2), 2)
                    chk_mac(i) = CByte(hex2uint(strHex))
                Next

                For i = 0 To 7
                    strHex = str.Substring((i * 2) + (106 * 2), 2)
                    challenge(i) = CByte(hex2uint(strHex))
                Next

                w.Write("AD_EncryptAuthWritePageEnc_ex2, wCardNum {0}" & vbCr & vbLf, wCardNum)
                rslt = AD_License_management.AD_EncryptAuthWritePageEnc(wCardNum, CUShort(num_bytes_to_test), enc_data, data, romid, manid, chk_mac, challenge, 0)


                w.Write("enc_data: ")
                For i = 0 To num_bytes_to_test - 1
                    w.Write("{0:X2}", enc_data(i))
                Next
                w.Write(vbCr & vbLf)

                w.Write("data: ")
                For i = 0 To 31
                    w.Write("{0:X2}", data(i))
                Next
                w.Write(vbCr & vbLf)

                w.Write("romid: ")
                For i = 0 To 7
                    w.Write("{0:X2}", romid(i))
                Next
                w.Write(vbCr & vbLf)

                w.Write("manid: ")
                For i = 0 To 1
                    w.Write("{0:X2}", manid(i))
                Next
                w.Write(vbCr & vbLf)

                w.Write("chk_mac: ")
                For i = 0 To 31
                    w.Write("{0:X2}", chk_mac(i))
                Next
                w.Write(vbCr & vbLf)

                w.Write("challenge: ")
                For i = 0 To 7
                    w.Write("{0:X2}", challenge(i))
                Next
                w.Write(vbCr & vbLf)


                w.Write("AD_EncryptAuthWritePageEnc_ex2: ----------------------------------")
                w.Write(" {0}" & vbCr & vbLf, If((rslt = 1), "FAIL", "SUCCESS"))
                If rslt = 1 Then
                    rt = 0
                End If

                w.Write("AD_EncryptReadSegment_ex2, wCardNum {0}" & vbCr & vbLf, wCardNum)
                rslt = AD_License_management.AD_EncryptReadSegment(wCardNum, data1, romid, manid, chk_mac, challenge)


                w.Write("data1: ")
                For i = 0 To 31
                    w.Write("{0:X2}", data1(i))
                Next
                w.Write(vbCr & vbLf)

                w.Write("romid: ")
                For i = 0 To 7
                    w.Write("{0:X2}", romid(i))
                Next
                w.Write(vbCr & vbLf)

                w.Write("manid: ")
                For i = 0 To 1
                    w.Write("{0:X2}", manid(i))
                Next
                w.Write(vbCr & vbLf)


                w.Write("AD_EncryptReadSegment_ex2:  ----------------------------------")
                w.Write(" {0}" & vbCr & vbLf, If((rslt = 1), "FAIL", "SUCCESS"))
                If rslt = 1 Then
                    rt = 0
                End If


                If rt = 1 Then
                    w.Write("Test Pass!")
                Else
                    w.Write("Test Fail!")
                End If
            End Using
        Catch
            MessageBox.Show("ERROR, Could not open LOT.TXT log file!" & vbLf)
        End Try
    End Sub

    Private Sub btnButtonSet21_Click(ByVal sender As Object, ByVal e As EventArgs) Handles btnButtonSet21.Click
        Dim wCardNum As UInt16 = CUShort(m_Number)

        Dim challenge As Byte() = New Byte(31) {}
        Dim data As Byte() = New Byte(31) {}
        Dim new_data As Byte() = New Byte(31) {}
        Dim data1 As Byte() = New Byte(31) {}
        Dim mac As Byte() = New Byte(31) {}

        Dim page7SavedData As Byte() = New Byte(31) {}
        Dim page8SavedData As Byte() = New Byte(31) {}
        Dim page9SavedData As Byte() = New Byte(31) {}

        Dim result As Integer
        Dim compareOK As Integer = 1
        Dim startPage As UInt16 = &H1
        Dim num_pages_to_test As Integer = 1
        Dim num_bytes_to_test As Integer = 32

        '''/////////////////////////

        Dim notUsed As [Byte]() = New [Byte](0) {}
        Dim zeroLen As UInt16 = 0
        Dim len32 As UInt16 = 32

        Dim data3 As Byte() = New Byte(31) {}
        Dim data4 As Byte() = New Byte(11) {}
        Dim data5 As Byte() = New Byte(0) {}
        Dim i As Integer
        Dim rslt As Integer
        Dim rt As Integer = 1
        Dim block As Integer
        Dim skip_setup As Integer = 0
        Dim page As Integer
        Dim cnt As Integer

        Dim [partial] As Byte() = New Byte(31) {}
        Dim new_page As Byte() = New Byte(31) {}
        Dim current_secret As Integer = 0
        Dim cleared_byte As Integer
        Dim memimage As Byte() = New Byte(511) {}
        Dim master_secret As Byte() = New Byte(31) {}
        Dim binding As Byte() = New Byte(31) {}
        Dim romid As Byte() = New Byte(7) {}
        Dim manid As Byte() = New Byte(1) {}

        Dim ITROMId As Byte() = New Byte(7) {}
        Dim ITMANId As Byte() = New Byte(1) {}
        Dim ITmaster_secret As Byte() = New Byte(31) {}
        Dim ITpartial As Byte() = New Byte(31) {}
        Dim ITbinding As Byte() = New Byte(31) {}

        Dim strHex As String

        Dim TempUserPath As String = My.Computer.FileSystem.SpecialDirectories.MyDocuments
        TempUserPath = TempUserPath + "//ADLINK"

        Try
            ' Determine whether the directory exists.
            If Directory.Exists(TempUserPath) Then
            Else
                ' Try to create the directory.
                Dim di As DirectoryInfo = Directory.CreateDirectory(TempUserPath)
            End If

        Catch ex As Exception
            Console.WriteLine("The process failed: {0}.", e.ToString())
        End Try

        ' open log file and print time stamp
        TempUserPath = TempUserPath + "//log6-0.txt"
        Try
            Using w As StreamWriter = File.AppendText(TempUserPath)
                'RandomNumbers.Seed((uint)time(null));

                For i = 0 To 31
                    strHex = txtEditDcsetbuf(i).Text
                    master_secret(i) = CByte(hex2uint(strHex))
                Next

                w.Write("master_secret: ")
                For i = 0 To 31
                    w.Write("{0:X2}", master_secret(i))
                Next
                w.Write(vbCr & vbLf)

                'MessageBox("The Card will InstallSecret!!!");

                Dim msgtmp = MessageBox.Show("The Card will InstallSecret!!!", "InstallSecret", MessageBoxButtons.YesNo, MessageBoxIcon.Question)
                If msgtmp = DialogResult.Yes Then
                    w.Write("AD_SetMasterSecret, wCardNum {0}" & vbCr & vbLf, wCardNum)
                    rslt = AD_License_management.AD_InstallSecret(wCardNum, master_secret, False)

                    w.Write(" {0}" & vbCr & vbLf, If((rslt) <> 0, "FAIL", "SUCCESS"))
                    If rslt <> 0 Then
                        rt = 0
                    End If

                    If rt = 1 Then
                        w.Write("Test Pass!")
                    Else
                        w.Write("Test Fail!")
                    End If
                Else
                    w.Write("Test Cancel")
                End If
            End Using
        Catch

            MessageBox.Show("ERROR, Could not open LOT.TXT log file!" & vbLf)
        End Try
    End Sub

    Private Sub btnButtonSet18_Click(ByVal sender As Object, ByVal e As EventArgs) Handles btnButtonSet18.Click
        Dim wCardNum As UInt16 = CUShort(m_Number)

        Dim challenge As Byte() = New Byte(31) {}
        Dim data As Byte() = New Byte(31) {}
        Dim new_data As Byte() = New Byte(31) {}
        Dim data1 As Byte() = New Byte(31) {}
        Dim mac As Byte() = New Byte(31) {}

        Dim page7SavedData As Byte() = New Byte(31) {}
        Dim page8SavedData As Byte() = New Byte(31) {}
        Dim page9SavedData As Byte() = New Byte(31) {}

        Dim result As Integer
        Dim compareOK As Integer = 1
        Dim startPage As UInt16 = &H1
        Dim num_pages_to_test As Integer = 1
        Dim num_bytes_to_test As Integer = 32

        '''/////////////////////////

        Dim notUsed As Byte() = New Byte(0) {}
        Dim zeroLen As UInt16 = 0
        Dim len32 As UInt16 = 32

        Dim data3 As Byte() = New Byte(31) {}
        Dim data4 As Byte() = New Byte(11) {}
        Dim data5 As Byte() = New Byte(0) {}
        Dim i As Integer
        Dim rslt As Integer
        Dim rt As Integer = 1
        Dim block As Integer
        Dim skip_setup As Integer = 0
        Dim page As Integer
        Dim cnt As Integer

        Dim [partial] As Byte() = New Byte(31) {}
        Dim new_page As Byte() = New Byte(31) {}
        Dim current_secret As Integer = 0
        Dim cleared_byte As Integer
        Dim memimage As Byte() = New Byte(511) {}
        Dim master_secret As Byte() = New Byte(31) {}
        Dim binding As Byte() = New Byte(31) {}
        Dim romid As Byte() = New Byte(7) {}
        Dim manid As Byte() = New Byte(1) {}

        Dim ITROMId As Byte() = New Byte(7) {}
        Dim ITMANId As Byte() = New Byte(1) {}
        Dim ITmaster_secret As Byte() = New Byte(31) {}
        Dim ITpartial As Byte() = New Byte(31) {}
        Dim ITbinding As Byte() = New Byte(31) {}

        Dim strHex As String

        Dim TempUserPath As String = My.Computer.FileSystem.SpecialDirectories.MyDocuments
        TempUserPath = TempUserPath + "//ADLINK"

        Try
            ' Determine whether the directory exists.
            If Directory.Exists(TempUserPath) Then
            Else
                ' Try to create the directory.
                Dim di As DirectoryInfo = Directory.CreateDirectory(TempUserPath)
            End If

        Catch ex As Exception
            Console.WriteLine("The process failed: {0}.", e.ToString())
        End Try

        ' open log file and print time stamp			
        TempUserPath = TempUserPath + "//log6-1.txt"
        Try
            Using w As StreamWriter = File.AppendText(TempUserPath)
                'RandomNumbers.Seed((uint)time(null));
                For i = 0 To 31
                    strHex = txtEditDcsetbuf(i).Text
                    master_secret(i) = CByte(hex2uint(strHex))
                Next

                w.Write("master_secret: ")
                For i = 0 To 31
                    w.Write("{0:X2}", master_secret(i))
                Next
                w.Write(vbCr & vbLf)

                w.Write("AD_SetMasterSecret, wCardNum {0}" & vbCr & vbLf, wCardNum)
                rslt = AD_License_management.AD_SetMasterSecret(wCardNum, master_secret)

                w.Write(" {0}" & vbCr & vbLf, If((rslt) <> 0, "FAIL", "SUCCESS"))
                If rslt <> 0 Then
                    rt = 0
                End If


                If rt = 1 Then
                    w.Write("Test Pass!")
                Else
                    w.Write("Test Fail!")
                End If
            End Using
        Catch

            MessageBox.Show("ERROR, Could not open LOT.TXT log file!" & vbLf)
        End Try
    End Sub
	Private Shared Function InlineAssignHelper(Of T)(ByRef target As T, value As T) As T
		target = value
		Return value
	End Function

    Private Sub Button1_Click(ByVal sender As System.Object, ByVal e As System.EventArgs)

    End Sub
End Class
