'This code has been automatically generated by DudeLabs, LLC RCConverter
Imports System.Drawing
Imports System.Collections
Imports System.ComponentModel
Imports System.Windows.Forms
''' <summary>
''' Summary description for FrmSamrtpoesampleDialog.
''' </summary>

Partial Class FrmSamrtpoesampleDialog
	Inherits System.Windows.Forms.Form
	''' <summary>
	''' Required designer variable.
	''' </summary>
	Private components As System.ComponentModel.Container = Nothing
	Private lblStatic1 As System.Windows.Forms.Label
    Friend WithEvents cboComboCardNumber As System.Windows.Forms.ComboBox
	Private lblStatic2 As System.Windows.Forms.Label
	Private txtEditId As System.Windows.Forms.TextBox
	Private txtEditDcgetbuf0 As System.Windows.Forms.TextBox
	Private lblStatic3 As System.Windows.Forms.Label
	Private lblStatic4 As System.Windows.Forms.Label
	Private txtEditError As System.Windows.Forms.TextBox
	Private lblStatic5 As System.Windows.Forms.Label
	Private txtEditId14 As System.Windows.Forms.TextBox
	Private lblStatic6 As System.Windows.Forms.Label
	Private txtEditId15 As System.Windows.Forms.TextBox
	Private lblStatic7 As System.Windows.Forms.Label
	Private txtEditId16 As System.Windows.Forms.TextBox
    Friend WithEvents btnButtonSet4 As System.Windows.Forms.Button
	Private grpStatic8 As System.Windows.Forms.GroupBox
	Private lblStatic9 As System.Windows.Forms.Label
	Private txtEditId18 As System.Windows.Forms.TextBox
	Private txtEditId19 As System.Windows.Forms.TextBox
	Private lblStatic10 As System.Windows.Forms.Label
	Private lblStatic11 As System.Windows.Forms.Label
	Private txtEditId20 As System.Windows.Forms.TextBox
    Friend WithEvents btnButtonSet29 As System.Windows.Forms.Button
    Friend WithEvents btnButtonSet30 As System.Windows.Forms.Button
    Friend WithEvents btnButtonSet31 As System.Windows.Forms.Button
    Friend WithEvents btnButtonSet32 As System.Windows.Forms.Button
	Private txtEditDcgetbuf5 As System.Windows.Forms.TextBox
	Private txtEditDcgetbuf6 As System.Windows.Forms.TextBox
    Friend WithEvents btnButtonSet33 As System.Windows.Forms.Button
	'public System.Windows.Forms.TextBox[] txtEditDcsetbuf = new System.Windows.Forms.TextBox[32];




	''' <summary>
	''' Clean up any resources being used.
	''' </summary>
	Protected Overrides Sub Dispose(disposing As Boolean)
		If disposing Then
			If components IsNot Nothing Then
				components.Dispose()
			End If
		End If
		MyBase.Dispose(disposing)
	End Sub

	#Region "DudeLabs LLC RCConverter generated code"
	''' <summary>
	''' Required method for Designer support - do not modify
	''' the contents of this method with the code editor.
	''' </summary>
	Private Sub InitializeComponent()
        Me.lblStatic1 = New System.Windows.Forms.Label()
        Me.cboComboCardNumber = New System.Windows.Forms.ComboBox()
        Me.lblStatic2 = New System.Windows.Forms.Label()
        Me.txtEditId = New System.Windows.Forms.TextBox()
        Me.txtEditDcgetbuf0 = New System.Windows.Forms.TextBox()
        Me.lblStatic3 = New System.Windows.Forms.Label()
        Me.lblStatic4 = New System.Windows.Forms.Label()
        Me.txtEditError = New System.Windows.Forms.TextBox()
        Me.lblStatic5 = New System.Windows.Forms.Label()
        Me.txtEditId14 = New System.Windows.Forms.TextBox()
        Me.lblStatic6 = New System.Windows.Forms.Label()
        Me.txtEditId15 = New System.Windows.Forms.TextBox()
        Me.lblStatic7 = New System.Windows.Forms.Label()
        Me.txtEditId16 = New System.Windows.Forms.TextBox()
        Me.btnButtonSet4 = New System.Windows.Forms.Button()
        Me.grpStatic8 = New System.Windows.Forms.GroupBox()
        Me.lblStatic10 = New System.Windows.Forms.Label()
        Me.lblStatic11 = New System.Windows.Forms.Label()
        Me.lblStatic9 = New System.Windows.Forms.Label()
        Me.txtEditId18 = New System.Windows.Forms.TextBox()
        Me.txtEditId19 = New System.Windows.Forms.TextBox()
        Me.txtEditId20 = New System.Windows.Forms.TextBox()
        Me.btnButtonSet29 = New System.Windows.Forms.Button()
        Me.btnButtonSet30 = New System.Windows.Forms.Button()
        Me.btnButtonSet31 = New System.Windows.Forms.Button()
        Me.btnButtonSet32 = New System.Windows.Forms.Button()
        Me.txtEditDcgetbuf5 = New System.Windows.Forms.TextBox()
        Me.txtEditDcgetbuf6 = New System.Windows.Forms.TextBox()
        Me.btnButtonSet33 = New System.Windows.Forms.Button()
        Me.panel2 = New System.Windows.Forms.Panel()
        Me.rdoRadio1On1 = New System.Windows.Forms.RadioButton()
        Me.rdoRadio1Off1 = New System.Windows.Forms.RadioButton()
        Me.lblStatic13 = New System.Windows.Forms.Label()
        Me.panel3 = New System.Windows.Forms.Panel()
        Me.rdoRadio1Off2 = New System.Windows.Forms.RadioButton()
        Me.rdoRadio1On2 = New System.Windows.Forms.RadioButton()
        Me.lblStatic14 = New System.Windows.Forms.Label()
        Me.panel4 = New System.Windows.Forms.Panel()
        Me.rdoRadio1Off4 = New System.Windows.Forms.RadioButton()
        Me.rdoRadio1On4 = New System.Windows.Forms.RadioButton()
        Me.lblStatic16 = New System.Windows.Forms.Label()
        Me.panel5 = New System.Windows.Forms.Panel()
        Me.rdoRadio1Off3 = New System.Windows.Forms.RadioButton()
        Me.rdoRadio1On3 = New System.Windows.Forms.RadioButton()
        Me.lblStatic15 = New System.Windows.Forms.Label()
        Me.panel6 = New System.Windows.Forms.Panel()
        Me.rdoRadio1Off8 = New System.Windows.Forms.RadioButton()
        Me.rdoRadio1On8 = New System.Windows.Forms.RadioButton()
        Me.lblStatic20 = New System.Windows.Forms.Label()
        Me.panel7 = New System.Windows.Forms.Panel()
        Me.rdoRadio1Off6 = New System.Windows.Forms.RadioButton()
        Me.rdoRadio1On6 = New System.Windows.Forms.RadioButton()
        Me.lblStatic18 = New System.Windows.Forms.Label()
        Me.panel8 = New System.Windows.Forms.Panel()
        Me.rdoRadio1Off7 = New System.Windows.Forms.RadioButton()
        Me.rdoRadio1On7 = New System.Windows.Forms.RadioButton()
        Me.lblStatic19 = New System.Windows.Forms.Label()
        Me.panel9 = New System.Windows.Forms.Panel()
        Me.rdoRadio1Off5 = New System.Windows.Forms.RadioButton()
        Me.rdoRadio1On5 = New System.Windows.Forms.RadioButton()
        Me.lblStatic17 = New System.Windows.Forms.Label()
        Me.panel1 = New System.Windows.Forms.Panel()
        Me.rdoRadio1Off16 = New System.Windows.Forms.RadioButton()
        Me.rdoRadio1On16 = New System.Windows.Forms.RadioButton()
        Me.lblStatic28 = New System.Windows.Forms.Label()
        Me.panel10 = New System.Windows.Forms.Panel()
        Me.rdoRadio1Off12 = New System.Windows.Forms.RadioButton()
        Me.rdoRadio1On12 = New System.Windows.Forms.RadioButton()
        Me.lblStatic24 = New System.Windows.Forms.Label()
        Me.panel11 = New System.Windows.Forms.Panel()
        Me.rdoRadio1Off14 = New System.Windows.Forms.RadioButton()
        Me.rdoRadio1On14 = New System.Windows.Forms.RadioButton()
        Me.lblStatic26 = New System.Windows.Forms.Label()
        Me.panel12 = New System.Windows.Forms.Panel()
        Me.rdoRadio1Off10 = New System.Windows.Forms.RadioButton()
        Me.rdoRadio1On10 = New System.Windows.Forms.RadioButton()
        Me.lblStatic22 = New System.Windows.Forms.Label()
        Me.panel13 = New System.Windows.Forms.Panel()
        Me.rdoRadio1Off15 = New System.Windows.Forms.RadioButton()
        Me.rdoRadio1On15 = New System.Windows.Forms.RadioButton()
        Me.lblStatic27 = New System.Windows.Forms.Label()
        Me.panel14 = New System.Windows.Forms.Panel()
        Me.rdoRadio1Off11 = New System.Windows.Forms.RadioButton()
        Me.rdoRadio1On11 = New System.Windows.Forms.RadioButton()
        Me.lblStatic23 = New System.Windows.Forms.Label()
        Me.panel15 = New System.Windows.Forms.Panel()
        Me.rdoRadio1Off13 = New System.Windows.Forms.RadioButton()
        Me.rdoRadio1On13 = New System.Windows.Forms.RadioButton()
        Me.lblStatic25 = New System.Windows.Forms.Label()
        Me.panel16 = New System.Windows.Forms.Panel()
        Me.rdoRadio1Off9 = New System.Windows.Forms.RadioButton()
        Me.rdoRadio1On9 = New System.Windows.Forms.RadioButton()
        Me.label1 = New System.Windows.Forms.Label()
        Me.grpStatic10 = New System.Windows.Forms.GroupBox()
        Me.btnButtonSet18 = New System.Windows.Forms.Button()
        Me.label2 = New System.Windows.Forms.Label()
        Me.btnButtonSet21 = New System.Windows.Forms.Button()
        Me.label3 = New System.Windows.Forms.Label()
        Me.txtEditDcsetbuf0 = New System.Windows.Forms.TextBox()
        Me.txtEditDcsetbuf1 = New System.Windows.Forms.TextBox()
        Me.txtEditDcsetbuf10 = New System.Windows.Forms.TextBox()
        Me.txtEditDcsetbuf11 = New System.Windows.Forms.TextBox()
        Me.txtEditDcsetbuf12 = New System.Windows.Forms.TextBox()
        Me.txtEditDcsetbuf13 = New System.Windows.Forms.TextBox()
        Me.txtEditDcsetbuf14 = New System.Windows.Forms.TextBox()
        Me.txtEditDcsetbuf15 = New System.Windows.Forms.TextBox()
        Me.txtEditDcsetbuf16 = New System.Windows.Forms.TextBox()
        Me.txtEditDcsetbuf17 = New System.Windows.Forms.TextBox()
        Me.txtEditDcsetbuf18 = New System.Windows.Forms.TextBox()
        Me.txtEditDcsetbuf19 = New System.Windows.Forms.TextBox()
        Me.txtEditDcsetbuf2 = New System.Windows.Forms.TextBox()
        Me.txtEditDcsetbuf20 = New System.Windows.Forms.TextBox()
        Me.txtEditDcsetbuf21 = New System.Windows.Forms.TextBox()
        Me.txtEditDcsetbuf22 = New System.Windows.Forms.TextBox()
        Me.txtEditDcsetbuf23 = New System.Windows.Forms.TextBox()
        Me.txtEditDcsetbuf24 = New System.Windows.Forms.TextBox()
        Me.txtEditDcsetbuf25 = New System.Windows.Forms.TextBox()
        Me.txtEditDcsetbuf26 = New System.Windows.Forms.TextBox()
        Me.txtEditDcsetbuf27 = New System.Windows.Forms.TextBox()
        Me.txtEditDcsetbuf28 = New System.Windows.Forms.TextBox()
        Me.txtEditDcsetbuf29 = New System.Windows.Forms.TextBox()
        Me.txtEditDcsetbuf3 = New System.Windows.Forms.TextBox()
        Me.txtEditDcsetbuf30 = New System.Windows.Forms.TextBox()
        Me.txtEditDcsetbuf31 = New System.Windows.Forms.TextBox()
        Me.txtEditDcsetbuf4 = New System.Windows.Forms.TextBox()
        Me.txtEditDcsetbuf5 = New System.Windows.Forms.TextBox()
        Me.txtEditDcsetbuf6 = New System.Windows.Forms.TextBox()
        Me.txtEditDcsetbuf7 = New System.Windows.Forms.TextBox()
        Me.txtEditDcsetbuf8 = New System.Windows.Forms.TextBox()
        Me.txtEditDcsetbuf9 = New System.Windows.Forms.TextBox()
        Me.groupBox1 = New System.Windows.Forms.GroupBox()
        Me.groupBox2 = New System.Windows.Forms.GroupBox()
        Me.groupBox3 = New System.Windows.Forms.GroupBox()
        Me.grpStatic8.SuspendLayout()
        Me.panel2.SuspendLayout()
        Me.panel3.SuspendLayout()
        Me.panel4.SuspendLayout()
        Me.panel5.SuspendLayout()
        Me.panel6.SuspendLayout()
        Me.panel7.SuspendLayout()
        Me.panel8.SuspendLayout()
        Me.panel9.SuspendLayout()
        Me.panel1.SuspendLayout()
        Me.panel10.SuspendLayout()
        Me.panel11.SuspendLayout()
        Me.panel12.SuspendLayout()
        Me.panel13.SuspendLayout()
        Me.panel14.SuspendLayout()
        Me.panel15.SuspendLayout()
        Me.panel16.SuspendLayout()
        Me.grpStatic10.SuspendLayout()
        Me.groupBox1.SuspendLayout()
        Me.groupBox2.SuspendLayout()
        Me.groupBox3.SuspendLayout()
        Me.SuspendLayout()
        '
        'lblStatic1
        '
        Me.lblStatic1.AutoSize = True
        Me.lblStatic1.Location = New System.Drawing.Point(42, 21)
        Me.lblStatic1.Name = "lblStatic1"
        Me.lblStatic1.Size = New System.Drawing.Size(70, 13)
        Me.lblStatic1.TabIndex = 1
        Me.lblStatic1.Text = "Card number:"
        '
        'cboComboCardNumber
        '
        Me.cboComboCardNumber.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList
        Me.cboComboCardNumber.Location = New System.Drawing.Point(120, 18)
        Me.cboComboCardNumber.Name = "cboComboCardNumber"
        Me.cboComboCardNumber.Size = New System.Drawing.Size(78, 21)
        Me.cboComboCardNumber.TabIndex = 2
        '
        'lblStatic2
        '
        Me.lblStatic2.AutoSize = True
        Me.lblStatic2.Location = New System.Drawing.Point(66, 50)
        Me.lblStatic2.Name = "lblStatic2"
        Me.lblStatic2.Size = New System.Drawing.Size(46, 13)
        Me.lblStatic2.TabIndex = 3
        Me.lblStatic2.Text = "Card ID:"
        '
        'txtEditId
        '
        Me.txtEditId.Enabled = False
        Me.txtEditId.Location = New System.Drawing.Point(120, 45)
        Me.txtEditId.Name = "txtEditId"
        Me.txtEditId.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditId.Size = New System.Drawing.Size(78, 20)
        Me.txtEditId.TabIndex = 4
        '
        'txtEditDcgetbuf0
        '
        Me.txtEditDcgetbuf0.Location = New System.Drawing.Point(102, 189)
        Me.txtEditDcgetbuf0.Name = "txtEditDcgetbuf0"
        Me.txtEditDcgetbuf0.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditDcgetbuf0.Size = New System.Drawing.Size(315, 20)
        Me.txtEditDcgetbuf0.TabIndex = 5
        '
        'lblStatic3
        '
        Me.lblStatic3.AutoSize = True
        Me.lblStatic3.Location = New System.Drawing.Point(18, 189)
        Me.lblStatic3.Name = "lblStatic3"
        Me.lblStatic3.Size = New System.Drawing.Size(60, 13)
        Me.lblStatic3.TabIndex = 6
        Me.lblStatic3.Text = "getbuf(hex)"
        '
        'lblStatic4
        '
        Me.lblStatic4.AutoSize = True
        Me.lblStatic4.Location = New System.Drawing.Point(216, 18)
        Me.lblStatic4.Name = "lblStatic4"
        Me.lblStatic4.Size = New System.Drawing.Size(49, 13)
        Me.lblStatic4.TabIndex = 7
        Me.lblStatic4.Text = "ERROR:"
        '
        'txtEditError
        '
        Me.txtEditError.Enabled = False
        Me.txtEditError.Location = New System.Drawing.Point(270, 13)
        Me.txtEditError.Name = "txtEditError"
        Me.txtEditError.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditError.Size = New System.Drawing.Size(78, 20)
        Me.txtEditError.TabIndex = 8
        '
        'lblStatic5
        '
        Me.lblStatic5.AutoSize = True
        Me.lblStatic5.Location = New System.Drawing.Point(212, 49)
        Me.lblStatic5.Name = "lblStatic5"
        Me.lblStatic5.Size = New System.Drawing.Size(59, 13)
        Me.lblStatic5.TabIndex = 9
        Me.lblStatic5.Text = "EEVersion:"
        '
        'txtEditId14
        '
        Me.txtEditId14.Enabled = False
        Me.txtEditId14.Location = New System.Drawing.Point(270, 45)
        Me.txtEditId14.Name = "txtEditId14"
        Me.txtEditId14.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditId14.Size = New System.Drawing.Size(78, 20)
        Me.txtEditId14.TabIndex = 10
        '
        'lblStatic6
        '
        Me.lblStatic6.AutoSize = True
        Me.lblStatic6.Location = New System.Drawing.Point(365, 48)
        Me.lblStatic6.Name = "lblStatic6"
        Me.lblStatic6.Size = New System.Drawing.Size(67, 13)
        Me.lblStatic6.TabIndex = 11
        Me.lblStatic6.Text = "EEStandard:"
        '
        'txtEditId15
        '
        Me.txtEditId15.Enabled = False
        Me.txtEditId15.Location = New System.Drawing.Point(432, 45)
        Me.txtEditId15.Name = "txtEditId15"
        Me.txtEditId15.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditId15.Size = New System.Drawing.Size(78, 20)
        Me.txtEditId15.TabIndex = 12
        '
        'lblStatic7
        '
        Me.lblStatic7.AutoSize = True
        Me.lblStatic7.Location = New System.Drawing.Point(528, 48)
        Me.lblStatic7.Name = "lblStatic7"
        Me.lblStatic7.Size = New System.Drawing.Size(43, 13)
        Me.lblStatic7.TabIndex = 13
        Me.lblStatic7.Text = "EEPort:"
        '
        'txtEditId16
        '
        Me.txtEditId16.Enabled = False
        Me.txtEditId16.Location = New System.Drawing.Point(582, 43)
        Me.txtEditId16.Name = "txtEditId16"
        Me.txtEditId16.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditId16.Size = New System.Drawing.Size(78, 20)
        Me.txtEditId16.TabIndex = 14
        '
        'btnButtonSet4
        '
        Me.btnButtonSet4.Location = New System.Drawing.Point(364, 13)
        Me.btnButtonSet4.Name = "btnButtonSet4"
        Me.btnButtonSet4.Size = New System.Drawing.Size(75, 24)
        Me.btnButtonSet4.TabIndex = 15
        Me.btnButtonSet4.Text = "Clear ERROR"
        '
        'grpStatic8
        '
        Me.grpStatic8.Controls.Add(Me.btnButtonSet4)
        Me.grpStatic8.Controls.Add(Me.cboComboCardNumber)
        Me.grpStatic8.Controls.Add(Me.lblStatic1)
        Me.grpStatic8.Controls.Add(Me.lblStatic10)
        Me.grpStatic8.Controls.Add(Me.lblStatic11)
        Me.grpStatic8.Controls.Add(Me.lblStatic2)
        Me.grpStatic8.Controls.Add(Me.lblStatic4)
        Me.grpStatic8.Controls.Add(Me.lblStatic5)
        Me.grpStatic8.Controls.Add(Me.lblStatic6)
        Me.grpStatic8.Controls.Add(Me.lblStatic7)
        Me.grpStatic8.Controls.Add(Me.lblStatic9)
        Me.grpStatic8.Controls.Add(Me.txtEditError)
        Me.grpStatic8.Controls.Add(Me.txtEditId)
        Me.grpStatic8.Controls.Add(Me.txtEditId14)
        Me.grpStatic8.Controls.Add(Me.txtEditId15)
        Me.grpStatic8.Controls.Add(Me.txtEditId16)
        Me.grpStatic8.Controls.Add(Me.txtEditId18)
        Me.grpStatic8.Controls.Add(Me.txtEditId19)
        Me.grpStatic8.Controls.Add(Me.txtEditId20)
        Me.grpStatic8.Location = New System.Drawing.Point(22, 11)
        Me.grpStatic8.Name = "grpStatic8"
        Me.grpStatic8.Size = New System.Drawing.Size(1017, 76)
        Me.grpStatic8.TabIndex = 16
        Me.grpStatic8.TabStop = False
        Me.grpStatic8.Text = "Static"
        '
        'lblStatic10
        '
        Me.lblStatic10.AutoSize = True
        Me.lblStatic10.Location = New System.Drawing.Point(842, 16)
        Me.lblStatic10.Name = "lblStatic10"
        Me.lblStatic10.Size = New System.Drawing.Size(79, 13)
        Me.lblStatic10.TabIndex = 20
        Me.lblStatic10.Text = "CPLDVersion2:"
        '
        'lblStatic11
        '
        Me.lblStatic11.AutoSize = True
        Me.lblStatic11.Location = New System.Drawing.Point(678, 43)
        Me.lblStatic11.Name = "lblStatic11"
        Me.lblStatic11.Size = New System.Drawing.Size(69, 13)
        Me.lblStatic11.TabIndex = 21
        Me.lblStatic11.Text = "MCUVersion:"
        '
        'lblStatic9
        '
        Me.lblStatic9.AutoSize = True
        Me.lblStatic9.Location = New System.Drawing.Point(670, 17)
        Me.lblStatic9.Name = "lblStatic9"
        Me.lblStatic9.Size = New System.Drawing.Size(79, 13)
        Me.lblStatic9.TabIndex = 17
        Me.lblStatic9.Text = "CPLDVersion1:"
        '
        'txtEditId18
        '
        Me.txtEditId18.Enabled = False
        Me.txtEditId18.Location = New System.Drawing.Point(750, 13)
        Me.txtEditId18.Name = "txtEditId18"
        Me.txtEditId18.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditId18.Size = New System.Drawing.Size(78, 20)
        Me.txtEditId18.TabIndex = 18
        '
        'txtEditId19
        '
        Me.txtEditId19.Enabled = False
        Me.txtEditId19.Location = New System.Drawing.Point(922, 13)
        Me.txtEditId19.Name = "txtEditId19"
        Me.txtEditId19.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditId19.Size = New System.Drawing.Size(78, 20)
        Me.txtEditId19.TabIndex = 19
        '
        'txtEditId20
        '
        Me.txtEditId20.Enabled = False
        Me.txtEditId20.Location = New System.Drawing.Point(750, 39)
        Me.txtEditId20.Name = "txtEditId20"
        Me.txtEditId20.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditId20.Size = New System.Drawing.Size(78, 20)
        Me.txtEditId20.TabIndex = 22
        '
        'btnButtonSet29
        '
        Me.btnButtonSet29.Location = New System.Drawing.Point(11, 17)
        Me.btnButtonSet29.Name = "btnButtonSet29"
        Me.btnButtonSet29.Size = New System.Drawing.Size(147, 24)
        Me.btnButtonSet29.TabIndex = 25
        Me.btnButtonSet29.Text = "EncryptReadSegment"
        '
        'btnButtonSet30
        '
        Me.btnButtonSet30.Location = New System.Drawing.Point(11, 183)
        Me.btnButtonSet30.Name = "btnButtonSet30"
        Me.btnButtonSet30.Size = New System.Drawing.Size(160, 24)
        Me.btnButtonSet30.TabIndex = 26
        Me.btnButtonSet30.Text = "EncryptAuthWritePageEnc"
        '
        'btnButtonSet31
        '
        Me.btnButtonSet31.Location = New System.Drawing.Point(12, 19)
        Me.btnButtonSet31.Name = "btnButtonSet31"
        Me.btnButtonSet31.Size = New System.Drawing.Size(146, 24)
        Me.btnButtonSet31.TabIndex = 29
        Me.btnButtonSet31.Text = "EncryptComputeEnc"
        '
        'btnButtonSet32
        '
        Me.btnButtonSet32.Location = New System.Drawing.Point(426, 39)
        Me.btnButtonSet32.Name = "btnButtonSet32"
        Me.btnButtonSet32.Size = New System.Drawing.Size(122, 24)
        Me.btnButtonSet32.TabIndex = 30
        Me.btnButtonSet32.Text = "SecretStatus"
        '
        'txtEditDcgetbuf5
        '
        Me.txtEditDcgetbuf5.Location = New System.Drawing.Point(12, 56)
        Me.txtEditDcgetbuf5.Multiline = True
        Me.txtEditDcgetbuf5.Name = "txtEditDcgetbuf5"
        Me.txtEditDcgetbuf5.Size = New System.Drawing.Size(394, 121)
        Me.txtEditDcgetbuf5.TabIndex = 31
        '
        'txtEditDcgetbuf6
        '
        Me.txtEditDcgetbuf6.Location = New System.Drawing.Point(12, 56)
        Me.txtEditDcgetbuf6.Multiline = True
        Me.txtEditDcgetbuf6.Name = "txtEditDcgetbuf6"
        Me.txtEditDcgetbuf6.Size = New System.Drawing.Size(394, 81)
        Me.txtEditDcgetbuf6.TabIndex = 32
        '
        'btnButtonSet33
        '
        Me.btnButtonSet33.Location = New System.Drawing.Point(180, 17)
        Me.btnButtonSet33.Name = "btnButtonSet33"
        Me.btnButtonSet33.Size = New System.Drawing.Size(147, 24)
        Me.btnButtonSet33.TabIndex = 81
        Me.btnButtonSet33.Text = "Check ON/OFF"
        '
        'panel2
        '
        Me.panel2.Controls.Add(Me.rdoRadio1On1)
        Me.panel2.Controls.Add(Me.rdoRadio1Off1)
        Me.panel2.Controls.Add(Me.lblStatic13)
        Me.panel2.Location = New System.Drawing.Point(6, 19)
        Me.panel2.Name = "panel2"
        Me.panel2.Size = New System.Drawing.Size(193, 17)
        Me.panel2.TabIndex = 84
        '
        'rdoRadio1On1
        '
        Me.rdoRadio1On1.Location = New System.Drawing.Point(84, 0)
        Me.rdoRadio1On1.Name = "rdoRadio1On1"
        Me.rdoRadio1On1.Size = New System.Drawing.Size(45, 17)
        Me.rdoRadio1On1.TabIndex = 87
        Me.rdoRadio1On1.Text = "ON"
        '
        'rdoRadio1Off1
        '
        Me.rdoRadio1Off1.Location = New System.Drawing.Point(128, 0)
        Me.rdoRadio1Off1.Name = "rdoRadio1Off1"
        Me.rdoRadio1Off1.Size = New System.Drawing.Size(50, 17)
        Me.rdoRadio1Off1.TabIndex = 88
        Me.rdoRadio1Off1.Text = "OFF"
        '
        'lblStatic13
        '
        Me.lblStatic13.AutoSize = True
        Me.lblStatic13.Location = New System.Drawing.Point(14, 1)
        Me.lblStatic13.Name = "lblStatic13"
        Me.lblStatic13.Size = New System.Drawing.Size(54, 13)
        Me.lblStatic13.TabIndex = 89
        Me.lblStatic13.Text = "Function1"
        '
        'panel3
        '
        Me.panel3.Controls.Add(Me.rdoRadio1Off2)
        Me.panel3.Controls.Add(Me.rdoRadio1On2)
        Me.panel3.Controls.Add(Me.lblStatic14)
        Me.panel3.Location = New System.Drawing.Point(6, 37)
        Me.panel3.Name = "panel3"
        Me.panel3.Size = New System.Drawing.Size(193, 17)
        Me.panel3.TabIndex = 85
        '
        'rdoRadio1Off2
        '
        Me.rdoRadio1Off2.Location = New System.Drawing.Point(128, 0)
        Me.rdoRadio1Off2.Name = "rdoRadio1Off2"
        Me.rdoRadio1Off2.Size = New System.Drawing.Size(50, 17)
        Me.rdoRadio1Off2.TabIndex = 43
        Me.rdoRadio1Off2.Text = "OFF"
        '
        'rdoRadio1On2
        '
        Me.rdoRadio1On2.Location = New System.Drawing.Point(84, 0)
        Me.rdoRadio1On2.Name = "rdoRadio1On2"
        Me.rdoRadio1On2.Size = New System.Drawing.Size(45, 17)
        Me.rdoRadio1On2.TabIndex = 42
        Me.rdoRadio1On2.Text = "ON"
        '
        'lblStatic14
        '
        Me.lblStatic14.AutoSize = True
        Me.lblStatic14.Location = New System.Drawing.Point(14, 3)
        Me.lblStatic14.Name = "lblStatic14"
        Me.lblStatic14.Size = New System.Drawing.Size(54, 13)
        Me.lblStatic14.TabIndex = 44
        Me.lblStatic14.Text = "Function2"
        '
        'panel4
        '
        Me.panel4.Controls.Add(Me.rdoRadio1Off4)
        Me.panel4.Controls.Add(Me.rdoRadio1On4)
        Me.panel4.Controls.Add(Me.lblStatic16)
        Me.panel4.Location = New System.Drawing.Point(6, 74)
        Me.panel4.Name = "panel4"
        Me.panel4.Size = New System.Drawing.Size(193, 17)
        Me.panel4.TabIndex = 87
        '
        'rdoRadio1Off4
        '
        Me.rdoRadio1Off4.Location = New System.Drawing.Point(128, 0)
        Me.rdoRadio1Off4.Name = "rdoRadio1Off4"
        Me.rdoRadio1Off4.Size = New System.Drawing.Size(50, 17)
        Me.rdoRadio1Off4.TabIndex = 46
        Me.rdoRadio1Off4.Text = "OFF"
        '
        'rdoRadio1On4
        '
        Me.rdoRadio1On4.Location = New System.Drawing.Point(84, 0)
        Me.rdoRadio1On4.Name = "rdoRadio1On4"
        Me.rdoRadio1On4.Size = New System.Drawing.Size(45, 17)
        Me.rdoRadio1On4.TabIndex = 45
        Me.rdoRadio1On4.Text = "ON"
        '
        'lblStatic16
        '
        Me.lblStatic16.AutoSize = True
        Me.lblStatic16.Location = New System.Drawing.Point(14, 1)
        Me.lblStatic16.Name = "lblStatic16"
        Me.lblStatic16.Size = New System.Drawing.Size(54, 13)
        Me.lblStatic16.TabIndex = 47
        Me.lblStatic16.Text = "Function4"
        '
        'panel5
        '
        Me.panel5.Controls.Add(Me.rdoRadio1Off3)
        Me.panel5.Controls.Add(Me.rdoRadio1On3)
        Me.panel5.Controls.Add(Me.lblStatic15)
        Me.panel5.Location = New System.Drawing.Point(6, 56)
        Me.panel5.Name = "panel5"
        Me.panel5.Size = New System.Drawing.Size(193, 17)
        Me.panel5.TabIndex = 86
        '
        'rdoRadio1Off3
        '
        Me.rdoRadio1Off3.Location = New System.Drawing.Point(128, 0)
        Me.rdoRadio1Off3.Name = "rdoRadio1Off3"
        Me.rdoRadio1Off3.Size = New System.Drawing.Size(50, 17)
        Me.rdoRadio1Off3.TabIndex = 43
        Me.rdoRadio1Off3.Text = "OFF"
        '
        'rdoRadio1On3
        '
        Me.rdoRadio1On3.Location = New System.Drawing.Point(84, 0)
        Me.rdoRadio1On3.Name = "rdoRadio1On3"
        Me.rdoRadio1On3.Size = New System.Drawing.Size(45, 17)
        Me.rdoRadio1On3.TabIndex = 42
        Me.rdoRadio1On3.Text = "ON"
        '
        'lblStatic15
        '
        Me.lblStatic15.AutoSize = True
        Me.lblStatic15.Location = New System.Drawing.Point(14, 1)
        Me.lblStatic15.Name = "lblStatic15"
        Me.lblStatic15.Size = New System.Drawing.Size(54, 13)
        Me.lblStatic15.TabIndex = 44
        Me.lblStatic15.Text = "Function3"
        '
        'panel6
        '
        Me.panel6.Controls.Add(Me.rdoRadio1Off8)
        Me.panel6.Controls.Add(Me.rdoRadio1On8)
        Me.panel6.Controls.Add(Me.lblStatic20)
        Me.panel6.Location = New System.Drawing.Point(6, 148)
        Me.panel6.Name = "panel6"
        Me.panel6.Size = New System.Drawing.Size(193, 17)
        Me.panel6.TabIndex = 91
        '
        'rdoRadio1Off8
        '
        Me.rdoRadio1Off8.Location = New System.Drawing.Point(128, 0)
        Me.rdoRadio1Off8.Name = "rdoRadio1Off8"
        Me.rdoRadio1Off8.Size = New System.Drawing.Size(50, 17)
        Me.rdoRadio1Off8.TabIndex = 58
        Me.rdoRadio1Off8.Text = "OFF"
        '
        'rdoRadio1On8
        '
        Me.rdoRadio1On8.Location = New System.Drawing.Point(84, 0)
        Me.rdoRadio1On8.Name = "rdoRadio1On8"
        Me.rdoRadio1On8.Size = New System.Drawing.Size(45, 17)
        Me.rdoRadio1On8.TabIndex = 57
        Me.rdoRadio1On8.Text = "ON"
        '
        'lblStatic20
        '
        Me.lblStatic20.AutoSize = True
        Me.lblStatic20.Location = New System.Drawing.Point(14, 1)
        Me.lblStatic20.Name = "lblStatic20"
        Me.lblStatic20.Size = New System.Drawing.Size(54, 13)
        Me.lblStatic20.TabIndex = 59
        Me.lblStatic20.Text = "Function8"
        '
        'panel7
        '
        Me.panel7.Controls.Add(Me.rdoRadio1Off6)
        Me.panel7.Controls.Add(Me.rdoRadio1On6)
        Me.panel7.Controls.Add(Me.lblStatic18)
        Me.panel7.Location = New System.Drawing.Point(6, 111)
        Me.panel7.Name = "panel7"
        Me.panel7.Size = New System.Drawing.Size(193, 17)
        Me.panel7.TabIndex = 89
        '
        'rdoRadio1Off6
        '
        Me.rdoRadio1Off6.Location = New System.Drawing.Point(128, 0)
        Me.rdoRadio1Off6.Name = "rdoRadio1Off6"
        Me.rdoRadio1Off6.Size = New System.Drawing.Size(50, 17)
        Me.rdoRadio1Off6.TabIndex = 52
        Me.rdoRadio1Off6.Text = "OFF"
        '
        'rdoRadio1On6
        '
        Me.rdoRadio1On6.Location = New System.Drawing.Point(84, 0)
        Me.rdoRadio1On6.Name = "rdoRadio1On6"
        Me.rdoRadio1On6.Size = New System.Drawing.Size(45, 17)
        Me.rdoRadio1On6.TabIndex = 51
        Me.rdoRadio1On6.Text = "ON"
        '
        'lblStatic18
        '
        Me.lblStatic18.AutoSize = True
        Me.lblStatic18.Location = New System.Drawing.Point(14, 1)
        Me.lblStatic18.Name = "lblStatic18"
        Me.lblStatic18.Size = New System.Drawing.Size(54, 13)
        Me.lblStatic18.TabIndex = 53
        Me.lblStatic18.Text = "Function6"
        '
        'panel8
        '
        Me.panel8.Controls.Add(Me.rdoRadio1Off7)
        Me.panel8.Controls.Add(Me.rdoRadio1On7)
        Me.panel8.Controls.Add(Me.lblStatic19)
        Me.panel8.Location = New System.Drawing.Point(6, 130)
        Me.panel8.Name = "panel8"
        Me.panel8.Size = New System.Drawing.Size(193, 17)
        Me.panel8.TabIndex = 90
        '
        'rdoRadio1Off7
        '
        Me.rdoRadio1Off7.Location = New System.Drawing.Point(128, 0)
        Me.rdoRadio1Off7.Name = "rdoRadio1Off7"
        Me.rdoRadio1Off7.Size = New System.Drawing.Size(50, 17)
        Me.rdoRadio1Off7.TabIndex = 55
        Me.rdoRadio1Off7.Text = "OFF"
        '
        'rdoRadio1On7
        '
        Me.rdoRadio1On7.Location = New System.Drawing.Point(84, 0)
        Me.rdoRadio1On7.Name = "rdoRadio1On7"
        Me.rdoRadio1On7.Size = New System.Drawing.Size(45, 17)
        Me.rdoRadio1On7.TabIndex = 54
        Me.rdoRadio1On7.Text = "ON"
        '
        'lblStatic19
        '
        Me.lblStatic19.AutoSize = True
        Me.lblStatic19.Location = New System.Drawing.Point(14, 3)
        Me.lblStatic19.Name = "lblStatic19"
        Me.lblStatic19.Size = New System.Drawing.Size(54, 13)
        Me.lblStatic19.TabIndex = 56
        Me.lblStatic19.Text = "Function7"
        '
        'panel9
        '
        Me.panel9.Controls.Add(Me.rdoRadio1Off5)
        Me.panel9.Controls.Add(Me.rdoRadio1On5)
        Me.panel9.Controls.Add(Me.lblStatic17)
        Me.panel9.Location = New System.Drawing.Point(6, 93)
        Me.panel9.Name = "panel9"
        Me.panel9.Size = New System.Drawing.Size(193, 17)
        Me.panel9.TabIndex = 88
        '
        'rdoRadio1Off5
        '
        Me.rdoRadio1Off5.Location = New System.Drawing.Point(128, 0)
        Me.rdoRadio1Off5.Name = "rdoRadio1Off5"
        Me.rdoRadio1Off5.Size = New System.Drawing.Size(50, 17)
        Me.rdoRadio1Off5.TabIndex = 49
        Me.rdoRadio1Off5.Text = "OFF"
        '
        'rdoRadio1On5
        '
        Me.rdoRadio1On5.Location = New System.Drawing.Point(84, 0)
        Me.rdoRadio1On5.Name = "rdoRadio1On5"
        Me.rdoRadio1On5.Size = New System.Drawing.Size(45, 17)
        Me.rdoRadio1On5.TabIndex = 48
        Me.rdoRadio1On5.Text = "ON"
        '
        'lblStatic17
        '
        Me.lblStatic17.AutoSize = True
        Me.lblStatic17.Location = New System.Drawing.Point(14, 1)
        Me.lblStatic17.Name = "lblStatic17"
        Me.lblStatic17.Size = New System.Drawing.Size(54, 13)
        Me.lblStatic17.TabIndex = 50
        Me.lblStatic17.Text = "Function5"
        '
        'panel1
        '
        Me.panel1.Controls.Add(Me.rdoRadio1Off16)
        Me.panel1.Controls.Add(Me.rdoRadio1On16)
        Me.panel1.Controls.Add(Me.lblStatic28)
        Me.panel1.Location = New System.Drawing.Point(205, 148)
        Me.panel1.Name = "panel1"
        Me.panel1.Size = New System.Drawing.Size(193, 17)
        Me.panel1.TabIndex = 99
        '
        'rdoRadio1Off16
        '
        Me.rdoRadio1Off16.Location = New System.Drawing.Point(128, 0)
        Me.rdoRadio1Off16.Name = "rdoRadio1Off16"
        Me.rdoRadio1Off16.Size = New System.Drawing.Size(50, 17)
        Me.rdoRadio1Off16.TabIndex = 82
        Me.rdoRadio1Off16.Text = "OFF"
        '
        'rdoRadio1On16
        '
        Me.rdoRadio1On16.Location = New System.Drawing.Point(82, 0)
        Me.rdoRadio1On16.Name = "rdoRadio1On16"
        Me.rdoRadio1On16.Size = New System.Drawing.Size(45, 17)
        Me.rdoRadio1On16.TabIndex = 81
        Me.rdoRadio1On16.Text = "ON"
        '
        'lblStatic28
        '
        Me.lblStatic28.AutoSize = True
        Me.lblStatic28.Location = New System.Drawing.Point(14, 1)
        Me.lblStatic28.Name = "lblStatic28"
        Me.lblStatic28.Size = New System.Drawing.Size(60, 13)
        Me.lblStatic28.TabIndex = 83
        Me.lblStatic28.Text = "Function16"
        '
        'panel10
        '
        Me.panel10.Controls.Add(Me.rdoRadio1Off12)
        Me.panel10.Controls.Add(Me.rdoRadio1On12)
        Me.panel10.Controls.Add(Me.lblStatic24)
        Me.panel10.Location = New System.Drawing.Point(205, 74)
        Me.panel10.Name = "panel10"
        Me.panel10.Size = New System.Drawing.Size(193, 17)
        Me.panel10.TabIndex = 95
        '
        'rdoRadio1Off12
        '
        Me.rdoRadio1Off12.Location = New System.Drawing.Point(128, 0)
        Me.rdoRadio1Off12.Name = "rdoRadio1Off12"
        Me.rdoRadio1Off12.Size = New System.Drawing.Size(50, 17)
        Me.rdoRadio1Off12.TabIndex = 70
        Me.rdoRadio1Off12.Text = "OFF"
        '
        'rdoRadio1On12
        '
        Me.rdoRadio1On12.Location = New System.Drawing.Point(82, 0)
        Me.rdoRadio1On12.Name = "rdoRadio1On12"
        Me.rdoRadio1On12.Size = New System.Drawing.Size(45, 17)
        Me.rdoRadio1On12.TabIndex = 69
        Me.rdoRadio1On12.Text = "ON"
        '
        'lblStatic24
        '
        Me.lblStatic24.AutoSize = True
        Me.lblStatic24.Location = New System.Drawing.Point(14, 1)
        Me.lblStatic24.Name = "lblStatic24"
        Me.lblStatic24.Size = New System.Drawing.Size(60, 13)
        Me.lblStatic24.TabIndex = 71
        Me.lblStatic24.Text = "Function12"
        '
        'panel11
        '
        Me.panel11.Controls.Add(Me.rdoRadio1Off14)
        Me.panel11.Controls.Add(Me.rdoRadio1On14)
        Me.panel11.Controls.Add(Me.lblStatic26)
        Me.panel11.Location = New System.Drawing.Point(205, 111)
        Me.panel11.Name = "panel11"
        Me.panel11.Size = New System.Drawing.Size(193, 17)
        Me.panel11.TabIndex = 97
        '
        'rdoRadio1Off14
        '
        Me.rdoRadio1Off14.Location = New System.Drawing.Point(128, 0)
        Me.rdoRadio1Off14.Name = "rdoRadio1Off14"
        Me.rdoRadio1Off14.Size = New System.Drawing.Size(50, 17)
        Me.rdoRadio1Off14.TabIndex = 76
        Me.rdoRadio1Off14.Text = "OFF"
        '
        'rdoRadio1On14
        '
        Me.rdoRadio1On14.Location = New System.Drawing.Point(82, 0)
        Me.rdoRadio1On14.Name = "rdoRadio1On14"
        Me.rdoRadio1On14.Size = New System.Drawing.Size(45, 17)
        Me.rdoRadio1On14.TabIndex = 75
        Me.rdoRadio1On14.Text = "ON"
        '
        'lblStatic26
        '
        Me.lblStatic26.AutoSize = True
        Me.lblStatic26.Location = New System.Drawing.Point(14, 0)
        Me.lblStatic26.Name = "lblStatic26"
        Me.lblStatic26.Size = New System.Drawing.Size(60, 13)
        Me.lblStatic26.TabIndex = 77
        Me.lblStatic26.Text = "Function14"
        '
        'panel12
        '
        Me.panel12.Controls.Add(Me.rdoRadio1Off10)
        Me.panel12.Controls.Add(Me.rdoRadio1On10)
        Me.panel12.Controls.Add(Me.lblStatic22)
        Me.panel12.Location = New System.Drawing.Point(205, 37)
        Me.panel12.Name = "panel12"
        Me.panel12.Size = New System.Drawing.Size(193, 17)
        Me.panel12.TabIndex = 93
        '
        'rdoRadio1Off10
        '
        Me.rdoRadio1Off10.Location = New System.Drawing.Point(128, 0)
        Me.rdoRadio1Off10.Name = "rdoRadio1Off10"
        Me.rdoRadio1Off10.Size = New System.Drawing.Size(50, 17)
        Me.rdoRadio1Off10.TabIndex = 64
        Me.rdoRadio1Off10.Text = "OFF"
        '
        'rdoRadio1On10
        '
        Me.rdoRadio1On10.Location = New System.Drawing.Point(82, 0)
        Me.rdoRadio1On10.Name = "rdoRadio1On10"
        Me.rdoRadio1On10.Size = New System.Drawing.Size(45, 17)
        Me.rdoRadio1On10.TabIndex = 63
        Me.rdoRadio1On10.Text = "ON"
        '
        'lblStatic22
        '
        Me.lblStatic22.AutoSize = True
        Me.lblStatic22.Location = New System.Drawing.Point(14, 3)
        Me.lblStatic22.Name = "lblStatic22"
        Me.lblStatic22.Size = New System.Drawing.Size(60, 13)
        Me.lblStatic22.TabIndex = 65
        Me.lblStatic22.Text = "Function10"
        '
        'panel13
        '
        Me.panel13.Controls.Add(Me.rdoRadio1Off15)
        Me.panel13.Controls.Add(Me.rdoRadio1On15)
        Me.panel13.Controls.Add(Me.lblStatic27)
        Me.panel13.Location = New System.Drawing.Point(205, 130)
        Me.panel13.Name = "panel13"
        Me.panel13.Size = New System.Drawing.Size(193, 17)
        Me.panel13.TabIndex = 98
        '
        'rdoRadio1Off15
        '
        Me.rdoRadio1Off15.Location = New System.Drawing.Point(128, 0)
        Me.rdoRadio1Off15.Name = "rdoRadio1Off15"
        Me.rdoRadio1Off15.Size = New System.Drawing.Size(50, 17)
        Me.rdoRadio1Off15.TabIndex = 79
        Me.rdoRadio1Off15.Text = "OFF"
        '
        'rdoRadio1On15
        '
        Me.rdoRadio1On15.Location = New System.Drawing.Point(82, 0)
        Me.rdoRadio1On15.Name = "rdoRadio1On15"
        Me.rdoRadio1On15.Size = New System.Drawing.Size(45, 17)
        Me.rdoRadio1On15.TabIndex = 78
        Me.rdoRadio1On15.Text = "ON"
        '
        'lblStatic27
        '
        Me.lblStatic27.AutoSize = True
        Me.lblStatic27.Location = New System.Drawing.Point(14, 3)
        Me.lblStatic27.Name = "lblStatic27"
        Me.lblStatic27.Size = New System.Drawing.Size(60, 13)
        Me.lblStatic27.TabIndex = 80
        Me.lblStatic27.Text = "Function15"
        '
        'panel14
        '
        Me.panel14.Controls.Add(Me.rdoRadio1Off11)
        Me.panel14.Controls.Add(Me.rdoRadio1On11)
        Me.panel14.Controls.Add(Me.lblStatic23)
        Me.panel14.Location = New System.Drawing.Point(205, 56)
        Me.panel14.Name = "panel14"
        Me.panel14.Size = New System.Drawing.Size(193, 17)
        Me.panel14.TabIndex = 94
        '
        'rdoRadio1Off11
        '
        Me.rdoRadio1Off11.Location = New System.Drawing.Point(128, 0)
        Me.rdoRadio1Off11.Name = "rdoRadio1Off11"
        Me.rdoRadio1Off11.Size = New System.Drawing.Size(50, 17)
        Me.rdoRadio1Off11.TabIndex = 67
        Me.rdoRadio1Off11.Text = "OFF"
        '
        'rdoRadio1On11
        '
        Me.rdoRadio1On11.Location = New System.Drawing.Point(82, 0)
        Me.rdoRadio1On11.Name = "rdoRadio1On11"
        Me.rdoRadio1On11.Size = New System.Drawing.Size(45, 17)
        Me.rdoRadio1On11.TabIndex = 66
        Me.rdoRadio1On11.Text = "ON"
        '
        'lblStatic23
        '
        Me.lblStatic23.AutoSize = True
        Me.lblStatic23.Location = New System.Drawing.Point(14, 1)
        Me.lblStatic23.Name = "lblStatic23"
        Me.lblStatic23.Size = New System.Drawing.Size(60, 13)
        Me.lblStatic23.TabIndex = 68
        Me.lblStatic23.Text = "Function11"
        '
        'panel15
        '
        Me.panel15.Controls.Add(Me.rdoRadio1Off13)
        Me.panel15.Controls.Add(Me.rdoRadio1On13)
        Me.panel15.Controls.Add(Me.lblStatic25)
        Me.panel15.Location = New System.Drawing.Point(205, 93)
        Me.panel15.Name = "panel15"
        Me.panel15.Size = New System.Drawing.Size(193, 17)
        Me.panel15.TabIndex = 96
        '
        'rdoRadio1Off13
        '
        Me.rdoRadio1Off13.Location = New System.Drawing.Point(128, 0)
        Me.rdoRadio1Off13.Name = "rdoRadio1Off13"
        Me.rdoRadio1Off13.Size = New System.Drawing.Size(50, 17)
        Me.rdoRadio1Off13.TabIndex = 73
        Me.rdoRadio1Off13.Text = "OFF"
        '
        'rdoRadio1On13
        '
        Me.rdoRadio1On13.Location = New System.Drawing.Point(82, 0)
        Me.rdoRadio1On13.Name = "rdoRadio1On13"
        Me.rdoRadio1On13.Size = New System.Drawing.Size(45, 17)
        Me.rdoRadio1On13.TabIndex = 72
        Me.rdoRadio1On13.Text = "ON"
        '
        'lblStatic25
        '
        Me.lblStatic25.AutoSize = True
        Me.lblStatic25.Location = New System.Drawing.Point(14, 3)
        Me.lblStatic25.Name = "lblStatic25"
        Me.lblStatic25.Size = New System.Drawing.Size(60, 13)
        Me.lblStatic25.TabIndex = 74
        Me.lblStatic25.Text = "Function13"
        '
        'panel16
        '
        Me.panel16.Controls.Add(Me.rdoRadio1Off9)
        Me.panel16.Controls.Add(Me.rdoRadio1On9)
        Me.panel16.Controls.Add(Me.label1)
        Me.panel16.Location = New System.Drawing.Point(205, 19)
        Me.panel16.Name = "panel16"
        Me.panel16.Size = New System.Drawing.Size(193, 17)
        Me.panel16.TabIndex = 92
        '
        'rdoRadio1Off9
        '
        Me.rdoRadio1Off9.Location = New System.Drawing.Point(128, 0)
        Me.rdoRadio1Off9.Name = "rdoRadio1Off9"
        Me.rdoRadio1Off9.Size = New System.Drawing.Size(50, 17)
        Me.rdoRadio1Off9.TabIndex = 67
        Me.rdoRadio1Off9.Text = "OFF"
        '
        'rdoRadio1On9
        '
        Me.rdoRadio1On9.Location = New System.Drawing.Point(82, 0)
        Me.rdoRadio1On9.Name = "rdoRadio1On9"
        Me.rdoRadio1On9.Size = New System.Drawing.Size(45, 17)
        Me.rdoRadio1On9.TabIndex = 66
        Me.rdoRadio1On9.Text = "ON"
        '
        'label1
        '
        Me.label1.AutoSize = True
        Me.label1.Location = New System.Drawing.Point(14, 3)
        Me.label1.Name = "label1"
        Me.label1.Size = New System.Drawing.Size(54, 13)
        Me.label1.TabIndex = 68
        Me.label1.Text = "Function9"
        '
        'grpStatic10
        '
        Me.grpStatic10.Controls.Add(Me.btnButtonSet18)
        Me.grpStatic10.Controls.Add(Me.label2)
        Me.grpStatic10.Controls.Add(Me.btnButtonSet21)
        Me.grpStatic10.Controls.Add(Me.label3)
        Me.grpStatic10.Controls.Add(Me.txtEditDcsetbuf0)
        Me.grpStatic10.Controls.Add(Me.btnButtonSet32)
        Me.grpStatic10.Controls.Add(Me.txtEditDcsetbuf1)
        Me.grpStatic10.Controls.Add(Me.txtEditDcsetbuf10)
        Me.grpStatic10.Controls.Add(Me.txtEditDcsetbuf11)
        Me.grpStatic10.Controls.Add(Me.txtEditDcsetbuf12)
        Me.grpStatic10.Controls.Add(Me.txtEditDcsetbuf13)
        Me.grpStatic10.Controls.Add(Me.txtEditDcsetbuf14)
        Me.grpStatic10.Controls.Add(Me.txtEditDcsetbuf15)
        Me.grpStatic10.Controls.Add(Me.txtEditDcsetbuf16)
        Me.grpStatic10.Controls.Add(Me.txtEditDcsetbuf17)
        Me.grpStatic10.Controls.Add(Me.txtEditDcsetbuf18)
        Me.grpStatic10.Controls.Add(Me.txtEditDcsetbuf19)
        Me.grpStatic10.Controls.Add(Me.txtEditDcsetbuf2)
        Me.grpStatic10.Controls.Add(Me.txtEditDcsetbuf20)
        Me.grpStatic10.Controls.Add(Me.txtEditDcsetbuf21)
        Me.grpStatic10.Controls.Add(Me.txtEditDcsetbuf22)
        Me.grpStatic10.Controls.Add(Me.txtEditDcsetbuf23)
        Me.grpStatic10.Controls.Add(Me.txtEditDcsetbuf24)
        Me.grpStatic10.Controls.Add(Me.txtEditDcsetbuf25)
        Me.grpStatic10.Controls.Add(Me.txtEditDcsetbuf26)
        Me.grpStatic10.Controls.Add(Me.txtEditDcsetbuf27)
        Me.grpStatic10.Controls.Add(Me.txtEditDcsetbuf28)
        Me.grpStatic10.Controls.Add(Me.txtEditDcsetbuf29)
        Me.grpStatic10.Controls.Add(Me.txtEditDcsetbuf3)
        Me.grpStatic10.Controls.Add(Me.txtEditDcsetbuf30)
        Me.grpStatic10.Controls.Add(Me.txtEditDcsetbuf31)
        Me.grpStatic10.Controls.Add(Me.txtEditDcsetbuf4)
        Me.grpStatic10.Controls.Add(Me.txtEditDcsetbuf5)
        Me.grpStatic10.Controls.Add(Me.txtEditDcsetbuf6)
        Me.grpStatic10.Controls.Add(Me.txtEditDcsetbuf7)
        Me.grpStatic10.Controls.Add(Me.txtEditDcsetbuf8)
        Me.grpStatic10.Controls.Add(Me.txtEditDcsetbuf9)
        Me.grpStatic10.Location = New System.Drawing.Point(22, 99)
        Me.grpStatic10.Name = "grpStatic10"
        Me.grpStatic10.Size = New System.Drawing.Size(560, 155)
        Me.grpStatic10.TabIndex = 100
        Me.grpStatic10.TabStop = False
        Me.grpStatic10.Text = "Install and Set Secret"
        '
        'btnButtonSet18
        '
        Me.btnButtonSet18.Location = New System.Drawing.Point(426, 103)
        Me.btnButtonSet18.Name = "btnButtonSet18"
        Me.btnButtonSet18.Size = New System.Drawing.Size(122, 24)
        Me.btnButtonSet18.TabIndex = 150
        Me.btnButtonSet18.Text = "SetMasterSecret"
        '
        'label2
        '
        Me.label2.AutoSize = True
        Me.label2.Location = New System.Drawing.Point(15, 61)
        Me.label2.Name = "label2"
        Me.label2.Size = New System.Drawing.Size(38, 13)
        Me.label2.TabIndex = 141
        Me.label2.Text = "Secret"
        '
        'btnButtonSet21
        '
        Me.btnButtonSet21.Location = New System.Drawing.Point(426, 72)
        Me.btnButtonSet21.Name = "btnButtonSet21"
        Me.btnButtonSet21.Size = New System.Drawing.Size(122, 24)
        Me.btnButtonSet21.TabIndex = 149
        Me.btnButtonSet21.Text = "InstallSecret"
        '
        'label3
        '
        Me.label3.AutoSize = True
        Me.label3.Location = New System.Drawing.Point(15, 37)
        Me.label3.Name = "label3"
        Me.label3.Size = New System.Drawing.Size(62, 13)
        Me.label3.TabIndex = 6
        Me.label3.Text = "setbuf (hex)"
        '
        'txtEditDcsetbuf0
        '
        Me.txtEditDcsetbuf0.Location = New System.Drawing.Point(86, 33)
        Me.txtEditDcsetbuf0.Name = "txtEditDcsetbuf0"
        Me.txtEditDcsetbuf0.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditDcsetbuf0.Size = New System.Drawing.Size(27, 20)
        Me.txtEditDcsetbuf0.TabIndex = 5
        '
        'txtEditDcsetbuf1
        '
        Me.txtEditDcsetbuf1.Location = New System.Drawing.Point(117, 33)
        Me.txtEditDcsetbuf1.Name = "txtEditDcsetbuf1"
        Me.txtEditDcsetbuf1.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditDcsetbuf1.Size = New System.Drawing.Size(24, 20)
        Me.txtEditDcsetbuf1.TabIndex = 7
        '
        'txtEditDcsetbuf10
        '
        Me.txtEditDcsetbuf10.Location = New System.Drawing.Point(148, 59)
        Me.txtEditDcsetbuf10.Name = "txtEditDcsetbuf10"
        Me.txtEditDcsetbuf10.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditDcsetbuf10.Size = New System.Drawing.Size(24, 20)
        Me.txtEditDcsetbuf10.TabIndex = 26
        '
        'txtEditDcsetbuf11
        '
        Me.txtEditDcsetbuf11.Location = New System.Drawing.Point(178, 59)
        Me.txtEditDcsetbuf11.Name = "txtEditDcsetbuf11"
        Me.txtEditDcsetbuf11.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditDcsetbuf11.Size = New System.Drawing.Size(26, 20)
        Me.txtEditDcsetbuf11.TabIndex = 27
        '
        'txtEditDcsetbuf12
        '
        Me.txtEditDcsetbuf12.Location = New System.Drawing.Point(212, 59)
        Me.txtEditDcsetbuf12.Name = "txtEditDcsetbuf12"
        Me.txtEditDcsetbuf12.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditDcsetbuf12.Size = New System.Drawing.Size(27, 20)
        Me.txtEditDcsetbuf12.TabIndex = 28
        '
        'txtEditDcsetbuf13
        '
        Me.txtEditDcsetbuf13.Location = New System.Drawing.Point(244, 59)
        Me.txtEditDcsetbuf13.Name = "txtEditDcsetbuf13"
        Me.txtEditDcsetbuf13.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditDcsetbuf13.Size = New System.Drawing.Size(24, 20)
        Me.txtEditDcsetbuf13.TabIndex = 29
        '
        'txtEditDcsetbuf14
        '
        Me.txtEditDcsetbuf14.Location = New System.Drawing.Point(274, 59)
        Me.txtEditDcsetbuf14.Name = "txtEditDcsetbuf14"
        Me.txtEditDcsetbuf14.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditDcsetbuf14.Size = New System.Drawing.Size(24, 20)
        Me.txtEditDcsetbuf14.TabIndex = 30
        '
        'txtEditDcsetbuf15
        '
        Me.txtEditDcsetbuf15.Location = New System.Drawing.Point(304, 59)
        Me.txtEditDcsetbuf15.Name = "txtEditDcsetbuf15"
        Me.txtEditDcsetbuf15.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditDcsetbuf15.Size = New System.Drawing.Size(26, 20)
        Me.txtEditDcsetbuf15.TabIndex = 31
        '
        'txtEditDcsetbuf16
        '
        Me.txtEditDcsetbuf16.Location = New System.Drawing.Point(86, 85)
        Me.txtEditDcsetbuf16.Name = "txtEditDcsetbuf16"
        Me.txtEditDcsetbuf16.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditDcsetbuf16.Size = New System.Drawing.Size(27, 20)
        Me.txtEditDcsetbuf16.TabIndex = 32
        '
        'txtEditDcsetbuf17
        '
        Me.txtEditDcsetbuf17.Location = New System.Drawing.Point(117, 85)
        Me.txtEditDcsetbuf17.Name = "txtEditDcsetbuf17"
        Me.txtEditDcsetbuf17.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditDcsetbuf17.Size = New System.Drawing.Size(24, 20)
        Me.txtEditDcsetbuf17.TabIndex = 33
        '
        'txtEditDcsetbuf18
        '
        Me.txtEditDcsetbuf18.Location = New System.Drawing.Point(147, 85)
        Me.txtEditDcsetbuf18.Name = "txtEditDcsetbuf18"
        Me.txtEditDcsetbuf18.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditDcsetbuf18.Size = New System.Drawing.Size(24, 20)
        Me.txtEditDcsetbuf18.TabIndex = 34
        '
        'txtEditDcsetbuf19
        '
        Me.txtEditDcsetbuf19.Location = New System.Drawing.Point(177, 85)
        Me.txtEditDcsetbuf19.Name = "txtEditDcsetbuf19"
        Me.txtEditDcsetbuf19.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditDcsetbuf19.Size = New System.Drawing.Size(26, 20)
        Me.txtEditDcsetbuf19.TabIndex = 35
        '
        'txtEditDcsetbuf2
        '
        Me.txtEditDcsetbuf2.Location = New System.Drawing.Point(147, 33)
        Me.txtEditDcsetbuf2.Name = "txtEditDcsetbuf2"
        Me.txtEditDcsetbuf2.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditDcsetbuf2.Size = New System.Drawing.Size(24, 20)
        Me.txtEditDcsetbuf2.TabIndex = 8
        '
        'txtEditDcsetbuf20
        '
        Me.txtEditDcsetbuf20.Location = New System.Drawing.Point(210, 85)
        Me.txtEditDcsetbuf20.Name = "txtEditDcsetbuf20"
        Me.txtEditDcsetbuf20.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditDcsetbuf20.Size = New System.Drawing.Size(27, 20)
        Me.txtEditDcsetbuf20.TabIndex = 36
        '
        'txtEditDcsetbuf21
        '
        Me.txtEditDcsetbuf21.Location = New System.Drawing.Point(243, 85)
        Me.txtEditDcsetbuf21.Name = "txtEditDcsetbuf21"
        Me.txtEditDcsetbuf21.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditDcsetbuf21.Size = New System.Drawing.Size(24, 20)
        Me.txtEditDcsetbuf21.TabIndex = 37
        '
        'txtEditDcsetbuf22
        '
        Me.txtEditDcsetbuf22.Location = New System.Drawing.Point(273, 85)
        Me.txtEditDcsetbuf22.Name = "txtEditDcsetbuf22"
        Me.txtEditDcsetbuf22.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditDcsetbuf22.Size = New System.Drawing.Size(24, 20)
        Me.txtEditDcsetbuf22.TabIndex = 38
        '
        'txtEditDcsetbuf23
        '
        Me.txtEditDcsetbuf23.Location = New System.Drawing.Point(303, 85)
        Me.txtEditDcsetbuf23.Name = "txtEditDcsetbuf23"
        Me.txtEditDcsetbuf23.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditDcsetbuf23.Size = New System.Drawing.Size(26, 20)
        Me.txtEditDcsetbuf23.TabIndex = 39
        '
        'txtEditDcsetbuf24
        '
        Me.txtEditDcsetbuf24.Location = New System.Drawing.Point(86, 110)
        Me.txtEditDcsetbuf24.Name = "txtEditDcsetbuf24"
        Me.txtEditDcsetbuf24.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditDcsetbuf24.Size = New System.Drawing.Size(27, 20)
        Me.txtEditDcsetbuf24.TabIndex = 40
        '
        'txtEditDcsetbuf25
        '
        Me.txtEditDcsetbuf25.Location = New System.Drawing.Point(117, 110)
        Me.txtEditDcsetbuf25.Name = "txtEditDcsetbuf25"
        Me.txtEditDcsetbuf25.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditDcsetbuf25.Size = New System.Drawing.Size(24, 20)
        Me.txtEditDcsetbuf25.TabIndex = 41
        '
        'txtEditDcsetbuf26
        '
        Me.txtEditDcsetbuf26.Location = New System.Drawing.Point(147, 110)
        Me.txtEditDcsetbuf26.Name = "txtEditDcsetbuf26"
        Me.txtEditDcsetbuf26.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditDcsetbuf26.Size = New System.Drawing.Size(24, 20)
        Me.txtEditDcsetbuf26.TabIndex = 42
        '
        'txtEditDcsetbuf27
        '
        Me.txtEditDcsetbuf27.Location = New System.Drawing.Point(177, 110)
        Me.txtEditDcsetbuf27.Name = "txtEditDcsetbuf27"
        Me.txtEditDcsetbuf27.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditDcsetbuf27.Size = New System.Drawing.Size(26, 20)
        Me.txtEditDcsetbuf27.TabIndex = 43
        '
        'txtEditDcsetbuf28
        '
        Me.txtEditDcsetbuf28.Location = New System.Drawing.Point(210, 110)
        Me.txtEditDcsetbuf28.Name = "txtEditDcsetbuf28"
        Me.txtEditDcsetbuf28.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditDcsetbuf28.Size = New System.Drawing.Size(27, 20)
        Me.txtEditDcsetbuf28.TabIndex = 44
        '
        'txtEditDcsetbuf29
        '
        Me.txtEditDcsetbuf29.Location = New System.Drawing.Point(243, 110)
        Me.txtEditDcsetbuf29.Name = "txtEditDcsetbuf29"
        Me.txtEditDcsetbuf29.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditDcsetbuf29.Size = New System.Drawing.Size(24, 20)
        Me.txtEditDcsetbuf29.TabIndex = 45
        '
        'txtEditDcsetbuf3
        '
        Me.txtEditDcsetbuf3.Location = New System.Drawing.Point(177, 33)
        Me.txtEditDcsetbuf3.Name = "txtEditDcsetbuf3"
        Me.txtEditDcsetbuf3.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditDcsetbuf3.Size = New System.Drawing.Size(26, 20)
        Me.txtEditDcsetbuf3.TabIndex = 9
        '
        'txtEditDcsetbuf30
        '
        Me.txtEditDcsetbuf30.Location = New System.Drawing.Point(273, 110)
        Me.txtEditDcsetbuf30.Name = "txtEditDcsetbuf30"
        Me.txtEditDcsetbuf30.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditDcsetbuf30.Size = New System.Drawing.Size(24, 20)
        Me.txtEditDcsetbuf30.TabIndex = 46
        '
        'txtEditDcsetbuf31
        '
        Me.txtEditDcsetbuf31.Location = New System.Drawing.Point(303, 110)
        Me.txtEditDcsetbuf31.Name = "txtEditDcsetbuf31"
        Me.txtEditDcsetbuf31.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditDcsetbuf31.Size = New System.Drawing.Size(26, 20)
        Me.txtEditDcsetbuf31.TabIndex = 47
        '
        'txtEditDcsetbuf4
        '
        Me.txtEditDcsetbuf4.Location = New System.Drawing.Point(210, 33)
        Me.txtEditDcsetbuf4.Name = "txtEditDcsetbuf4"
        Me.txtEditDcsetbuf4.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditDcsetbuf4.Size = New System.Drawing.Size(27, 20)
        Me.txtEditDcsetbuf4.TabIndex = 20
        '
        'txtEditDcsetbuf5
        '
        Me.txtEditDcsetbuf5.Location = New System.Drawing.Point(243, 33)
        Me.txtEditDcsetbuf5.Name = "txtEditDcsetbuf5"
        Me.txtEditDcsetbuf5.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditDcsetbuf5.Size = New System.Drawing.Size(24, 20)
        Me.txtEditDcsetbuf5.TabIndex = 21
        '
        'txtEditDcsetbuf6
        '
        Me.txtEditDcsetbuf6.Location = New System.Drawing.Point(273, 33)
        Me.txtEditDcsetbuf6.Name = "txtEditDcsetbuf6"
        Me.txtEditDcsetbuf6.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditDcsetbuf6.Size = New System.Drawing.Size(24, 20)
        Me.txtEditDcsetbuf6.TabIndex = 22
        '
        'txtEditDcsetbuf7
        '
        Me.txtEditDcsetbuf7.Location = New System.Drawing.Point(303, 33)
        Me.txtEditDcsetbuf7.Name = "txtEditDcsetbuf7"
        Me.txtEditDcsetbuf7.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditDcsetbuf7.Size = New System.Drawing.Size(26, 20)
        Me.txtEditDcsetbuf7.TabIndex = 23
        '
        'txtEditDcsetbuf8
        '
        Me.txtEditDcsetbuf8.Location = New System.Drawing.Point(86, 59)
        Me.txtEditDcsetbuf8.Name = "txtEditDcsetbuf8"
        Me.txtEditDcsetbuf8.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditDcsetbuf8.Size = New System.Drawing.Size(27, 20)
        Me.txtEditDcsetbuf8.TabIndex = 24
        '
        'txtEditDcsetbuf9
        '
        Me.txtEditDcsetbuf9.Location = New System.Drawing.Point(118, 59)
        Me.txtEditDcsetbuf9.Name = "txtEditDcsetbuf9"
        Me.txtEditDcsetbuf9.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal
        Me.txtEditDcsetbuf9.Size = New System.Drawing.Size(24, 20)
        Me.txtEditDcsetbuf9.TabIndex = 25
        '
        'groupBox1
        '
        Me.groupBox1.Controls.Add(Me.panel2)
        Me.groupBox1.Controls.Add(Me.panel9)
        Me.groupBox1.Controls.Add(Me.panel5)
        Me.groupBox1.Controls.Add(Me.panel8)
        Me.groupBox1.Controls.Add(Me.panel16)
        Me.groupBox1.Controls.Add(Me.panel3)
        Me.groupBox1.Controls.Add(Me.panel15)
        Me.groupBox1.Controls.Add(Me.lblStatic3)
        Me.groupBox1.Controls.Add(Me.panel7)
        Me.groupBox1.Controls.Add(Me.txtEditDcgetbuf0)
        Me.groupBox1.Controls.Add(Me.panel14)
        Me.groupBox1.Controls.Add(Me.panel13)
        Me.groupBox1.Controls.Add(Me.panel4)
        Me.groupBox1.Controls.Add(Me.panel12)
        Me.groupBox1.Controls.Add(Me.panel1)
        Me.groupBox1.Controls.Add(Me.panel11)
        Me.groupBox1.Controls.Add(Me.panel10)
        Me.groupBox1.Controls.Add(Me.panel6)
        Me.groupBox1.Location = New System.Drawing.Point(22, 270)
        Me.groupBox1.Name = "groupBox1"
        Me.groupBox1.Size = New System.Drawing.Size(560, 231)
        Me.groupBox1.TabIndex = 101
        Me.groupBox1.TabStop = False
        Me.groupBox1.Text = "Current Data"
        '
        'groupBox2
        '
        Me.groupBox2.Controls.Add(Me.btnButtonSet29)
        Me.groupBox2.Controls.Add(Me.txtEditDcgetbuf6)
        Me.groupBox2.Controls.Add(Me.btnButtonSet33)
        Me.groupBox2.Location = New System.Drawing.Point(616, 99)
        Me.groupBox2.Name = "groupBox2"
        Me.groupBox2.Size = New System.Drawing.Size(423, 155)
        Me.groupBox2.TabIndex = 102
        Me.groupBox2.TabStop = False
        Me.groupBox2.Text = "Read Data"
        '
        'groupBox3
        '
        Me.groupBox3.Controls.Add(Me.btnButtonSet31)
        Me.groupBox3.Controls.Add(Me.txtEditDcgetbuf5)
        Me.groupBox3.Controls.Add(Me.btnButtonSet30)
        Me.groupBox3.Location = New System.Drawing.Point(616, 270)
        Me.groupBox3.Name = "groupBox3"
        Me.groupBox3.Size = New System.Drawing.Size(423, 231)
        Me.groupBox3.TabIndex = 103
        Me.groupBox3.TabStop = False
        Me.groupBox3.Text = "Encrpt and Write Data"
        '
        'FrmSamrtpoesampleDialog
        '
        Me.ClientSize = New System.Drawing.Size(1054, 517)
        Me.Controls.Add(Me.groupBox3)
        Me.Controls.Add(Me.groupBox2)
        Me.Controls.Add(Me.groupBox1)
        Me.Controls.Add(Me.grpStatic10)
        Me.Controls.Add(Me.grpStatic8)
        Me.Font = New System.Drawing.Font("Microsoft Sans Serif", 8.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.MaximizeBox = False
        Me.Name = "FrmSamrtpoesampleDialog"
        Me.Text = "License Management Sample"
        Me.grpStatic8.ResumeLayout(False)
        Me.grpStatic8.PerformLayout()
        Me.panel2.ResumeLayout(False)
        Me.panel2.PerformLayout()
        Me.panel3.ResumeLayout(False)
        Me.panel3.PerformLayout()
        Me.panel4.ResumeLayout(False)
        Me.panel4.PerformLayout()
        Me.panel5.ResumeLayout(False)
        Me.panel5.PerformLayout()
        Me.panel6.ResumeLayout(False)
        Me.panel6.PerformLayout()
        Me.panel7.ResumeLayout(False)
        Me.panel7.PerformLayout()
        Me.panel8.ResumeLayout(False)
        Me.panel8.PerformLayout()
        Me.panel9.ResumeLayout(False)
        Me.panel9.PerformLayout()
        Me.panel1.ResumeLayout(False)
        Me.panel1.PerformLayout()
        Me.panel10.ResumeLayout(False)
        Me.panel10.PerformLayout()
        Me.panel11.ResumeLayout(False)
        Me.panel11.PerformLayout()
        Me.panel12.ResumeLayout(False)
        Me.panel12.PerformLayout()
        Me.panel13.ResumeLayout(False)
        Me.panel13.PerformLayout()
        Me.panel14.ResumeLayout(False)
        Me.panel14.PerformLayout()
        Me.panel15.ResumeLayout(False)
        Me.panel15.PerformLayout()
        Me.panel16.ResumeLayout(False)
        Me.panel16.PerformLayout()
        Me.grpStatic10.ResumeLayout(False)
        Me.grpStatic10.PerformLayout()
        Me.groupBox1.ResumeLayout(False)
        Me.groupBox1.PerformLayout()
        Me.groupBox2.ResumeLayout(False)
        Me.groupBox2.PerformLayout()
        Me.groupBox3.ResumeLayout(False)
        Me.groupBox3.PerformLayout()
        Me.ResumeLayout(False)

    End Sub
	#End Region

	Private panel2 As Panel
	Private rdoRadio1On1 As RadioButton
	Private rdoRadio1Off1 As RadioButton
	Private lblStatic13 As Label
	Private panel3 As Panel
	Private rdoRadio1Off2 As RadioButton
	Private rdoRadio1On2 As RadioButton
	Private lblStatic14 As Label
	Private panel4 As Panel
	Private rdoRadio1Off4 As RadioButton
	Private rdoRadio1On4 As RadioButton
	Private lblStatic16 As Label
	Private panel5 As Panel
	Private rdoRadio1Off3 As RadioButton
	Private rdoRadio1On3 As RadioButton
	Private lblStatic15 As Label
	Private panel6 As Panel
	Private rdoRadio1Off8 As RadioButton
	Private rdoRadio1On8 As RadioButton
	Private lblStatic20 As Label
	Private panel7 As Panel
	Private rdoRadio1Off6 As RadioButton
	Private rdoRadio1On6 As RadioButton
	Private lblStatic18 As Label
	Private panel8 As Panel
	Private rdoRadio1Off7 As RadioButton
	Private rdoRadio1On7 As RadioButton
	Private lblStatic19 As Label
	Private panel9 As Panel
	Private rdoRadio1Off5 As RadioButton
	Private rdoRadio1On5 As RadioButton
	Private lblStatic17 As Label
	Private panel1 As Panel
	Private rdoRadio1Off16 As RadioButton
	Private rdoRadio1On16 As RadioButton
	Private lblStatic28 As Label
	Private panel10 As Panel
	Private rdoRadio1Off12 As RadioButton
	Private rdoRadio1On12 As RadioButton
	Private lblStatic24 As Label
	Private panel11 As Panel
	Private rdoRadio1Off14 As RadioButton
	Private rdoRadio1On14 As RadioButton
	Private lblStatic26 As Label
	Private panel12 As Panel
	Private rdoRadio1Off10 As RadioButton
	Private rdoRadio1On10 As RadioButton
	Private lblStatic22 As Label
	Private panel13 As Panel
	Private rdoRadio1Off15 As RadioButton
	Private rdoRadio1On15 As RadioButton
	Private lblStatic27 As Label
	Private panel14 As Panel
	Private rdoRadio1On11 As RadioButton
	Private lblStatic23 As Label
	Private panel15 As Panel
	Private rdoRadio1Off13 As RadioButton
	Private rdoRadio1On13 As RadioButton
	Private lblStatic25 As Label
	Private panel16 As Panel
	Private rdoRadio1Off9 As RadioButton
	Private rdoRadio1On9 As RadioButton
	Private label1 As Label
	Private grpStatic10 As GroupBox
	Private label2 As Label
	Private label3 As Label
	Private txtEditDcsetbuf0 As TextBox
	Private txtEditDcsetbuf1 As TextBox
	Private txtEditDcsetbuf10 As TextBox
	Private txtEditDcsetbuf11 As TextBox
	Private txtEditDcsetbuf12 As TextBox
	Private txtEditDcsetbuf13 As TextBox
	Private txtEditDcsetbuf14 As TextBox
	Private txtEditDcsetbuf15 As TextBox
	Private txtEditDcsetbuf16 As TextBox
	Private txtEditDcsetbuf17 As TextBox
	Private txtEditDcsetbuf18 As TextBox
	Private txtEditDcsetbuf19 As TextBox
	Private txtEditDcsetbuf2 As TextBox
	Private txtEditDcsetbuf20 As TextBox
	Private txtEditDcsetbuf21 As TextBox
	Private txtEditDcsetbuf22 As TextBox
	Private txtEditDcsetbuf23 As TextBox
	Private txtEditDcsetbuf24 As TextBox
	Private txtEditDcsetbuf25 As TextBox
	Private txtEditDcsetbuf26 As TextBox
	Private txtEditDcsetbuf27 As TextBox
	Private txtEditDcsetbuf28 As TextBox
	Private txtEditDcsetbuf29 As TextBox
	Private txtEditDcsetbuf3 As TextBox
	Private txtEditDcsetbuf30 As TextBox
	Private txtEditDcsetbuf31 As TextBox
	Private txtEditDcsetbuf4 As TextBox
	Private txtEditDcsetbuf5 As TextBox
	Private txtEditDcsetbuf6 As TextBox
	Private txtEditDcsetbuf7 As TextBox
	Private txtEditDcsetbuf8 As TextBox
	Private txtEditDcsetbuf9 As TextBox
    Friend WithEvents btnButtonSet21 As Button
    Friend WithEvents btnButtonSet18 As Button
	Private rdoRadio1Off11 As RadioButton
    Private groupBox1 As GroupBox
	Private groupBox2 As GroupBox
    Private groupBox3 As GroupBox

End Class
